### ISSUE TITLE
Add shadowsocks-libev as depend

### ISSUE THREAD

**Issue by LazyZhu** [shadowsocks/luci-app-shadowsocks#1]
You can use advanced dependency types:
https://wiki.openwrt.org/doc/devel/dependencies
Like choice only one package from `shadowsocks-libev`, `shadowsocks-libev-mbedtls` and `shadowsocks-libev-polarssl`.

**Comment by aa65535** [comment]
创建这个包的目的就是为了与 shadowsocks-libev 解耦, 它会使用 `ss-redir` 和 `ss-tunnel`, 但不一定非要由用户安装 shadowsocks-libev 这个包来获得.
只要检查到系统中有 `ss-redir` 和 `ss-tunnel` 这两个命令, 即可正常工作.

在 luci 页面, 有检查 `ss-redir`  是否存在，并给出提示.
启动时也会检查 `ss-redir` 和 `ss-tunnel` 这两个命令是否存在.

**Comment by LazyZhu** [comment]
It would make sense when install `luci-app-shadowsocks` automatically install one of `shadowsocks-libev`, you packeage does't fit the openwrt package rules.
You can check all offical packages of openwrt:
https://github.com/openwrt/packages/blob/master/net/luci-app-bcp38/Makefile#L24
https://github.com/openwrt/packages/blob/master/net/luci-app-clamav/Makefile#L25
https://github.com/openwrt/packages/blob/master/net/luci-app-squid/Makefile#L24
...

**Comment by LazyZhu** [comment]
Also, i suggest you use native `procd` to replace old init script:
https://wiki.openwrt.org/inbox/procd-init-scripts
And openwrt's libubox also included jshn.sh which can toally deal with json:
https://github.com/openwrt/openwrt/blob/chaos_calmer/package/network/config/netifd/files/lib/network/config.sh#L4

**Comment by braveguywallce** [comment]
@aa65535 原来我在用你的openwrt-shadowsocks时，也是先装shadowsocks-libev-spec ,然后再装你的luci-app-shadowcosk-spec. 这个项目和前面的luci-app-shadowsocks-spec有什么区别呢？前面的luci-app-shadowsocks-spec也无法单独工作的，所以我有点糊涂了。

**Comment by aa65535** [comment]
@LazyZhu 因为加密库有三个，依赖并不是很好解决，所以就不依赖（其实之前的 luci-app-shadowcosk-spec也没有依赖）。
当然，这个项目并不能算是一个标准的 luci application 软件包，只是为了方便。
目前的 init script 并没有必要使用 procd ，更方便自定义，也用不到 json 解析。

@braveguywallce 就是将 shadowsocks-libev-spec 的 ss-rules 、配置和 luci 放到一起了，现在的 openwrt-shadowsocks 只提供 ss-{local,redir,tunnel} 这几个二进制文件。

当前项目没依赖 shadowsocks-libev 或者相关软件包，可以由用户自己提供 ss-{redir,tunnel} 这两个二进制文件供 luci-app-shadowsocks 调用。
