### ISSUE TITLE
希望添加ss-local支持 

### ISSUE THREAD

**Issue by ysh815** [shadowsocks/luci-app-shadowsocks#10]
只想简单的用ss-local 不想用ss-redir  ss-tunnel  希望界面上提供ss-local 功能

我的用法是这样的, 在openwrt上用ss-local开启代理服务.
使用时在浏览器上SwitchyOmega做切换,毕竟有时候普通的网站也需要代理,但并不是每次都需要.
这种需求还是有的.
但是,luci-app-shadowsocks好像并不提供ss-local支持,希望添加上,能够在luci上配置,并查看状态

**Comment by cokebar** [comment]
直接使用原版shadowsocks-libev编译安装即可，配置好json文件后开机自启就行了，光用ss-local用不着luci，功能很简单。
PS: 路由上跑ss-local性能不佳

**Comment by cokebar** [comment]
性能是相对于PC和arm智能机来说，你要是arm双核或者四核路由当我没说

**Comment by whoistop** [comment]
https://github.com/ravageralpha/my_openwrt_mod
用这个。

**Comment by braveguywallce** [comment]
ss-local 还要放在路由上跑没有意义。

**Comment by ysh815** [comment]
ss-local功能确实非常简单,但不能说 用不着luci,毕竟有luci比没有更好用,况且还有不少小白.
至于性能, ss-local 比 ss-redir占资源更少,  ss-redir能在路由上跑,ss-local当让更可以.
ss-local 放在路由上的目的是不用在局域网内的每台电脑都装一个shadowsocks
