### ISSUE TITLE
Xchacha20

### ISSUE THREAD

**Issue by simonsmh** [shadowsocks/luci-app-shadowsocks#100]

**Comment by cokebar** [comment]
http://openwrt-dist.sourceforge.net/packages/LEDE/
http://openwrt-dist.sourceforge.net/packages/OpenWrt/
对应位置找到libsodium 1.0.12版本下载安装

**Comment by simonsmh** [comment]
我是说luci没有加xchacha20
其次，libsodium openwrt-feeds里更新到1012了

Cokebar Chi <notifications@github.com>于2017年3月16日周四 19:00写道：

http://openwrt-dist.sourceforge.net/packages/LEDE/
http://openwrt-dist.sourceforge.net/packages/OpenWrt/
对应位置找到libsodium 1.0.12版本下载安装

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/shadowsocks/luci-app-shadowsocks/issues/100#issuecomment-287023984>,
or mute the thread

**Comment by cokebar** [comment]
你标题写的太迷了

**Comment by simonsmh** [comment]
手机上，不小心点了个回车（
