### ISSUE TITLE
在不被默认tfo的设备上手动打开tfo

### ISSUE THREAD

**Issue by simonsmh** [shadowsocks/luci-app-shadowsocks#101]
希望tfo的选项在不被默认tfo的设备上可以手动打开tfo，而不是判断+隐藏。openwrt cc内核就已经是3.18了，基本上都能支持tfo
`echo 3 > /proc/sys/net/ipv4/tcp_fastopen`

**Comment by suikatomoki** [comment]
请问怎么判断客户端开启了fto，net.ipv4.tcp_fastopen = 1 以及 /etc/config/shadowsocks 字段 option fast_open '1' 就行了吗？谢谢

**Comment by simonsmh** [comment]
@suikatomoki 因为默认没开，所以服务器选项里没打勾肯定没开tfo。。（
其他的话我也不知道有什么好的debug方式，之前的issue也没讨论出结果，不是吗？

**Comment by suikatomoki** [comment]
@simonsmh 我怎么没那个选项 版本 1.6.3-1 
![qq 20170318205412](https://cloud.githubusercontent.com/assets/10336224/24072149/2757f04c-0c1d-11e7-9445-bf751c9955ab.png)
![qq 20170318205438](https://cloud.githubusercontent.com/assets/10336224/24072150/2788caf0-0c1d-11e7-99a1-cddf62921d2d.png)

**Comment by simonsmh** [comment]
对啊，tfo要求参数为3，而系统默认为1

suika <notifications@github.com>于2017年3月18日周六 20:55写道：

**Comment by suikatomoki** [comment]
@simonsmh 不是服务器为3 客户端为1吗？

**Comment by simonsmh** [comment]
openwrt也算是服务器啊（

suika <notifications@github.com>于2017年3月18日周六 20:57写道：

**Comment by suikatomoki** [comment]
@simonsmh 那个option fast_open '1' 
1是true的意思吧 默认0代表false

**Comment by suikatomoki** [comment]
@simonsmh 
https://github.com/shadowsocks/shadowsocks-libev/issues/713#issuecomment-231284017

**Comment by simonsmh** [comment]
```
local function support_fast_open()
	return luci.sys.exec("cat /proc/sys/net/ipv4/tcp_fastopen 2>/dev/null"):trim() == "3"
end
```
https://github.com/shadowsocks/luci-app-shadowsocks/blob/master/files/luci/model/cbi/shadowsocks/servers-details.lua

**Comment by suikatomoki** [comment]
@simonsmh 我懂你意思了 是我犯蠢了

**Comment by cokebar** [comment]
打开系统tfo应该不是luci-app-shadowsocks管的

**Comment by cokebar** [comment]
我发现最坑的居然是chrome，windows10下居然不支持tfo。。。
edge/firefox都支持了。。
貌似是因为微软那api有问题，导致chrome开了tfo以后若干功能坏掉了 所以一直没加进去
