### ISSUE TITLE
配置文件读取错误，/var/etc/shadowsocks.json 文件不存在（Mode : Lenovo Y1）

### ISSUE THREAD

**Issue by TienYow** [shadowsocks/luci-app-shadowsocks#103]
添加了服务信息，启动了Socks5代理，但是访问网站失败（ERR_CONNECTION_CLOSED），在SSH通过ps命令显示任务以下面的命令启动：
`ss-local -c /var/etc/shadowsocks.json -u -l 1080 --mtu 1492 -f /var/run/ss-local-1.pid`
复制这段命令运行提示：ERROR: Invalid config path.

**Comment by cokebar** [comment]
`/var/etc/shadowsocks.json`是init.d脚本读取uci配置后生成的配置文件，执行init.d之前肯定是不存在的

**Comment by cokebar** [comment]
检查socks5代理是否启动，检查PC端的代理配置是否正确

**Comment by TienYow** [comment]
我用SSH详细做了测试，只要带有 -c 配置就启动不起来，然后直接跳出帮助（-h）列表，不知道是不是我的路由解析不了json，我的配置文件如下
`
{
"server_host":"52.xxx.xxx.xxx",
"server_port":8388,
"local_address":"0.0.0.0",
"local_port":1080,
"password":"xxxxxxxx",
"method":"chacha20",
"timeout":60,
"plugin":"obfs-local",
"plugin_opts":"obfs=http;obfs-host=cloudfront.net"
}
`
用问完整命令就能启动：
`/usr/bin/ss-local -s 52.xxx.xxx.xxx -p 8388 -l 1080 -k xxxxxxxx -m chacha20 -t 6 -b 0.0.0.0 -f /var/run/ss-local.pid -u --fast-open --plugin obfs-local --plugin-opts "obfs=http;obfs-host=cloudfront.net"`

**Comment by TienYow** [comment]
修改了 /files/root/etc/init.d/shadowsocks 脚本，解决了我的问题

**Comment by aa65535** [comment]
`/var/etc` 这个目录存在不？

**Comment by aa65535** [comment]
json 里的字段是 `server` 不是  `server_host`
