### ISSUE TITLE
ss-tunnel 的那个目标地址是个什么鬼

### ISSUE THREAD

**Issue by TienYow** [shadowsocks/luci-app-shadowsocks#104]
$ ss-tunnel -h
`[-L <addr>:<port>]         Destination server address and port
                                  for local port forwarding.
`

他跟服务器的”-d“有什么关系？找了很久都没用相关帮助和说明
$ ss-server -h
`[-d <addr>]                Name servers for internal DNS resolver.
`

**Comment by aa65535** [comment]
它们俩没关系，所以你找不出相关说明。

`ss-tunnel -b 127.0.0.1 -l 1234 -L 8.8.8.8:53 ...`

表示发往 `127.0.0.1:1234` 的数据包会通过 ss-tunnel 转发到 `8.8.8.8:53`

`-d <addr>` 这个是 DNS 解析所使用的 DNS server 地址。

**Comment by TienYow** [comment]
@aa65535 你的意思是只做本地转发吗？那要选择“服务器”的作用是什么？

**Comment by cokebar** [comment]
@TienYow 单端口隧道协议

**Comment by aa65535** [comment]
@TienYow 上面 `ss-tunnel` 的 `-s` 和 `-p` 被省略了，`ss-{local,redir,tunnel}` 都是需要先与 `ss-server` 建了连接，然后由 `ss-server` 发起实际请求。
