### ISSUE TITLE
MTU设置导致UDP转发失败

### ISSUE THREAD

**Issue by terrytw** [shadowsocks/luci-app-shadowsocks#105]
从某一个版本起可以设置MTU了
大概是因为SS新版本的加密和混淆方式在数据包前面增加了几个字节？
总之SS-REDIR默认把MTU设置成1492，导致系统日志里面大量产生
kern.err ss-redir[1193]: [udp] server_recv_sendto fragmentation
kern.err ss-redir[1193]: [udp] server_recv_sendto fragmentation
kern.err ss-redir[1193]: [udp] server_recv_sendto fragmentation

服务端则是大量
ERROR: [udp] server_recv_recvfrom fragmentation: File exists
ERROR: [udp] server_recv_recvfrom fragmentation: File exists
ERROR: [udp] server_recv_recvfrom fragmentation: File exists
和
unable to resolve bbs.xxxx.com
unable to resolve api.xxx.com
unable to resolve sb.xxxx.com

请问MTU到底该设置成多少才合适？
试过1400，1492，1480，1500，都报错

**Comment by muronghan** [comment]
@terrytw 你是路由自己拨号吗？你在wan的override MTU里填多少？是1492？把它去掉试试看，ssdir里的override MTU仍然保持默认的1492

**Comment by terrytw** [comment]
@muronghan 
是路由器自己拨号
电信的网络
WAN里面的MTU没有设置

**Comment by cokebar** [comment]
有些电信是1480 ifconfig可以看，或者用ping试

**Comment by terrytw** [comment]
@cokebar 
pppoe-wan里面mtu是1492

**Comment by terrytw** [comment]
在服务端的config.json里面加入
"nameserver":"8.8.8.8",
"mtu":1500
似乎解决了这个问题
