### ISSUE TITLE
可以重现的死机 HELP!

### ISSUE THREAD

**Issue by whao** [shadowsocks/luci-app-shadowsocks#106]
`Device: Linksys WRT1900ACSv2 w/ OpenWrt Chaos Calmer 15.05.1`
昨天刚刚入手了新的1900ACS，然后迫不及待的开始配置。完成所有之后发现，路由器会不定时的死机，重启大概5-10min就会死机。死机就是：Wi-Fi信号突然消失，ethernet灯灭了，只剩power亮着，路由器ping不通，当然网页也是上不去 反正就是死死的死了。需要关机30s(时间短了还不行开开还是死着)以上然后开机才能正常工作，然后大概十几分钟就又死了：（

我一开始以为是硬件问题。reset了到干净的15.05.01。用了几个小时没有问题（Wi-Fi开着）。然后我开始装```ChinaDNS
luci-app-chinadns
dns-forwarder
luci-app-dns-forwarder
shadowsocks-libev
luci-app-shadowsocks```.
很巧，安装完之后大概3分钟左右就又死机了。我之后又重来的几次，安装完这几个包之后每次都可以稳定的死机。
之前在wndr4300&1900ac上面都没有遇到过这样的情况，不知道同志们有没有碰到过。system log里面看不到什么东西。crash log里面也什么都没有。我准备装个15.05试试看还是不是这样。装好了回来更新。

Any idea?
Best

**Comment by pexcn** [comment]
是硬件问题吧

**Comment by cokebar** [comment]
刷LEDE试试LEDE.

**Comment by whao** [comment]
@pexcn 不知道和v2版有没有关系。没有搜到太多v2版的信息。openwrt官网就说v2要newer wifi driver所以应该也不是什么问题

**Comment by whao** [comment]
@cokebar 刚刚下午刷LEDE了。很不幸，没有装任何东西，干净的跑了一会都死机了。。。。。但是很奇怪，官方固件和干净的op都可以跑，当然也有可能是没有触发bug对吧。。。。考虑要不要退货重发

**Comment by cokebar** [comment]
我希望的机型 没有问题。

**Comment by simonsmh** [comment]
> system log里面看不到什么东西。crash log里面也什么都没有。

系统设置里把级别改为debug，然后将崩溃时的log发送上来

**Comment by suikatomoki** [comment]
刚入手？ 试试退货吧，别人都没问题，我还想死机都死不了。

**Comment by whao** [comment]
谢谢同志们帮助。应该是硬件问题了。昨晚刷回了官方固件，夜里不知道什么时候死机了。。。退货重换一个了。。。
