### ISSUE TITLE
ss-rules的o参数问题

### ISSUE THREAD

**Issue by reusu** [shadowsocks/luci-app-shadowsocks#107]
请问-o之后加入OUTPUT链之后
是不是路由器本体出去也是走ss了
因为chinadns的海外ip经常阻塞
导致整个海外DNS解析不了
所以在想如果路由器本体海外访问也ok的话
应该就能解决了？

**Comment by aa65535** [comment]
ChinaDNS 上游搭配 DNS-Forwarder , 然后「代理自身」选择正常代理即可。

**Comment by suikatomoki** [comment]
补充：路由器自身DNS污染也要解决
WAN口设置→高级设置，取消“使用端局通告的DNS服务器”的勾选，并在“使用自定义的DNS服务器”中填入127.0.0.1
不然还是使用路由器上游提供的DNS 例如“运营商DNS“
