### ISSUE TITLE
ss-rules能添加IPV6转发的支持么

### ISSUE THREAD

**Issue by reusu** [shadowsocks/luci-app-shadowsocks#109]
因为这边本地电信是有分配IPV6地址
并且可以直通海外
使用的时候发现youtube视频非常慢
然后就发现DNS是解析到IPV6的地址去了
将电脑的IPV6协商关掉一切正常

那么问题来了
我的远端服务器也是有IPV6出口的
那么可以将IPV6转发到SS服务器出去么

**Comment by reusu** [comment]
ping r1---sn-i3b7kn7z.googlevideo.com

正在 Ping r1.sn-i3b7kn7z.googlevideo.com [2404:6800:400c:2::7] 具有 32 字节的数据:
来自 2404:6800:400c:2::7 的回复: 时间=121ms
请求超时。
来自 2404:6800:400c:2::7 的回复: 时间=126ms
来自 2404:6800:400c:2::7 的回复: 时间=125ms

2404:6800:400c:2::7 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 3，丢失 = 1 (25% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 121ms，最长 = 126ms，平均 = 124ms

ping r1---sn-i3b7kn7z.googlevideo.com

正在 Ping r1.sn-i3b7kn7z.googlevideo.com [74.125.102.87] 具有 32 字节的数据:
请求超时。
请求超时。
请求超时。
 请求超时。

74.125.102.87 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 0，丢失 = 4 (100% 丢失)，

**Comment by reusu** [comment]
顺带问一下另一个问题
我这边是用dnsmasq+chinadns+dnsf进行的dns解析
顺带因为业务原因有添加了dnsmasq-hosts的解析文件
但是在启动影梭服务之后
发现icmp是可以正常返回hosts内的解析的
但是使用浏览器访问远端
貌似是被解析到了正确的ip上
导致业务不可行
那么请问下如何关闭这个远端再解析的功能呢

**Comment by cokebar** [comment]
dual stack is a disaster.
disable ipv6 on your router.
