### ISSUE TITLE
每次升级安装就会 Collected errors

### ISSUE THREAD

**Issue by chnt7305** [shadowsocks/luci-app-shadowsocks#11]
Configuring luci-app-shadowsocks.
Collected errors:
 * resolve_conffiles: Existing conffile /etc/config/shadowsocks is different from the conffile in the new package. The new conffile will be placed at /etc/config/shadowsocks-opkg.

用opkg  --force-maintainer 覆盖掉已经存在的配置文件就不会有错误提示了，但是要重新配置。。。
忽略这个错误？

**Comment by aa65535** [comment]
这是正常的, 可以忽略.
因为旧的配置默认不会被覆盖, 新的配置文件保存在 `/etc/config/shadowsocks-opkg`.
