### ISSUE TITLE
 Cannot satisfy the following dependencies for iptables-mod-tproxy

### ISSUE THREAD

**Issue by tporwx** [shadowsocks/luci-app-shadowsocks#111]
我自己编译了wndr4300的LEDE 17.01.0的固件，打开了128M空间。
但是安装iptables-mod-tproxy时遇到错误提示：
 Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for iptables-mod-tproxy:
 *      kernel (= 4.4.50-1-bce704651ad97b2c16dec9baa6b46324) *
 * opkg_install_cmd: Cannot install package iptables-mod-tproxy.

是自编译的问题吗？应该怎么解决?(除了强制安装)

**Comment by aa65535** [comment]
自己编译的话顺便把 iptables-mod-tproxy 也选上，别想用官方源的 kmod.
打开 128M 空间可以修改 Image Builder 做到，这样可以使用官方源。

**Comment by no1be4me** [comment]
I have this same error on LEDE with Kernel 4.4.79 for Luci-app-shadowsocks_1.8.1-1_all.ipk same with iptables-mod-tproxy

**Comment by cokebar** [comment]
@no1be4me LEDE 17.01记得已经是4.9的内核了 因此自编译的4.4内核需要在编译时就勾选这个包。

**Comment by no1be4me** [comment]
Cokebar, you mind saying the above in English pls. My Chinese's is really not at all, and my translator is just as bad.
When I try to install I get Kernel 4.4.71 so I take it luci-app-shadowsocks_1.8.1-1_all.ipk is looking for this Kernel.

**Comment by cokebar** [comment]
@no1be4me LEDE 17.01's official image use 4.9 kernel. But you're using a 3rd-party ROM which use 4.4 kernel. So you should build the kmod depends with 4.4 kernel by yourself. Or you should consider flashing officical LEDE 17.01.2 ROM

**Comment by aa65535** [comment]
@cokebar LEDE 17.01.2 kernel version is 4.4.71,  https://lede-project.org/releases/17.01/notes-17.01.2 .

**Comment by cokebar** [comment]
@aa65535 sorry I make a mistake. snapshot use a newer kernel while release version use 4.4

**Comment by techotaku** [comment]
@no1be4me If you want install [iptables-mod-tproxy](https://lede-project.org/packages/pkgdata/iptables-mod-tproxy), your image kernel must include [kmod-ipt-tproxy](https://lede-project.org/packages/pkgdata/kmod-ipt-tproxy). *(menuconfig -> kernel-modules -> netfilter-extensions)*

**Comment by no1be4me** [comment]
Thanks for sending!   
  
  
  

  
  

  
  
>
