### ISSUE TITLE
Where is "TCP Fast Open" option to set

### ISSUE THREAD

**Issue by ddqp** [shadowsocks/luci-app-shadowsocks#113]
请问，在哪能设置，我在luci的shadowsocks里面没看到这个选项，无论是服务器设置还是其他地方，都没看到。
luci的版本是v1.6.3-1
shadowsocks libev版本3.0.5-1

**Comment by suikatomoki** [comment]
echo 3 > /proc/sys/net/ipv4/tcp_fastopen
https://github.com/shadowsocks/luci-app-shadowsocks/issues/101#issue-215187317

有混淆还需要在plugin_opts中添加fast-open
https://github.com/shadowsocks/shadowsocks-libev/issues/1399#issuecomment-289353555

**Comment by ddqp** [comment]
收到，谢谢！
