### ISSUE TITLE
关于fastopen 无法在配置文件中启用fast_open true

### ISSUE THREAD

**Issue by milebye** [shadowsocks/luci-app-shadowsocks#118]
ss 的启动配置文件在/var/etc/下，这个文件是由init.d/shadowsocks生成
默认配置不导入/etc/config/shadowsocks中有关fastopen的配置
所以无论怎么设置/etc/config/shadowsocks都不会启用fastopen

**Comment by cokebar** [comment]
https://github.com/shadowsocks/luci-app-shadowsocks/blob/master/files/root/etc/init.d/shadowsocks#L132
启动脚本中tfo通过命令行开启 不是通过config file

**Comment by milebye** [comment]
实际测试，我把tcp_fastopen值改为3，还是没有启动。tfo 的值并没有传送到命令行。
我手动添加--fast-open命令，系统值为1时，tcpfastopen一样生效，所以由/pro/sys/net/ipv4/tcp_fastopen的值来判断好吗？

**Comment by cokebar** [comment]
@milebye tcp_fastopen=3是开启tfo的前提：
if [ "3" = "$(cat /proc/sys/net/ipv4/tcp_fastopen 2>/dev/null)" ]; then

满足这个前提后，再去uci配置文件中取fast_open的值，如果是true，则补上--fast-open参数
uci_bool_by_name $1 fast_open && echo "--fast-open"

通过ps命令看到 fastopen参数是正常加上去的：
32308 root      2276 S    ss-redir -c /var/etc/shadowsocks.json --fast-open -l 9080 --mtu 1492 --reuse-port -f /var/run/ss-redir-1.

**Comment by milebye** [comment]
- -!  解决了，还需要在配置文件中添加fast_open true 选项，不过默认luci在添加服务器的时候没有添加fast_open的选项。 
!!!!!
我刚又去查看了下，原来需要把fastopen值改为3时，添加或修改服务器时才出现是否打开tcpfastopen。。。
建议修改下，客户端为1时，我实测同样有效。。

**Comment by milebye** [comment]
@cokebar   另外有个问题，想请教下   
上周末我才把openwrt换成lede 17.1.1 ，结果现在又出了 17.1.2。。 
我这才刚刚配置完毕，不想从头再来一遍..  而且我发现我的软件包已经全部是最新的了。
还需要升级吗？
或者可以把软件包全部升级到最新？ 然后直接换个内核文件就行？

**Comment by cokebar** [comment]
@milebye 
1.luci的服务器配置里有tfo的选项的啊，1.6.3 加进去了
2.同时作为服务端和客户端的话需要tcp_fast_open=3：https://bg2bkk.github.io/post/tcp_fast_open%E7%9A%84%E6%A6%82%E5%BF%B5%20%E4%BD%9C%E7%94%A8%E4%BB%A5%E5%8F%8A%E5%AE%9E%E7%8E%B0/
3. 升级可以保留配置文件升级 不过包要重装。会编译rom的话可以自己做个makefile的patch，把自己的配置文件和额外需要的包加进去，官方更新后，使用这个patch编译新rom就行了

**Comment by milebye** [comment]
@cokebar  对，luci也会判断，但那文章说了他是本地测试所以需要改3，但路由一般不会做为服务器，只是客户端，而且像我这样，本来设置好了的，想试fastopen时就会遇到各种问题，手动添加到配置文件无效，原因是没有先改fastopen值为3

**Comment by cokebar** [comment]
@milebye ss-redir既是客户端也是服务端

**Comment by milebye** [comment]
@cokebar   
ss-redir 只能算一个客户端吧，因为它并不对外提供服务，ss-local我觉得可以算。能给局域网提供代理，redir只是我们改了路由包，我是这么理解的。也不知道理解对不。

0 关闭，1客户端，2服务器，3同时启用。
我的理解是我们需要减少与远端服务器之间的RTT，而不内部网络之间，内部网络基本可以忽略，当然也可以打开，但内部主机支不支持又是一回事了。

当值为1时，我确实观测到TCPFastOpenPassive在增长，所以还是不要由值为3才打开，因为就算不支持，打开fast-open也不影响连接，这时走正常流程。

所以建议还是不要把值为3才打开，大于1就可以打开了。 不然许多新人会出现和我一样的问题。

**Comment by cokebar** [comment]
TFO我不懂 不瞎猜了 求助大神 @aa65535 @madeye @wongsyrone

**Comment by cokebar** [comment]
@milebye luci里改成检测到tcp_fastopen不满足条件时候给出提示 而不是直接隐藏掉选项 可能好些

**Comment by cokebar** [comment]
@milebye 之前某个issue讨论过这个问题 #101

**Comment by milebye** [comment]
@cokebar   至少我觉得，因为默认为1，这时添加ss时不会有提示是否打开fastopen选项，这个需要修改下，因为不知道的人可能就选否，知道就选1，当fastopen不正常时，他们会去上网查，这时网上通常都会有把值改为3，这时，他在luci中打开fastopen选项，重启ss就正常了。

**Comment by simonsmh** [comment]
#101

**Comment by milebye** [comment]
无人处理。close.
