### ISSUE TITLE
servers服务器配置 -> server 仅支持填写IP地址

### ISSUE THREAD

**Issue by also1412** [shadowsocks/luci-app-shadowsocks#119]
servers服务器配置 -> server应同时允许填写hostname和IP地址，配合Shadowsocks-libev for OpenWrt的配置方式：

+--------+----------+--------------------------------+
|  键名      |  数据类型  |                      说明                         |
+--------+----------+--------------------------------+
| server    |    字符串   | 服务器地址, 可以是 IP 或者域名    |
+--------+----------+--------------------------------+

**Comment by cokebar** [comment]
duplicated. #30
