### ISSUE TITLE
内网下无法使用小米盒子的AirPlay

### ISSUE THREAD

**Issue by badsirius** [shadowsocks/luci-app-shadowsocks#121]
1. 设备Netgear WNDR4300(网件4300)
2. Openwrt Version: CC 15.05.01
3. 安装了 Openwrt-Shadowsocks/luci-app-shadowsocks/ChinaDNS/dns-forward/Openwrt-luci-dist
4. **问题**
开启ss和和设置dns-forward和ChinaDNS，内网下iOS设备无法找到同一内网的小米盒子的AirPlay。
关闭ss和将DNS查询方式恢复成固件默认方式后，iOS设备可以找到小米盒子的AirPlay信号。

请问有谁遇到类似情况的吗？

**Comment by aa65535** [comment]
只恢复 DNS 设置是否会正常？
