### ISSUE TITLE
udp服务器（UDP relay）需要哪些其他包支持？

### ISSUE THREAD

**Issue by hdstar2009** [shadowsocks/luci-app-shadowsocks#123]
有款新的路由器因为Lede等适配无线驱动有问题，最后在BB适配下发现无线驱动正常使用。
BB固件中已经有添加iptables-mod-tproxy，ip，ipsets，dnsmasq-full，kmod-ipt-tproxy等组件，安装2.4x版或者更新的其他版的shadowsocks-libev（以前在mt7620a的BB上一直正常使用）发现udp relay都无法实现。
shadowsocks-libev安装最新的3.07版本，选择UDP服务器也不会提示缺少iptables-mod-tproxy，但是udp relay就是无法实现（换之前老的mt7620a的路由器udp relay可以实现），所以想问下作者，udp relay这个功能有没有其他什么必须要的包？

同时，怎么来手工验证或者说检查udp relay功能是否正常运作？（我现在检查udp relay是否成功是通过第三方的那个NatTypeTester软件和在SS服务器上看udp数据是否有接收到）

**Comment by tianlichunhong** [comment]
你确定你的服务器已经将udp relay功能打开了？

**Comment by aa65535** [comment]
启动没报错就说明不缺少包。

**Comment by suikatomoki** [comment]
pc上
dig www.google.com @8.8.8.8 
能正确解析就行
-U 的 ss进程确定存在吗？

**Comment by xjduke** [comment]
同样的问题，UDP Relay 无效 LEDE Reboot 17.01.2+Shadowsocks 3.0.7 （2.6也一样）SS上联正常，服务器开启了UDP代理，但是服务器收不到UDP的转发！同一台服务器我用树莓派自己安装ss并且按网上设置iptables后一切正常！

**Comment by WordlessEcho** [comment]
[package: iptables-mod-tproxy](https://lede-project.org/packages/pkgdata/iptables-mod-tproxy)
稍微说一下，假如是拉最新的代码编译，似乎要顺便编译一个 ipstable-mod-tproxy 出来，因为好像和最新的内核不太兼容
你们也可以试一下我编译的版本，我的路由是 Newifi Mini，和你的应该是可以用同样的包的
gongjianwei.com/lede
