### ISSUE TITLE
“访问控制”页面不正常

### ISSUE THREAD

**Issue by WordlessEcho** [shadowsocks/luci-app-shadowsocks#126]
以下是错误信息

```log
/usr/lib/lua/luci/dispatcher.lua:469: Failed to execute cbi dispatcher target for entry '/admin/services/shadowsocks/access-control'.
The called action terminated with an exception:
...ib/lua/luci/model/cbi/shadowsocks/access-control.lua:92: attempt to call field 'arptable' (a nil value)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:469: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:121: in function </usr/lib/lua/luci/dispatcher.lua:120>
```

复现率是百分百，已经尝试过看起来像是相似问题的 #8 中所推荐的方法：
- 重启
- 清除缓存

均没有作用

**Comment by cokebar** [comment]
217a004

**Comment by cokebar** [comment]
build with latest commit

**Comment by WordlessEcho** [comment]
@cokebar 感谢，问题解决了，正在看你的教程 XD

Problem in 1.6.3.
Fixed in next version.

**Comment by G0510OLD** [comment]
@WordlessEcho @cokebar 本人纯小白，刚才给路由器装SS的时候也出了一样的问题，请问可以告知详细的解决方法吗？

**Comment by WordlessEcho** [comment]
@G0510OLD 简单说，这个版本（1.6.1）有问题，作者虽然修了，但是还没有打包
我已经基于 rapimps/mt7620 的 **LEDE** SDK 编译了一个版本，现在我分享出来，你只需要：

(DELETED)

**Comment by G0510OLD** [comment]
@WordlessEcho 解决了，非常感谢！！

**Comment by WordlessEcho** [comment]
最新版已修复此问题，我的服务器不再提供自编译版本，请前去下载作者的最新版

**Comment by G0510OLD** [comment]
可以提供一个地址吗？多谢。

2017-07-19 13:41 GMT+08:00 Wordless Echo <notifications@github.com>:

**Comment by cokebar** [comment]
@G0510OLD https://github.com/shadowsocks/luci-app-shadowsocks/releases
releases页面就是发布正式版本用的
1.7.0版本修复此问题

**Comment by flyher** [comment]
@WordlessEcho 
之前的版本没遇到过，更新到1.70版本出现了此问题。

**Comment by WordlessEcho** [comment]
@flyher 无法复现，请详细描述你的问题

**Comment by flyher** [comment]
@WordlessEcho 
昨天更新luci 1.63到1.7的，更新完毕，重启，访问面板 “控制访问”，报你在一楼的错误。

**Comment by WordlessEcho** [comment]
@flyher 
```bash
root@Newifi-Mini:/tmp# opkg install luci-app-shadowsocks_1.7.0-1_all.ipk
Package luci-app-shadowsocks (1.7.0-1) installed in root is up to date.
```
我使用的是 all 版本，并没有出现问题
你确定你的报错和我是一模一样的吗？

**Comment by aa65535** [comment]
@flyher 
请提供你的固件版本；
1.7 已经不存在 dispatch 方法，所以不可能报错跟一楼一样。

**Comment by flyher** [comment]
@WordlessEcho 
同all版，貌似错误信息的行号不一样，早期的版本我是从spec升级上来的;

@aa65535 
openwrt14的固件，具体内容等我晚上再切到新版本复现给你;

**Comment by aa65535** [comment]
@flyher spec 版需要先卸载掉，然后重新安装这个。

**Comment by WordlessEcho** [comment]
@flyher 请你新开 issue

**Comment by flyher** [comment]
@aa65535 
spec版本很久以前已经卸载过的，luci也是从1.7版本报错的。

@WordlessEcho 
好像忘了这个issue，我把这个issue加到闹钟提醒我不要忘记～_～，复现如果出现我会新开一个。

**Comment by flyher** [comment]
@aa65535 
@WordlessEcho 
确实是我的问题，测试了1.7和1.8，报错的日志我在这个issue  #134 中贴了出来。
