### ISSUE TITLE
luci-app-shadowsocks运行不到10来秒就停止

### ISSUE THREAD

**Issue by jack338c** [shadowsocks/luci-app-shadowsocks#133]
能打开google,u2,但不到10来秒就死，同时发现/var/etc shadowsocks.json下这个配置文件也自动消失
同样shadowsocks-libev版本用shadowsocks-libev原版gfwlist就没有问题

请问有这种情况吗？
谢谢

**Comment by aa65535** [comment]
使用的版本？
ss 进程是否还在？
`iptables-save -t nat` 打印的内容？

**Comment by jack338c** [comment]
版本shadowsocks-libev 3.0.6
进程等下分享你（正在编译到那个出问题的固件）
等下打印与你

最新发现：编译shadowsocks-libev时注释别的，只保留ss-redir，就没有问题
补充，之前都没问题的，加了这个料---https://github.com/gwlim/mips74k-ar71xx-lede-patch,就出现上述问题

感谢这么晚还帮答疑解惑！

**Comment by jack338c** [comment]
问题解决了，换个shadowsocks-libev版本就可以了
感谢您的时间!
