### ISSUE TITLE
目前的版本连接多个服务器能智能分流吗？

### ISSUE THREAD

**Issue by hfangit** [shadowsocks/luci-app-shadowsocks#135]
我先在可以同时使用，伦敦，东京，洛杉矶的服务器， 目前的版本，我用的chnroute路由表，我访问一个非中国IP，它会优先连接哪个服务器？

**Comment by aa65535** [comment]
https://github.com/shadowsocks/shadowsocks-libev/issues/493

这里的负载均衡是系统行为，具体效果需要自己测试。

以下是我测试的结果（可能不准确）：
同一个会话只使用一个连接；
不同会话会使用不同的连接，具体选择哪个连接，是随机的；
多个连接中有一个或者多个不可用的话，会自动选择可用的连接。
