### ISSUE TITLE
Feature request: Add dst default

### ISSUE THREAD

**Issue by lvqier** [shadowsocks/luci-app-shadowsocks#136]
Hi @aa65535，
现在目标IP地址的默认行为是走 ss-redir，但在我的应用场景下，只有 match 白名单的 IP 需要走代理。因此希望在 Redir Rules -> Destination Settings 下增加一个 "dst default" 选项，可通过该选项配置默认 forward 或者默认 bypass，这样可以实现更灵活的转发规则。

谢谢！

**Comment by aa65535** [comment]
不是很明白你的需求。

另外，Redir Rules -> Destination Settings  在哪？

2017年8月6日 23:11，Qier LU <notifications@github.com>写道：

Hi @aa65535<https://github.com/aa65535>，
现在目标IP地址的默认行为是走 ss-redir，但在我的应用场景下，只有 match 白名单的 IP 需要走代理。因此希望在 Redir Rules -> Destination Settings 下增加一个 "dst default" 选项，可通过该选项配置默认 forward 或者默认 bypass，这样可以实现更灵活的转发规则。

谢谢！

**Comment by lvqier** [comment]
Sorry，我按 LEDE trunk 上的版本来描述的，似乎是个很老的版本。。
从最终生成的 iptables 规则角度来描述，希望可以配置成：
`
*nat
...
-A SS_SPEC_LAN_AC -m set --match-set ss_spec_src_bp src -j RETURN
-A SS_SPEC_LAN_AC -m set --match-set ss_spec_src_fw src -j SS_SPEC_WAN_FW
-A SS_SPEC_LAN_AC -m set --match-set ss_spec_src_ac src -j SS_SPEC_WAN_AC
-A SS_SPEC_LAN_AC -j SS_SPEC_WAN_AC
-A SS_SPEC_LAN_DG -m set --match-set ss_spec_dst_sp dst -j RETURN
-A SS_SPEC_LAN_DG -p tcp -j SS_SPEC_LAN_AC
-A SS_SPEC_WAN_AC -m set --match-set ss_spec_dst_fw dst -j SS_SPEC_WAN_FW
-A SS_SPEC_WAN_AC -m set --match-set ss_spec_dst_bp dst -j RETURN
-A SS_SPEC_WAN_AC -j RETURN
`
主要是最后一行，即 SS_SPEC_WAN_AC 默认不转发。

**Comment by cokebar** [comment]
@lvqier 
进入 Luci 界面 -> 访问控制 -> 外网区域
「被忽略IP列表」 选择留空(/dev/null)
「额外被忽略IP」 设置为 0.0.0.0/1 和 128.0.0.0/1
「走代理IP列表」 设置为你需要强制走代理的IP的列表文件即可

**Comment by aa65535** [comment]
@lvqier 按照 @cokebar 提供的方法配置即可。
