### ISSUE TITLE
Transparent proxy not working after upgrade

### ISSUE THREAD

**Issue by EvianZhow** [shadowsocks/luci-app-shadowsocks#138]
I'm using the ipset version of this app, during service startup, I encountered the error below, causing firewall not to include redirect rules, so transparent proxy not working anymore. Guess another compatible issue here? 

Router Firmware: OpenWRT 14.04
LuCI App Version: 1.8.0 (master, self-compiled)

Debug log:
```
ipset v6.20.1: Error in line 1: Syntax error: typename 'hash:mac' is unknown
ss-rules[32281]: Start failed!
```

**Comment by EvianZhow** [comment]
Using the without-ipset version works fine. So should I upgrade my ipset version (ipset v6.20.1) or stick to the current one? Package manager said it's the latest version.

**Comment by EvianZhow** [comment]
FYI: According to http://ipset.netfilter.org/changelog.html, hash:mac appeared to be available in version 6.22 or later.

**Comment by EvianZhow** [comment]
So quite interested about the performance differences between ipset and without-ipset version. Thank you!

**Comment by aa65535** [comment]
ipset v6.20 not support 'hash:mac'.
You'd better upgrade the firmware to v15.05 and above.
