### ISSUE TITLE
LEDE17.01 启用SS 网络周期性断流

### ISSUE THREAD

**Issue by crackself** [shadowsocks/luci-app-shadowsocks#141]
WNDR 4300v1  LEDE17.01 ，编译时启用LEDEfeed源里的SS，SS设置为ignore.list模式，开启后路由器大概运行10-15分钟出现一次网络断流现象（国内外网站均无法访问，约3分钟左右恢复）。同一个固件对比，不开启SS无此问题。
[system_log.txt](https://github.com/shadowsocks/luci-app-shadowsocks/files/1219624/system_log.txt)

**Comment by suikatomoki** [comment]
同WNDR 4300v1 17.01 版，同编译路由器固件时同时启用ss全套 并开启128M flash 没有出现你说的问题
固件由 https://downloads.lede-project.org/releases/17.01.2/targets/ar71xx/nand/lede-imagebuilder-17.01.2-ar71xx-nand.Linux-x86_64.tar.xz 构建

**Comment by crackself** [comment]
谢谢指导。我是通过源码编译的，这个会有差别吗

**Comment by suikatomoki** [comment]
@crackself 源码编译问题很多 不建议 我都试过 
imagebuilder 才是最佳实践

**Comment by crackself** [comment]
嗯，我也试试
