### ISSUE TITLE
为什么升级了luci-app1.8.0和1.8.1都用不了，只能装回1.7.0才能用

### ISSUE THREAD

**Issue by mie1987** [shadowsocks/luci-app-shadowsocks#142]
本来我用luci-app1.7.0和shadowsocks-libev_3.0.8-1，今天升级到luci-app1.8.1之后翻不了，于是全新安装1.8.0和shadowsocks-libev，还是不行，最后装回1.7.0才能翻啊，为什么。配置文件都删除重新装的。用PandoraBox 17.01，小米mini，7620

**Comment by aa65535** [comment]
没有提供有用的信息，我只能推测是因为 ipset 版本过低引起的错误，参考 #138
