### ISSUE TITLE
更新luci-app-shadowsocks和shadowsocks-libev后，shadowsocks不再会随路由重启而自动重启

### ISSUE THREAD

**Issue by Balanky** [shadowsocks/luci-app-shadowsocks#143]
/etc/init.d/shadwosocks enable后也一样。

**Comment by aa65535** [comment]
log?

**Comment by Balanky** [comment]
Mon Aug 28 20:43:24 2017 kern.debug kernel: [   16.420000] ath: doing EEPROM country->regdmn map search
Mon Aug 28 20:43:24 2017 kern.debug kernel: [   16.420000] ath: country maps to regdmn code: 0x3a
Mon Aug 28 20:43:24 2017 kern.debug kernel: [   16.420000] ath: Country alpha2 being used: US
Mon Aug 28 20:43:24 2017 kern.debug kernel: [   16.420000] ath: Regpair used: 0x3a
Mon Aug 28 20:43:24 2017 kern.info kernel: [   16.420000] cfg80211: Calling CRDA for country: US
Mon Aug 28 20:43:24 2017 kern.info kernel: [   16.450000] cfg80211: Regulatory domain changed to country: US
Mon Aug 28 20:43:24 2017 kern.info kernel: [   16.450000] cfg80211:  DFS Master region: FCC
Mon Aug 28 20:43:24 2017 kern.info kernel: [   16.460000] cfg80211:   (start_freq - end_freq @ bandwidth), (max_antenna_gain, max_eirp), (dfs_cac_time)
Mon Aug 28 20:43:24 2017 kern.info kernel: [   16.470000] cfg80211:   (2402000 KHz - 2472000 KHz @ 40000 KHz), (N/A, 3000 mBm), (N/A)
Mon Aug 28 20:43:24 2017 kern.info kernel: [   16.470000] cfg80211:   (5170000 KHz - 5250000 KHz @ 80000 KHz, 160000 KHz AUTO), (N/A, 2300 mBm), (N/A)
Mon Aug 28 20:43:24 2017 kern.info kernel: [   16.480000] cfg80211:   (5250000 KHz - 5330000 KHz @ 80000 KHz, 160000 KHz AUTO), (N/A, 2300 mBm), (0 s)
Mon Aug 28 20:43:24 2017 kern.info kernel: [   16.490000] cfg80211:   (5490000 KHz - 5730000 KHz @ 160000 KHz), (N/A, 2300 mBm), (0 s)
Mon Aug 28 20:43:24 2017 kern.info kernel: [   16.500000] cfg80211:   (5735000 KHz - 5835000 KHz @ 80000 KHz), (N/A, 3000 mBm), (N/A)
Mon Aug 28 20:43:24 2017 kern.info kernel: [   16.510000] cfg80211:   (57240000 KHz - 63720000 KHz @ 2160000 KHz), (N/A, 4000 mBm), (N/A)
Mon Aug 28 20:43:24 2017 kern.info kernel: [   16.540000] ip_tables: (C) 2000-2006 Netfilter Core Team
Mon Aug 28 20:43:24 2017 kern.info kernel: [   16.570000] nf_conntrack version 0.5.0 (1964 buckets, 7856 max)
Mon Aug 28 20:43:24 2017 kern.info kernel: [   16.650000] xt_time: kernel timezone is -0000
Mon Aug 28 20:43:24 2017 kern.info kernel: [   16.690000] PPP generic driver version 2.4.2
Mon Aug 28 20:43:24 2017 kern.info kernel: [   16.700000] NET: Registered protocol family 24
Mon Aug 28 20:43:24 2017 kern.debug kernel: [   16.720000] ath: EEPROM regdomain: 0x0
Mon Aug 28 20:43:24 2017 kern.debug kernel: [   16.720000] ath: EEPROM indicates default country code should be used
Mon Aug 28 20:43:24 2017 kern.debug kernel: [   16.720000] ath: doing EEPROM country->regdmn map search
Mon Aug 28 20:43:24 2017 kern.debug kernel: [   16.720000] ath: country maps to regdmn code: 0x3a
Mon Aug 28 20:43:24 2017 kern.debug kernel: [   16.720000] ath: Country alpha2 being used: US
Mon Aug 28 20:43:24 2017 kern.debug kernel: [   16.720000] ath: Regpair used: 0x3a
Mon Aug 28 20:43:24 2017 kern.debug kernel: [   16.730000] ieee80211 phy1: Selected rate control algorithm 'minstrel_ht'
Mon Aug 28 20:43:24 2017 kern.info kernel: [   16.730000] ieee80211 phy1: Atheros AR9340 Rev:2 mem=0xb8100000, irq=47
Mon Aug 28 20:43:27 2017 cron.info crond[953]: crond (busybox 1.23.2) started, log level 8
Mon Aug 28 20:43:27 2017 authpriv.info dropbear[973]: Not backgrounding
Mon Aug 28 20:43:30 2017 kern.info ss-redir[1098]: initializing ciphers... chacha20-ietf-poly1305
Mon Aug 28 20:43:30 2017 user.emerg syslog:  2017-08-28 20:43:30 INFO: set MTU to 1492
Mon Aug 28 20:43:30 2017 user.emerg syslog:  2017-08-28 20:43:30 INFO: plugin "obfs-local" enabled
Mon Aug 28 20:43:30 2017 user.emerg syslog:  2017-08-28 20:43:30 INFO: using tcp fast open
Mon Aug 28 20:43:30 2017 kern.info ss-redir[1098]: tcp port reuse enabled
Mon Aug 28 20:43:30 2017 kern.info ss-redir[1098]: UDP relay enabled
Mon Aug 28 20:43:30 2017 kern.err ss-redir[1098]: [udp] getaddrinfo: ai_family not supported
Mon Aug 28 20:43:30 2017 kern.err ss-redir[1098]: [udp] bind() error
Mon Aug 28 20:43:30 2017 kern.info ss-redir[1105]: initializing ciphers... chacha20-ietf-poly1305
Mon Aug 28 20:43:30 2017 kern.info ss-redir[1105]: tcp port reuse enabled
Mon Aug 28 20:43:30 2017 kern.info ss-redir[1105]: UDP relay enabled
**Mon Aug 28 20:43:30 2017 kern.err ss-redir[1105]: [udp] getaddrinfo: ai_family not supported
Mon Aug 28 20:43:30 2017 kern.err ss-redir[1105]: [udp] bind() error**
Mon Aug 28 20:43:31 2017 kern.info kernel: [   26.880000] device eth1 entered promiscuous mode
Mon Aug 28 20:43:31 2017 kern.info kernel: [   26.920000] br-lan: port 1(eth1) entered forwarding state
Mon Aug 28 20:43:31 2017 kern.info kernel: [   26.920000] br-lan: port 1(eth1) entered forwarding state
Mon Aug 28 20:43:31 2017 daemon.notice netifd: Interface 'lan' is enabled
Mon Aug 28 20:43:31 2017 daemon.notice netifd: Interface 'lan' is setting up now
Mon Aug 28 20:43:31 2017 daemon.notice netifd: Interface 'lan' is now up
Mon Aug 28 20:43:31 2017 daemon.notice netifd: Interface 'loopback' is enabled
Mon Aug 28 20:43:31 2017 daemon.notice netifd: Interface 'loopback' is setting up now
Mon Aug 28 20:43:31 2017 daemon.notice netifd: Interface 'loopback' is now up
Mon Aug 28 20:43:31 2017 daemon.notice netifd: Interface 'wan' is enabled
Mon Aug 28 20:43:31 2017 daemon.notice netifd: Interface 'wan6' is enabled
Mon Aug 28 20:43:31 2017 kern.info kernel: [   27.010000] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
Mon Aug 28 20:43:31 2017 daemon.notice netifd: Bridge 'br-lan' link is up
Mon Aug 28 20:43:31 2017 daemon.notice netifd: Interface 'lan' has link connectivity 
Mon Aug 28 20:43:31 2017 daemon.notice netifd: Network device 'lo' link is up
Mon Aug 28 20:43:31 2017 daemon.notice netifd: Interface 'loopback' has link connectivity 
Mon Aug 28 20:43:32 2017 user.notice firewall: Reloading firewall due to ifup of lan (br-lan)
Mon Aug 28 20:43:33 2017 daemon.notice netifd: Bridge 'br-lan' link is down
Mon Aug 28 20:43:33 2017 daemon.notice netifd: Interface 'lan' has link connectivity loss
Mon Aug 28 20:43:33 2017 kern.info kernel: [   28.280000] br-lan: port 1(eth1) entered disabled state
Mon Aug 28 20:43:34 2017 kern.info kernel: [   29.280000] eth0: link up (100Mbps/Full duplex)
Mon Aug 28 20:43:34 2017 daemon.notice netifd: Network device 'eth0' link is up
Mon Aug 28 20:43:34 2017 daemon.notice netifd: Interface 'wan' has link connectivity 
Mon Aug 28 20:43:34 2017 daemon.notice netifd: Interface 'wan' is setting up now
Mon Aug 28 20:43:34 2017 daemon.notice netifd: Interface 'wan6' has link connectivity 
Mon Aug 28 20:43:34 2017 daemon.notice netifd: Interface 'wan6' is setting up now
Mon Aug 28 20:43:34 2017 kern.info kernel: [   29.320000] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
Mon Aug 28 20:43:34 2017 daemon.notice netifd: wan (1412): udhcpc (v1.23.2) started
Mon Aug 28 20:43:35 2017 daemon.notice netifd: radio0 (1234): Configuration file: /var/run/hostapd-phy1.conf
Mon Aug 28 20:43:35 2017 kern.info kernel: [   30.490000] IPv6: ADDRCONF(NETDEV_UP): wlan1: link is not ready
Mon Aug 28 20:43:35 2017 daemon.notice netifd: radio1 (1235): Configuration file: /var/run/hostapd-phy0.conf
Mon Aug 28 20:43:35 2017 daemon.notice netifd: radio0 (1234): wlan1: interface state UNINITIALIZED->COUNTRY_UPDATE
Mon Aug 28 20:43:35 2017 kern.info kernel: [   30.530000] device wlan1 entered promiscuous mode
Mon Aug 28 20:43:35 2017 daemon.notice netifd: wan (1412): Sending discover...
Mon Aug 28 20:43:35 2017 daemon.notice netifd: wan (1412): Sending select for 192.168.1.2...
Mon Aug 28 20:43:35 2017 daemon.notice netifd: wan (1412): Lease of 192.168.1.2 obtained, lease time 86400
Mon Aug 28 20:43:35 2017 kern.warn kernel: [   31.070000] ath10k_pci 0000:00:00.0: otp stream is empty, using board.bin contents
Mon Aug 28 20:43:37 2017 user.emerg syslog: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Mon Aug 28 20:43:37 2017 user.err ss-rules[1174]: Start failed!
Mon Aug 28 20:43:37 2017 user.emerg syslog: ss-rules[1174]: Start failed!
Mon Aug 28 20:43:38 2017 kern.info kernel: [   33.350000] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
Mon Aug 28 20:43:38 2017 kern.info kernel: [   33.380000] device wlan0 entered promiscuous mode
Mon Aug 28 20:43:38 2017 daemon.notice netifd: Interface 'wan' is now up
Mon Aug 28 20:43:38 2017 daemon.notice netifd: radio0 (1234): Using interface wlan1 with hwaddr 04:a1:51:88:25:3d and ssid "DONG."
Mon Aug 28 20:43:38 2017 daemon.notice netifd: radio1 (1235): wlan0: interface state UNINITIALIZED->HT_SCAN
Mon Aug 28 20:43:39 2017 user.emerg syslog:  2017-08-28 20:43:38 INFO: set MTU to 1492
Mon Aug 28 20:43:39 2017 user.emerg syslog:  2017-08-28 20:43:39 INFO: plugin "obfs-local" enabled
Mon Aug 28 20:43:39 2017 kern.info ss-local[1566]: using tcp fast open
Mon Aug 28 20:43:39 2017 kern.info ss-local[1565]: using tcp fast open
Mon Aug 28 20:43:39 2017 kern.info ss-local[1566]: initializing ciphers... chacha20-ietf-poly1305
Mon Aug 28 20:43:39 2017 kern.info ss-local[1565]: initializing ciphers... chacha20-ietf-poly1305
Mon Aug 28 20:43:39 2017 kern.info ss-local[1566]: tcp port reuse enabled
Mon Aug 28 20:43:39 2017 kern.info ss-local[1565]: tcp port reuse enabled
Mon Aug 28 20:43:39 2017 kern.info ss-local[1566]: udprelay enabled
Mon Aug 28 20:43:39 2017 kern.info ss-local[1565]: udprelay enabled
Mon Aug 28 20:43:39 2017 kern.info ss-local[1566]: udp port reuse enabled
Mon Aug 28 20:43:39 2017 kern.info ss-local[1566]: listening at 0.0.0.0:1080
Mon Aug 28 20:43:39 2017 kern.info ss-local[1566]: running from root user
Mon Aug 28 20:43:39 2017 kern.info ss-local[1565]: udp port reuse enabled
Mon Aug 28 20:43:39 2017 kern.info ss-local[1565]: listening at 0.0.0.0:1080
Mon Aug 28 20:43:39 2017 kern.info ss-local[1565]: running from root user
Mon Aug 28 20:43:39 2017 user.emerg syslog:  2017-08-28 20:43:39 INFO: set MTU to 1492
Mon Aug 28 20:43:39 2017 user.emerg syslog:  2017-08-28 20:43:39 INFO: plugin "obfs-local" enabled
Mon Aug 28 20:43:39 2017 kern.info ss-tunnel[1634]: initializing ciphers... chacha20-ietf-poly1305
Mon Aug 28 20:43:39 2017 daemon.notice netifd: radio1 (1235): Using interface wlan0 with hwaddr 04:a1:51:88:25:3f and ssid "DONG.5G"
Mon Aug 28 20:43:39 2017 kern.info ss-tunnel[1639]: initializing ciphers... chacha20-ietf-poly1305
Mon Aug 28 20:43:39 2017 kern.info ss-tunnel[1639]: tcp port reuse enabled
Mon Aug 28 20:43:39 2017 kern.info ss-tunnel[1639]: UDP relay enabled
Mon Aug 28 20:43:39 2017 kern.info ss-tunnel[1639]: udp port reuse enabled
Mon Aug 28 20:43:39 2017 kern.info ss-tunnel[1639]: listening at 0.0.0.0:5353
Mon Aug 28 20:43:39 2017 kern.info ss-tunnel[1639]: running from root user
Mon Aug 28 20:43:39 2017 kern.info ss-tunnel[1634]: tcp port reuse enabled
Mon Aug 28 20:43:39 2017 kern.info ss-tunnel[1634]: UDP relay enabled
Mon Aug 28 20:43:39 2017 kern.info ss-tunnel[1634]: udp port reuse enabled
Mon Aug 28 20:43:39 2017 kern.info ss-tunnel[1634]: listening at 0.0.0.0:5353
Mon Aug 28 20:43:39 2017 kern.info ss-tunnel[1634]: running from root user
Mon Aug 28 20:43:39 2017 daemon.notice netifd: radio0 (1234): wlan1: interface state COUNTRY_UPDATE->ENABLED
Mon Aug 28 20:43:39 2017 daemon.notice netifd: radio0 (1234): wlan1: AP-ENABLED 
Mon Aug 28 20:43:39 2017 kern.info kernel: [   35.030000] br-lan: port 2(wlan1) entered forwarding state
Mon Aug 28 20:43:39 2017 kern.info kernel: [   35.030000] br-lan: port 2(wlan1) entered forwarding state
Mon Aug 28 20:43:39 2017 kern.info kernel: [   35.040000] IPv6: ADDRCONF(NETDEV_CHANGE): wlan1: link becomes ready
Mon Aug 28 20:43:39 2017 daemon.notice netifd: Bridge 'br-lan' link is up
Mon Aug 28 20:43:39 2017 daemon.notice netifd: Interface 'lan' has link connectivity 
Mon Aug 28 20:43:40 2017 user.emerg syslog: setting up led WAN (green)
Mon Aug 28 20:43:40 2017 user.emerg syslog: setting up led USB
Mon Aug 28 20:43:40 2017 user.emerg syslog: setting up led WLAN
Mon Aug 28 20:43:40 2017 daemon.info dnsmasq[1662]: started, version 2.73 cachesize 150
Mon Aug 28 20:43:40 2017 daemon.info dnsmasq[1662]: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP no-DHCPv6 no-Lua TFTP no-conntrack no-ipset no-auth no-DNSSEC loop-detect inotify
Mon Aug 28 20:43:40 2017 daemon.info dnsmasq[1662]: DNS service limited to local subnets
Mon Aug 28 20:43:40 2017 daemon.info dnsmasq-dhcp[1662]: DHCP, IP range 10.0.0.100 -- 10.0.0.249, lease time 12h
Mon Aug 28 20:43:40 2017 daemon.info dnsmasq[1662]: using nameserver 127.0.0.1#5354
Mon Aug 28 20:43:40 2017 daemon.info dnsmasq[1662]: read /etc/hosts - 1 addresses
Mon Aug 28 20:43:40 2017 daemon.info dnsmasq[1662]: read /tmp/hosts/dhcp - 1 addresses
Mon Aug 28 20:43:40 2017 daemon.info dnsmasq-dhcp[1662]: read /etc/ethers - 0 addresses
Mon Aug 28 20:43:40 2017 daemon.notice netifd: Network device 'wlan1' link is up
Mon Aug 28 20:43:40 2017 user.emerg syslog: Starting kcptun...
Mon Aug 28 20:43:41 2017 user.notice kcptun: Client started.
Mon Aug 28 20:43:41 2017 daemon.info procd: - init complete -
Mon Aug 28 20:43:41 2017 kern.info kernel: [   37.030000] br-lan: port 2(wlan1) entered forwarding state
Mon Aug 28 20:43:42 2017 daemon.info dnsmasq[1662]: exiting on receipt of SIGTERM
Mon Aug 28 20:43:42 2017 daemon.info dnsmasq[1765]: started, version 2.73 cachesize 150
Mon Aug 28 20:43:42 2017 daemon.info dnsmasq[1765]: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP no-DHCPv6 no-Lua TFTP no-conntrack no-ipset no-auth no-DNSSEC loop-detect inotify
Mon Aug 28 20:43:42 2017 daemon.info dnsmasq[1765]: DNS service limited to local subnets
Mon Aug 28 20:43:42 2017 daemon.info dnsmasq-dhcp[1765]: DHCP, IP range 10.0.0.100 -- 10.0.0.249, lease time 12h
Mon Aug 28 20:43:42 2017 daemon.info dnsmasq[1765]: using nameserver 127.0.0.1#5354
Mon Aug 28 20:43:42 2017 daemon.info dnsmasq[1765]: read /etc/hosts - 1 addresses
Mon Aug 28 20:43:42 2017 daemon.info dnsmasq[1765]: read /tmp/hosts/dhcp - 1 addresses
Mon Aug 28 20:43:42 2017 daemon.info dnsmasq-dhcp[1765]: read /etc/ethers - 0 addresses
Mon Aug 28 20:43:42 2017 kern.info kernel: [   37.370000] br-lan: port 3(wlan0) entered forwarding state
Mon Aug 28 20:43:42 2017 kern.info kernel: [   37.370000] br-lan: port 3(wlan0) entered forwarding state
Mon Aug 28 20:43:42 2017 kern.info kernel: [   37.380000] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
Mon Aug 28 20:43:42 2017 daemon.notice netifd: radio1 (1235): wlan0: interface state HT_SCAN->ENABLED
Mon Aug 28 20:43:42 2017 daemon.notice netifd: radio1 (1235): wlan0: AP-ENABLED 
Mon Aug 28 20:43:42 2017 user.notice firewall: Reloading firewall due to ifup of wan (eth0)
Mon Aug 28 20:43:42 2017 daemon.notice netifd: Network device 'wlan0' link is up
Mon Aug 28 20:43:44 2017 kern.info kernel: [   39.370000] br-lan: port 3(wlan0) entered forwarding state
Mon Aug 28 20:43:59 2017 daemon.info hostapd: wlan1: STA 68:9c:70:85:38:c8 IEEE 802.11: authenticated
Mon Aug 28 20:43:59 2017 daemon.info hostapd: wlan1: STA 68:9c:70:85:38:c8 IEEE 802.11: associated (aid 1)
Mon Aug 28 20:43:59 2017 daemon.info hostapd: wlan1: STA 68:9c:70:85:38:c8 WPA: pairwise key handshake completed (RSN)
Mon Aug 28 20:43:59 2017 daemon.info dnsmasq-dhcp[1765]: DHCPREQUEST(br-lan) 10.0.0.206 68:9c:70:85:38:c8 
Mon Aug 28 20:43:59 2017 daemon.info dnsmasq-dhcp[1765]: DHCPACK(br-lan) 10.0.0.206 68:9c:70:85:38:c8 Anne-teki-iPad
Mon Aug 28 20:46:42 2017 daemon.info hostapd: wlan1: STA e4:f8:9c:86:3d:64 IEEE 802.11: authenticated
Mon Aug 28 20:46:42 2017 daemon.info hostapd: wlan1: STA e4:f8:9c:86:3d:64 IEEE 802.11: associated (aid 2)
Mon Aug 28 20:46:42 2017 daemon.info hostapd: wlan1: STA e4:f8:9c:86:3d:64 WPA: pairwise key handshake completed (RSN)
Mon Aug 28 20:46:42 2017 daemon.info dnsmasq-dhcp[1765]: DHCPREQUEST(br-lan) 10.0.0.246 e4:f8:9c:86:3d:64 
Mon Aug 28 20:46:42 2017 daemon.info dnsmasq-dhcp[1765]: DHCPACK(br-lan) 10.0.0.246 e4:f8:9c:86:3d:64 2011-20150923KN
Mon Aug 28 20:46:42 2017 daemon.warn odhcpd[932]: DHCPV6 SOLICIT IA_NA from 000100011d9417a1f0761ce59caa on br-lan: ok fdee:1950:41e7::b45/128 
Mon Aug 28 20:46:43 2017 daemon.info dnsmasq[1765]: read /etc/hosts - 1 addresses
Mon Aug 28 20:46:43 2017 daemon.info dnsmasq[1765]: read /tmp/hosts/odhcpd - 0 addresses
Mon Aug 28 20:46:43 2017 daemon.info dnsmasq[1765]: read /tmp/hosts/dhcp - 1 addresses
Mon Aug 28 20:46:43 2017 daemon.info dnsmasq-dhcp[1765]: read /etc/ethers - 0 addresses
Mon Aug 28 20:46:43 2017 daemon.warn odhcpd[932]: DHCPV6 SOLICIT IA_NA from 000100011d9417a1f0761ce59caa on br-lan: ok fdee:1950:41e7::b45/128 
Mon Aug 28 20:46:43 2017 daemon.info hostapd: wlan1: STA 5c:a8:6a:70:1f:be IEEE 802.11: authenticated
Mon Aug 28 20:46:43 2017 daemon.info hostapd: wlan1: STA 5c:a8:6a:70:1f:be IEEE 802.11: associated (aid 3)
Mon Aug 28 20:46:43 2017 daemon.info hostapd: wlan1: STA 5c:a8:6a:70:1f:be WPA: pairwise key handshake completed (RSN)
Mon Aug 28 20:46:43 2017 daemon.info dnsmasq-dhcp[1765]: DHCPREQUEST(br-lan) 10.0.0.228 5c:a8:6a:70:1f:be 
Mon Aug 28 20:46:43 2017 daemon.info dnsmasq-dhcp[1765]: DHCPACK(br-lan) 10.0.0.228 5c:a8:6a:70:1f:be HUAWEI_P9
Mon Aug 28 20:46:44 2017 daemon.warn odhcpd[932]: DHCPV6 REQUEST IA_NA from 000100011d9417a1f0761ce59caa on br-lan: ok fdee:1950:41e7::b45/128 
Mon Aug 28 20:46:44 2017 daemon.info dnsmasq[1765]: read /etc/hosts - 1 addresses
Mon Aug 28 20:46:44 2017 daemon.info dnsmasq[1765]: read /tmp/hosts/odhcpd - 1 addresses
Mon Aug 28 20:46:44 2017 daemon.info dnsmasq[1765]: read /tmp/hosts/dhcp - 1 addresses
Mon Aug 28 20:46:44 2017 daemon.info dnsmasq-dhcp[1765]: read /etc/ethers - 0 addresses
Mon Aug 28 20:46:48 2017 daemon.info dnsmasq-dhcp[1765]: DHCPREQUEST(br-lan) 10.0.0.228 5c:a8:6a:70:1f:be 
Mon Aug 28 20:46:48 2017 daemon.info dnsmasq-dhcp[1765]: DHCPACK(br-lan) 10.0.0.228 5c:a8:6a:70:1f:be HUAWEI_P9
Mon Aug 28 20:46:51 2017 authpriv.info dropbear[1863]: Child connection from 10.0.0.246:50812
Mon Aug 28 20:46:54 2017 daemon.info hostapd: wlan1: STA 24:00:ba:6a:ef:a3 IEEE 802.11: authenticated
Mon Aug 28 20:46:54 2017 daemon.info hostapd: wlan1: STA 24:00:ba:6a:ef:a3 IEEE 802.11: associated (aid 4)
Mon Aug 28 20:46:54 2017 daemon.info hostapd: wlan1: STA 24:00:ba:6a:ef:a3 WPA: pairwise key handshake completed (RSN)
Mon Aug 28 20:46:54 2017 daemon.info dnsmasq-dhcp[1765]: DHCPREQUEST(br-lan) 10.0.0.109 24:00:ba:6a:ef:a3 
Mon Aug 28 20:46:54 2017 daemon.info dnsmasq-dhcp[1765]: DHCPACK(br-lan) 10.0.0.109 24:00:ba:6a:ef:a3 android-62852c5c87d6a161
Mon Aug 28 20:46:54 2017 daemon.info dnsmasq-dhcp[1765]: DHCPREQUEST(br-lan) 10.0.0.109 24:00:ba:6a:ef:a3 
Mon Aug 28 20:46:54 2017 daemon.info dnsmasq-dhcp[1765]: DHCPACK(br-lan) 10.0.0.109 24:00:ba:6a:ef:a3 android-62852c5c87d6a161
Mon Aug 28 20:46:57 2017 authpriv.notice dropbear[1863]: Password auth succeeded for 'root' from 10.0.0.246:50812

**Comment by aa65535** [comment]
```
Mon Aug 28 20:43:30 2017 kern.info ss-redir[1098]: tcp port reuse enabled
Mon Aug 28 20:43:30 2017 kern.info ss-redir[1098]: UDP relay enabled
Mon Aug 28 20:43:30 2017 kern.err ss-redir[1098]: [udp] getaddrinfo: ai_family not supported
Mon Aug 28 20:43:30 2017 kern.err ss-redir[1098]: [udp] bind() error
Mon Aug 28 20:43:30 2017 kern.info ss-redir[1105]: initializing ciphers... chacha20-ietf-poly1305
Mon Aug 28 20:43:30 2017 kern.info ss-redir[1105]: tcp port reuse enabled
Mon Aug 28 20:43:30 2017 kern.info ss-redir[1105]: UDP relay enabled
Mon Aug 28 20:43:30 2017 kern.err ss-redir[1105]: [udp] getaddrinfo: ai_family not supported
Mon Aug 28 20:43:30 2017 kern.err ss-redir[1105]: [udp] bind() error
```
到 https://github.com/shadowsocks/shadowsocks-libev/issues 提 issue
