### ISSUE TITLE
启动脚本和配置文件可以放在 shadowsocks-libev 软件包里面么

### ISSUE THREAD

**Issue by lvii** [shadowsocks/luci-app-shadowsocks#145]
Hi

最近在给 TP Link WR703N 自定义 img 因为 ROM 比较小，没有安装 LuCI

安装好 `shadowsocks-libev` 发现里面只有 bin 文件，没有相关的 **启动脚本** 和 **配置文件**

请问能像 ChinaDNS，dns-forwarder 那样将 **启动脚本**、**配置文件** 放在 `shadowsocks-libev` 软件包么

谢谢！

**Comment by aa65535** [comment]
可以修改 Makefile 实现。
