### ISSUE TITLE
关于 DNS 污染的问题

### ISSUE THREAD

**Issue by NemoAlex** [shadowsocks/luci-app-shadowsocks#147]
之前在 OpenWrt 15.05.1 安装了 luci-app-shadowsocks - 1.8.1，并没有使用 ChinaDNS（安装了，但是没有开启，DNS 使用的是运营商的 211.140.188.188）。
使用 CHNRoute 模式，很神奇的发现没有 DNS 污染的问题。翻了下文档，没有找到相关的信息。虽然没搞懂为什么，但是就一直这样用着了。直到今天，发现 DNS 被污染，所有的污染又突然回来了。
有没有人遇到跟我一样的情况？

**Comment by sadoneli** [comment]
没有

**Comment by NemoAlex** [comment]
所以这是个玄学问题吗？
