### ISSUE TITLE
为什么 ss-tunnel 转发的默认 DNS 是 `8.8.4.4`？

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/luci-app-shadowsocks#149]
为什么不是 `8.8.8.8`, 是不是因为 `8.8.4.4` 受到的干扰比较少？

**Comment by aa65535** [comment]
是，同时您可以根据自己想要修改。

**Comment by pexcn** [comment]
原来是这样。但是这是从 vps 查询并通过 ss-tunnel 返回结果的吧？跟大陆的干扰没有关系吧？@aa65535
