### ISSUE TITLE
socks5用不了

### ISSUE THREAD

**Issue by just9n** [shadowsocks/luci-app-shadowsocks#15]
shadowoscks.json里local_address改不了啊，总是自动变成 0.0.0.0

**Comment by aa65535** [comment]
为什么说 `local_address` 是 `0.0.0.0` 就用不了？

**Comment by just9n** [comment]
但是我浏览器填了127.0.0.1:1080用不了啊

**Comment by aa65535** [comment]
`127.0.0.1` 是本地地址, 你需要改成您路由器的 IP 地址, 比如 `192.168.1.1:1080`

另外, shadowoscks.json 是自动生成的, 不要去修改它.
