### ISSUE TITLE
出现重复的 ss-redir 进程

### ISSUE THREAD

**Issue by lvii** [shadowsocks/luci-app-shadowsocks#157]
`ss-redir` 不能根据 PID 文件检查进程冲突么？

不知道怎么会成出现两个进程，需要设置 `startup_delay` 参数么？

希望启动脚本可以增加 `pgrep` 检查进程是否已存在的判断逻辑。

```
# pgrep -lf ss
1074 ss-redir -c /var/etc/shadowsocks.cfg0a4a8f.json -l 1234 --mtu 1492 -f /var/run/ss-redir-cfg0a4a8f.pid
1462 ss-redir -c /var/etc/shadowsocks.cfg0a4a8f.json -l 1234 --mtu 1492 -f /var/run/ss-redir-cfg0a4a8f.pid

# cat /var/run/ss-redir-cfg0a4a8f.pid
1462
```

**Comment by pexcn** [comment]
默认会开启 `reuse_port`: https://github.com/shadowsocks/luci-app-shadowsocks/issues/152

**Comment by lvii** [comment]
@pexcn 路由器是 TP Link WR703n CPU 不是双核的

**Comment by lvii** [comment]
找到问题了：

`/etc/init.d/shadowsocks` 脚本中的 `gen_config_file()` 函数生成 `"reuse_port": true` 配置是写死的

```
gen_config_file() {
        local config_file=/var/etc/$NAME.$1.json
        cat <<-EOF >$config_file
                {
                    "server": "$(uci_get_by_name $1 server)",
                    "server_port": $(uci_get_by_name $1 server_port),
                    $(get_crypto_config $1)
                    "method": "$(uci_get_by_name $1 encrypt_method)",
                    "local_address": "0.0.0.0",$(get_plugin_config $1)
                    "timeout": $(uci_get_by_name $1 timeout 60),
                    "reuse_port": true
                }
EOF
        echo $config_file
}
```

**Comment by aa65535** [comment]
现在使用多进程不限制核心，有多个进程的话看看是不是设置了多个主服务器。

**Comment by lvii** [comment]
@aa65535  ss 启动脚本调用了 2 次，配置文件里面的 `"reuse_port": true` 配置导致出现两个进程。

**Comment by aa65535** [comment]
为什么要调用两次？

**Comment by lvii** [comment]
@aa65535 是我的问题。

- `/etc/init.d/shadowsocks enable` 开机自启动了一次
- `/etc/uci-defaults/` 初始化脚本又 **重复** start 了一次

`/etc/init.d/shadowsocks` 脚本里生成 ss 配置的函数 `"reuse_port": true` 配置是否可以别 hard code

根据 UCI 的设置 **动态** 生成 `reuse_port` 配置
