### ISSUE TITLE
不可用 - iptables-mod-tproxy 或 ip 缺失

### ISSUE THREAD

**Issue by FreeVicto** [shadowsocks/luci-app-shadowsocks#158]
iptables-mod-tproxy 1.4.21-1和ip都有的情况下UDP服务器提示题目错误，，换ip-full 3.15.0-1，还是说缺失，

用的是OpenWrt Barrier Breaker 14.07系统，luci-app-shadowsocks-without-ipset 1.8.1-1/ shadowsocks-libev 3.1.0-1

请问问题究竟出在那里？

**Comment by tacuar** [comment]
用BB老系统的话, 不要装IP FULL, 直接装IP就行了, 一定要是IP,而不是IP FULL
