### ISSUE TITLE
更新到1.3版后，显示还有没填写的

### ISSUE THREAD

**Issue by liyiecho** [shadowsocks/luci-app-shadowsocks#16]
错误如图所示

<img width="725" alt="screen shot 2016-08-24 at 3 14 39 pm" src="https://cloud.githubusercontent.com/assets/5213722/17925428/86bea7a6-6a1f-11e6-93c0-f3ca5c768d70.png">

**Comment by aa65535** [comment]
尝试安装 `iptables-mod-tproxy` 也可以解决.
