### ISSUE TITLE
shadowsocks-libev不运行

### ISSUE THREAD

**Issue by Dakai** [shadowsocks/luci-app-shadowsocks#161]
安装了openwrt-shadowsocks的3.1.0版本，/usr/bin里三个可执行文件都正常可在SSH里运行，服务器端用手机客户端测试也正常，但是无法通过Luci界面运行SS，透明代理、Socks5代理、端口转发始终是未运行状态，下面各项配置都设置好了

**Comment by tacuar** [comment]
你是不是其它的程序提前装好了libsodium.

你可以试试编译的时候不要选上libsodium,或者现在删掉libsodium, 装上这里与ss一起发布的libsodium, 然后再装SS.

**Comment by Jennal** [comment]
@tacuar 我也遇到一样的情况。需要依赖什么版本的libsodium才对？

**Comment by cokebar** [comment]
@Jennal 依赖1.0.12版本
