### ISSUE TITLE
请教：点击“访问控制”页面便签，会杀 正则表达式版 dnsmasq 进程

### ISSUE THREAD

**Issue by hzqim** [shadowsocks/luci-app-shadowsocks#162]
LEDE 17.01.04 和 luci-app-shadowsocks 最新版
dnsmasq 2.78 with regex patch 
点击“访问控制”页面便签，会杀 dnsmasq 进程，被杀之后起不来。
去掉 /etc/dnsmasq.conf 中 正则配置，故障消失。

因为这个“bug”别人几乎遇不到，所以我只是请作者请教原因，谢谢。

**Comment by tacuar** [comment]
我碰到的问题是现在只要点那个访问控制, 配置页面就会卡死一样好久不会动, 但是等个二三十秒才能进入那个访问控制.

**Comment by hzqim** [comment]
@tacuar 对，杀Dnsmasq进程的同时，页面也打不开，需要等上许久才能打开。
但我把 /etc/dnsmasq.conf 中的正则配置去掉，就一切正常。
你也修改了 Dnsmasq ？

**Comment by aa65535** [comment]
这个属于系统的问题，应该是[这里](https://github.com/shadowsocks/luci-app-shadowsocks/blob/v1.8.0/files/luci/model/cbi/shadowsocks/access-control.lua#L92)引起的。
参见 https://github.com/shadowsocks/luci-app-shadowsocks/issues/32 。
