### ISSUE TITLE
能让ss不代理hosts内的ip地址吗？

### ISSUE THREAD

**Issue by daiaji** [shadowsocks/luci-app-shadowsocks#165]
有时候还是在用hosts的

**Comment by suikatomoki** [comment]
https://github.com/shadowsocks/luci-app-shadowsocks/wiki/GfwList-Support

**Comment by daiaji** [comment]
@suikatomoki 一条一条加很难过啊
然后就是iptables也是保存在flash上？
复制一遍hosts感觉更难过了
现在flash只剩下1M的可用空间了
