### ISSUE TITLE
请问可以加入黑名单模式吗？

### ISSUE THREAD

**Issue by lxhill** [shadowsocks/luci-app-shadowsocks#168]
想要使用gfw黑名单模式，但app里好像只有白名单模式？？多谢！

**Comment by cokebar** [comment]
https://github.com/shadowsocks/luci-app-shadowsocks/wiki/GfwList-Support

**Comment by lxhill** [comment]
@cokebar 小白看着好像挺复杂的，而且每次重启都要再次运行命令，如果直接有可见的功能模块就好了，多谢！
