### ISSUE TITLE
全是尚无任何配置

### ISSUE THREAD

**Issue by simonsmh** [shadowsocks/luci-app-shadowsocks#17]
影梭 - 基本设置
运行状态
尚无任何配置

 透明代理
尚无任何配置

 SOCKS5代理
尚无任何配置

从intital升级到https://github.com/shadowsocks/luci-app-shadowsocks/commit/8c6c7802d08395fe06c9b2134d3f833fbac812d6的，自编译的
![image](https://cloud.githubusercontent.com/assets/9512067/17971007/85efd218-6b0b-11e6-9c6e-34fd8c33eba9.png)

**Comment by cokebar** [comment]
https://github.com/shadowsocks/luci-app-shadowsocks/releases/tag/v1.2.0
