### ISSUE TITLE
如何设置最佳 MTU 大小？

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/luci-app-shadowsocks#172]
我从本地用 ping 尝试测试 MTU 大小，得到的数据是 `1452`

```
C:\Users\Administrator>ping -f -l 1453 [VPS IP]

正在 Ping [VPS IP] 具有 1453 字节的数据:
需要拆分数据包但是设置 DF。
需要拆分数据包但是设置 DF。
需要拆分数据包但是设置 DF。
需要拆分数据包但是设置 DF。

C:\Users\Administrator>ping -f -l 1452 [VPS IP]

正在 Ping [VPS IP] 具有 1452 字节的数据:
来自 [VPS IP] 的回复: 字节=1452 时间=160ms TTL=51
来自 [VPS IP] 的回复: 字节=1452 时间=160ms TTL=51
来自 [VPS IP] 的回复: 字节=1452 时间=161ms TTL=51
来自 [VPS IP] 的回复: 字节=1452 时间=159ms TTL=51
```

想请教一下：
1. 最佳 MTU 是 `1452`  还是 `1452 + ICMP (8) + IP (20) = 1480` ?
2. 在 luci 界面填写的 MTU 值应该是以上这个问题获得的 MTU 值？  
还是根据：[udprelay.c#L1341](https://github.com/shadowsocks/shadowsocks-libev/blob/3ed6019e1fff87e004b55b48bfd065946919f7b2/src/udprelay.c#L1341)，还要在 ICMP 和 IP 的基础上再减去 shadowsocks 的 (- 1 - 2 - 64)？

**Comment by pexcn** [comment]
看到了[这里](https://github.com/shadowsocks/shadowsocks-libev/blob/3ed6019e1fff87e004b55b48bfd065946919f7b2/src/local.c#L1743)，所以 MTU 应该设置成 `1452 + 28` ?

**Comment by aa65535** [comment]
是的

**Comment by pexcn** [comment]
懂了，谢谢

**Comment by lixingcong** [comment]
实在搞不懂shadowVPN中的MTU设置又跟shadowsocks不一样。。

https://github.com/clowwindy/ShadowVPN/issues/77#issuecomment-71356250

**Comment by pexcn** [comment]
@lixingcong 两种协议的包头大小不一样吧...
