### ISSUE TITLE
基于IP地址的访问控制

### ISSUE THREAD

**Issue by lqzhgood** [shadowsocks/luci-app-shadowsocks#173]
更新到新版本后发现访问控制现在是基于 MAC 了~ 没有 IP 地址的了。
所有通过 PPTP 加入家里路由的内网用户 MAC 都为0:0:0:0:0:0，现在的版本就无法控制了，原来基于 IP 是可以控制 PPTP 用户的 SS 访问的。

希望把基于 IP地址 的访问控制加回来。 ：）

**Comment by aa65535** [comment]
fix  2d55704
