### ISSUE TITLE
访问控制问题

### ISSUE THREAD

**Issue by mslovecc** [shadowsocks/luci-app-shadowsocks#174]
当被忽略列表选ChinaDNS路由表的时候，大多数应用可以正常走SS流量，但是谷歌Play商店和Youtube无法连接，只有在启动全局代理才连接。有什么办法可以解决这个问题？

**Comment by shNanChen** [comment]
参照下面这个，
https://github.com/shadowsocks/shadowsocks-android/issues/1016

Google Play会尝试连接services.googleapis.cn这个域名，
这个域名会被解析到Google中国的ip（203.208.32+.x），
而这些ip并不能正常返回数据

**Comment by mslovecc** [comment]
我也按那里说的把services.googleapis.cn用hosts指向了美国ip但是play商店还是用不了，要用的话只能选择全局模式。如果用ss android选择绕过本地和中国大陆地址就不存在这个问题。

**Comment by aa65535** [comment]
在 DHCP/DNS -> DNS 转发 中添加一条
```
/services.googleapis.cn/127.0.0.1#5300
```
其中 127.0.0.1#5300 是 dns-forwarder 或者 ss-tunnel 之类的提供的 dns 解析.

**Comment by mslovecc** [comment]
添加dns转发后还是打不开play商店，Youtube就没有问题，可能play商店还涉及其它域名

**Comment by mslovecc** [comment]
问题解决了，配合Chinadns一起用，修改DHCP/DNS，和设置shadowvpn的设置一样，不过打开国内网站时感觉会慢了一点点。
