### ISSUE TITLE
新版本内网控制逻辑是否有误

### ISSUE THREAD

**Issue by pigpigabc123** [shadowsocks/luci-app-shadowsocks#176]
新版本改回基于ip地址的内网控制，但访问控制页面中若代理自身设为正常代理，则无论代理类型设为直接连接还是正常代理，无论内网主机代理规则列表中的主机是否选择正常代理还是直接连接，所有内网主机均走正常代理模式，即无法对某一台主机有效设置直接连接模式，设置了也是走代理。
只有当代理自身设为直接连接，才能实现对内网某一台主机有效设置直接连接模式。
是否控制逻辑就是这样设置的还是配置有误？
路由：lede Reboot 17.01.4 版本

**Comment by aa65535** [comment]
逻辑不会是你描述的这样，我也没有复现你描述的问题。
提交下面四条命令的打印结果我分析一下：
```
iptables-save -t nat
ipset list ss_spec_src_ac
ipset list ss_spec_src_bp
ipset list ss_spec_src_fw
```

**Comment by pigpigabc123** [comment]
@aa65535 
找到原因了，ss与koolproxy有冲突，关闭koolproxy恢复正常，要想koolproxy与ss兼容真是头疼。
root@AC1900:~# iptables-save -t nat
# Generated by iptables-save v1.4.21 on Sun Jan  7 21:34:00 2018
*nat
:PREROUTING ACCEPT [47:6684]
:INPUT ACCEPT [41:2046]
:OUTPUT ACCEPT [20:1244]
:POSTROUTING ACCEPT [29:1750]
:KOOLPROXY - [0:0]
:KOOLPROXY_HTTP - [0:0]
:KOOLPROXY_HTTPS - [0:0]
:SS_SPEC_LAN_AC - [0:0]
:SS_SPEC_LAN_DG - [0:0]
:SS_SPEC_WAN_AC - [0:0]
:SS_SPEC_WAN_DG - [0:0]
:SS_SPEC_WAN_FW - [0:0]
:postrouting_lan_rule - [0:0]
:postrouting_rule - [0:0]
:postrouting_wan_rule - [0:0]
:prerouting_lan_rule - [0:0]
:prerouting_rule - [0:0]
:prerouting_wan_rule - [0:0]
:zone_lan_postrouting - [0:0]
:zone_lan_prerouting - [0:0]
:zone_wan_postrouting - [0:0]
:zone_wan_prerouting - [0:0]
-A PREROUTING -p tcp -j SS_SPEC_LAN_DG
-A PREROUTING -m comment --comment "!fw3: user chain for prerouting" -j prerouting_rule
-A PREROUTING -p tcp -j KOOLPROXY
-A PREROUTING -i br-lan -m comment --comment "!fw3" -j zone_lan_prerouting
-A PREROUTING -i pppoe-wan -m comment --comment "!fw3" -j zone_wan_prerouting
-A PREROUTING -i eth1 -m comment --comment "!fw3" -j zone_wan_prerouting
-A OUTPUT -p tcp -j SS_SPEC_WAN_DG
-A POSTROUTING -m comment --comment "!fw3: user chain for postrouting" -j postrouting_rule
-A POSTROUTING -o br-lan -m comment --comment "!fw3" -j zone_lan_postrouting
-A POSTROUTING -o pppoe-wan -m comment --comment "!fw3" -j zone_wan_postrouting
-A POSTROUTING -o eth1 -m comment --comment "!fw3" -j zone_wan_postrouting
-A KOOLPROXY -d 0.0.0.0/8 -j RETURN
-A KOOLPROXY -d 10.0.0.0/8 -j RETURN
-A KOOLPROXY -d 100.64.0.0/10 -j RETURN
-A KOOLPROXY -d 127.0.0.0/8 -j RETURN
-A KOOLPROXY -d 169.254.0.0/16 -j RETURN
-A KOOLPROXY -d 172.16.0.0/12 -j RETURN
-A KOOLPROXY -d 192.168.0.0/16 -j RETURN
-A KOOLPROXY -d 224.0.0.0/4 -j RETURN
-A KOOLPROXY -d 240.0.0.0/4 -j RETURN
-A KOOLPROXY -p tcp -j KOOLPROXY_HTTPS
-A KOOLPROXY_HTTP -p tcp -m multiport --dports 80 -j REDIRECT --to-ports 3000
-A KOOLPROXY_HTTPS -p tcp -m multiport --dports 80,443 -j REDIRECT --to-ports 3000
-A SS_SPEC_LAN_AC -m set --match-set ss_spec_src_bp src -j RETURN
-A SS_SPEC_LAN_AC -m set --match-set ss_spec_src_fw src -j SS_SPEC_WAN_FW
-A SS_SPEC_LAN_AC -m set --match-set ss_spec_src_ac src -j SS_SPEC_WAN_AC
-A SS_SPEC_LAN_AC -j RETURN
-A SS_SPEC_LAN_DG -m set --match-set ss_spec_dst_sp dst -j RETURN
-A SS_SPEC_LAN_DG -p tcp -m multiport --dports 53,80,443 -j SS_SPEC_LAN_AC
-A SS_SPEC_WAN_AC -m set --match-set ss_spec_dst_fw dst -j SS_SPEC_WAN_FW
-A SS_SPEC_WAN_AC -m set --match-set ss_spec_dst_bp dst -j RETURN
-A SS_SPEC_WAN_AC -j SS_SPEC_WAN_FW
-A SS_SPEC_WAN_DG -m set --match-set ss_spec_dst_sp dst -j RETURN
-A SS_SPEC_WAN_DG -p tcp -m multiport --dports 53,80,443 -j SS_SPEC_WAN_AC
-A SS_SPEC_WAN_FW -p tcp -j REDIRECT --to-ports 1080
-A zone_lan_postrouting -m comment --comment "!fw3: user chain for postrouting" -j postrouting_lan_rule
-A zone_lan_prerouting -m comment --comment "!fw3: user chain for prerouting" -j prerouting_lan_rule
-A zone_wan_postrouting -m comment --comment "!fw3: user chain for postrouting" -j postrouting_wan_rule
-A zone_wan_postrouting -m comment --comment "!fw3" -j MASQUERADE
-A zone_wan_prerouting -m comment --comment "!fw3: user chain for prerouting" -j prerouting_wan_rule
COMMIT
# Completed on Sun Jan  7 21:34:00 2018
root@AC1900:~# ipset list ss_spec_src_ac
Name: ss_spec_src_ac
Type: hash:ip
Revision: 4
Header: family inet hashsize 64 maxelem 65536
Size in memory: 88
References: 2
Members:
root@AC1900~# ipset list ss_spec_src_bp
Name: ss_spec_src_bp
Type: hash:ip
Revision: 4
Header: family inet hashsize 64 maxelem 65536
Size in memory: 128
References: 2
Members:
192.168.31.125
root@AC1900:~# ipset list ss_spec_src_fw
Name: ss_spec_src_fw
Type: hash:ip
Revision: 4
Header: family inet hashsize 64 maxelem 65536
Size in memory: 88
References: 2
Members:
