### ISSUE TITLE
为什么速度很缓慢？

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/luci-app-shadowsocks#177]
用 openwrt 路由器的版本，速度最高到 1MB/s 而 Windows 版可以达到 4MB/s, 线路应该是没有问题的，看了一下，它在路由器上的 CPU 占用也不高，才 25% 左右

**Comment by pexcn** [comment]
除了 ss-redir, ss-local 也是这样的速度

**Comment by aa65535** [comment]
应该是路由器性能的问题。

**Comment by pexcn** [comment]
好吧，以后换个 x86 或者 arm 的软路由折腾下
