### ISSUE TITLE
经常会出现“保存&应用”后出现三个服务都“未运行”的情况，再点一次才会好

### ISSUE THREAD

**Issue by DragonCat1** [shadowsocks/luci-app-shadowsocks#179]
最近几个版本在我机子上都会有这个问题，忘了是从哪个版本开始的了。

**Comment by aa65535** [comment]
因为你更新了 `luci-base` ， 配置文件 `/etc/config/ucitrack` 被覆盖了，参见 https://github.com/openwrt/luci/pull/1235 。
你需要手动添加下面的 section 或者重新安装一遍 luci-app-shadowsocks 

```
config shadowsocks
	option init 'shadowsocks'
```

**Comment by DragonCat1** [comment]
接上
ucitrack 没有配置项不能正常使用，不能正常开关了，但重装不能解决

**Comment by Batur24** [comment]
最新版本，ucitrack有这个配置项
```
config shadowsocks
	option init 'shadowsocks'
```
但是三个服务一直是“未运行”

**Comment by Batur24** [comment]
重新输入一遍参数，又okay了
sorry
