### ISSUE TITLE
请教ss-redir和ss-local的选择

### ISSUE THREAD

**Issue by sijidou** [shadowsocks/luci-app-shadowsocks#18]
如题，在一台单核路由器的情况下，二者该如何选择呢？我测试了，发现ss-local反应更快些，但是不太稳定。
而两者单独开启都可以正常代理，那么，我是该单独选择一个呢，还是两个都开启，都开启的话优先权是怎么样的？
另外，ss-local开启fastopen的话，是如下那个样子么：
config socks5_proxy
        option local_port '1080'
        option fast_open '1'
        option server 'xxxxxxxf'

**Comment by aa65535** [comment]
ss-redir 和 ss-local 属于不同的代理类型, 同时开启并不冲突.
透明代理可以使当前网关下的所有设备自动使用代理, SOCKS5代理需要设置手动去设置使用.
根据自己的使用场景去选择使用.

当前版本不支持开启 TFO , 如果支持的话也是在「服务器管理」里面添加相应的选项.
