### ISSUE TITLE
直接密钥怎么用

### ISSUE THREAD

**Issue by xingezhang** [shadowsocks/luci-app-shadowsocks#182]
更新1.90版本后，有一个直接密钥，不懂什么意思，该如何使用？

**Comment by bazingaterry** [comment]
https://github.com/shadowsocks/shadowsocks-org/issues/35

https://github.com/shadowsocks/shadowsocks-libev/issues/1214

**Comment by xingezhang** [comment]
意思是不用password，那么conf该怎么写呢？

**Comment by bazingaterry** [comment]
```json
{
    "key": "xxx"
}
```

https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/jconf.c#L241

**Comment by xingezhang** [comment]
试了一下，manager-mode不支持，server是OK的，可是我不太懂，这个和password的区别在哪？如果是为了避免弱密码，那直接把生成的key value写在password里面不行吗？为什么要增加key参数？

**Comment by bazingaterry** [comment]
manager mode 不支持 key，但是只需要添加幾行代碼即可支持。

至於 key 和 password 的區別 https://github.com/shadowsocks/shadowsocks-org/issues/35 裡面有說明，理解起來可能需要密碼學基礎（我也不好，所以解釋不清楚）。但可以知道的是使用 key 會比 password 有更好的 security 和 performance。

**Comment by xingezhang** [comment]
@bazingaterry 非常感谢您这么耐心的讲解，谢谢！
