### ISSUE TITLE
LEDE 17.01.4 使用透明代理，其他默认配置，无法正常走代理

### ISSUE THREAD

**Issue by MitchellJo** [shadowsocks/luci-app-shadowsocks#183]
配置好服务器，访问控制为默认配置；

- 使用透明代理，浏览器直接访问google.com时，提示证书异常；

- 使用SOCKET5模式，浏览器配套使用SwitchyOmega，google.com能正常访问；

**Comment by lixingcong** [comment]
透明代理需要先解决DNS污染投毒的问题

**Comment by MitchellJo** [comment]
已经解决，需要使用依赖包 ip-full 与 iptables-mod-tproxy
