### ISSUE TITLE
希望能生成更加小的路由表

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/luci-app-shadowsocks#186]
现在根据 [ChinaDNS#about-chnroute](https://github.com/shadowsocks/ChinaDNS#about-chnroute) 这种方式生成的路由表有 8 千多行，而这种方式更加精简：[ipset-lists/tools/gen-china-routes.sh](https://github.com/rssnsj/network-feeds/blob/master/ipset-lists/tools/gen-china-routes.sh#L13) 只有 5 千多行。

因为有些内容：
```
203.17.248.0/24
203.17.249.0/24
```
可以用以下一行代替，范围也覆盖了
```
203.17.248.0/23
```

### 参考
- https://github.com/rssnsj/network-feeds/issues/33
- https://github.com/rssnsj/network-feeds/blob/master/ipset-lists/tools

**Comment by lixingcong** [comment]
使用cidrmerge

**Comment by pexcn** [comment]
好的，我尝试一下

**Comment by LGA1150** [comment]
`opkg install aggregate`
