### ISSUE TITLE
关于SS UI的一点建议

### ISSUE THREAD

**Issue by zglzone** [shadowsocks/luci-app-shadowsocks#19]
目前SS UI有一点不人性化的地方就是当添加了多条线路添加繁琐会使页面变长，就目前而言很多SS供应商的提供的多条线路唯一不同的就是服务器，那么批量添加能不能做成服务器填写多个其他认证信息只填写一遍？

**Comment by cokebar** [comment]
目前可以自己去修改/etc/config/shadowsocks, 复制config servers字段 修改IP和remark即可
