### ISSUE TITLE
请问 Main Server 列表中的 server 会自动在当前 server 不可用的时候切换吗？

### ISSUE THREAD

**Issue by everyx** [shadowsocks/luci-app-shadowsocks#194]
我看到 main server 可以添加很多个 server，那么是否有这个功能？如果没有的话，为什么不整成只能选择一个呢？

**Comment by airhuman** [comment]
同问

**Comment by aa65535** [comment]
https://www.google.com/search?q=reuseport

Google 有答案。

http://www.blogjava.net/yongboy/archive/2015/02/12/422893.html
https://blog.csdn.net/dog250/article/details/51510823
