### ISSUE TITLE
是否考虑开发：对配置多个Main Server时，做负载均衡或优先选择延迟低的节点？

### ISSUE THREAD

**Issue by airhuman** [shadowsocks/luci-app-shadowsocks#198]
首先为luci-app-shadowsocks支持多个Main Server点个赞，能用上多核。

其次，请问，未来是否会考虑做多个Main Server的负载均衡或优先选择延迟低的节点。

因为我有多个server节点，延迟和丢包都是动态的，如果能智能选择性能好的节点就完美了，拍脑袋想下，这个需求带来的好处，可能比利用多核还实惠啊。

谢谢。

**Comment by aa65535** [comment]
https://github.com/shadowsocks/luci-app-shadowsocks/issues/194
