### ISSUE TITLE
Proxy IPv6

### ISSUE THREAD

**Issue by WordlessEcho** [shadowsocks/luci-app-shadowsocks#202]
Is it anyway to config Shadowsocks openwrt proxy IPv6 in IPv4-only network? (4to6 proxy)

**Comment by TienYow** [comment]
need server network support

**Comment by WordlessEcho** [comment]
I mean that set up Shadowsocks as a 4to6 proxy.

**Comment by TienYow** [comment]
> I mean that set up Shadowsocks as a 4to6 proxy.

i pulled a new requests , if merged I'll develop in the next requests.

**Comment by WordlessEcho** [comment]
Nice! Thanks for you.

**Comment by WordlessEcho** [comment]
Duplicate #213
