### ISSUE TITLE
结合gfwlist2dnsmasq使用是怎么一回事呢

### ISSUE THREAD

**Issue by lupohan44** [shadowsocks/luci-app-shadowsocks#207]
iptables -t nat -I SS_SPEC_WAN_AC 1 -m set --match-set gfwlist dst -j SS_SPEC_WAN_FW
这一行gfwlist是用gfwlist2dnsmasq生成的文件叫gfwlist吗

**Comment by TienYow** [comment]
gfwlist 这是 ipset 列表，要结合 dnsmasq-full 和端口转发 使用
