### ISSUE TITLE
能否额外忽略指定域名走代理？

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/luci-app-shadowsocks#209]
我的 OpenWRT 的 shadowsocks 设置了代理自身。
我在使用 he.net 的 ddns 服务，而它解析出来的 ip 不在 chnroute.txt 的范围以内，所以走了代理，我更新 ddns 的 ip 需要把 he.net 的 `dyn.dns.he.net` dig 出来的 ip 都添加到忽略列表里面，才能更新到正确的 ip, 但是怕 `dyn.dns.he.net` 的 ip 有变动，想问下能不能忽略指定域名走代理？

**Comment by lixingcong** [comment]
配合dnsmasq-full+ipset，添加到ss-redir的直连防火墙规则里面

**Comment by pexcn** [comment]
指的是类似 https://github.com/shadowsocks/luci-app-shadowsocks/wiki/GfwList-Support 这样的做法？

**Comment by TienYow** [comment]
我 pull 了一个但没有合并，可以看下 Pull requests

**Comment by pexcn** [comment]
好的。
我看了下 he.net 的[文档](https://dns.he.net/docs.html)，原来它提供了 `myip` 参数，现在直接从网络接口获取，走不走代理都无所谓了...
