### ISSUE TITLE
是否可以重新开放填写域名的支持？

### ISSUE THREAD

**Issue by MeIsReallyBa** [shadowsocks/luci-app-shadowsocks#210]
我是教育网用户，教育网v6开机无需认证即可有网，但需要连接的v6 server是动态ip，对方已经做了ddns，可惜你的版本最新版本删除了填写域名的支持

**Comment by aa65535** [comment]
https://github.com/shadowsocks/luci-app-shadowsocks/wiki/Auto-Update-Servers-IP

**Comment by MeIsReallyBa** [comment]
> https://github.com/shadowsocks/luci-app-shadowsocks/wiki/Auto-Update-Servers-IP

非常感谢你，我已经成功解决了动态ip的问题。另外在国内作为纯代理用，加密似乎可以省略。但官方的libev并不支持不加密的选项。我在github上https://github.com/SPYFF/shadowsocks-libev-nocrypto/releases看到了类似的项目，可否考虑在你的libev中加入这项功能？

**Comment by MeIsReallyBa** [comment]
成功解决，谢谢

**Comment by singular78** [comment]
如果server的ip发生变化，脚本中是否应该补充一句，将新的ip加入Bypassed IP？
