### ISSUE TITLE
可否加入none加密的功能

### ISSUE THREAD

**Issue by MeIsReallyBa** [shadowsocks/luci-app-shadowsocks#211]
server与client均在国内做纯代理使用，加密似乎不是一个必要的选项。尤其是路由器的性能对加密实在力不从心。在github上已经看到了类似的项目：https://github.com/SPYFF/shadowsocks-libev-nocrypto/releases 。可否考虑在你的libev内加入呢？

**Comment by TienYow** [comment]
安全才是 ss 的精髓，可以考了用性能消耗低点的加密方式，比如 CHACHA20-IETF-POLY1305 或 RC4-MD5

**Comment by wonpn** [comment]
> server与client均在国内做纯代理使用，加密似乎不是一个必要的选项。尤其是路由器的性能对加密实在力不从心。在github上已经看到了类似的项目：https://github.com/SPYFF/shadowsocks-libev-nocrypto/releases 。可否考虑在你的libev内加入呢？

国内纯代理可以用“SOCKS5代理”，shadowsocks-openwrt带这个功能，openwrt ddns出去就行了
