### ISSUE TITLE
能帮我看下为什么启用ss_redir.hi代理没用吗

### ISSUE THREAD

**Issue by xianshanlai** [shadowsocks/luci-app-shadowsocks#214]
你好，我的openwrt升级为18.06.1后，直接从界面安装了下面的软件包：
luci-app-shadowsocks-libev git-18.320.63580-3787301-1
shadowsocks-libev-config 3.1.3-2
shadowsocks-libev-ss-local 3.1.3-2
shadowsocks-libev-ss-redir 3.1.3-2
shadowsocks-libev-ss-rules 3.1.3-2
shadowsocks-libev-ss-tunnel 3.1.3-2
一开始使用ss_local代理可以正常访问google，但是启用透明代理不行。
本人基本小白，启用透明代理是按网上搜的配置方法：先启用ss_redir.hi，并在Redir Rules里把Disabled勾去掉，然后在Destination Settings选项卡里把Dst default设置为forward后保存应用。
还能帮我分析下什么原因啊，先谢谢了啊。。
我tracert 8.8.8.8，发现请求都没有到我的ss服务器上去

**Comment by lixingcong** [comment]
dns污染

**Comment by xianshanlai** [comment]
> 
> 
> dns污染

那该怎么弄啊？要先把chinaDNS装了吗

**Comment by lixingcong** [comment]
[污染](https://github.com/shadowsocks/luci-app-shadowsocks/issues/183)
