### ISSUE TITLE
无法禁用 redir rules

### ISSUE THREAD

**Issue by balthild** [shadowsocks/luci-app-shadowsocks#219]
## 复现步骤

1. 首先配置好透明代理，此时 Local Instances 处对应 ss_redir 实例的 `Running` 是 `yes`；
2. 查询 IP 确认路由器可以转发请求到 SS 服务器；
3. 在 Redir Rules 处勾选 `Disabled` 复选框，保存并应用；
4. 回到 Local Instances 处，发现实例的 `Running` 仍然是 `yes`；
5. 查询 IP 发现路由器仍在转发请求到 SS 服务器；
6. 编辑实例，将其禁用后，路由器才停止转发请求。

## 预期行为

禁用 Redir Rules 后，路由器就停止转发请求。

## 版本
- OpenWrt 18.06.2 r7676-cddd7b4c77
- luci-app-shadowsocks-libev git-19.034.35162-a0ae6c9-1
- shadowsocks-libev-* 3.1.3-2

**Comment by aa65535** [comment]
你的描述跟界面对不上，可以提供截图吗？

**Comment by balthild** [comment]
Local Instances 界面：
![image](https://user-images.githubusercontent.com/2662758/52269049-0e0c1d00-2978-11e9-8cf4-d119e4491c2f.png)

Redir Rules 界面（描述中 Disable 打成了 Disabled）：
![image](https://user-images.githubusercontent.com/2662758/52269017-f46ad580-2977-11e9-9834-f00b228ab720.png)

**Comment by pexcn** [comment]
截图的好像是这里的吧？ https://github.com/openwrt/luci/tree/master/applications/luci-app-shadowsocks-libev

**Comment by balthild** [comment]
的确是。抱歉，之前不知道原来有两个同类软件包……
