### ISSUE TITLE
新功能建议

### ISSUE THREAD

**Issue by tyadan** [shadowsocks/luci-app-shadowsocks#22]
目前在mac上使用surge，有一个功能比较有用，建议在此项目中可以考虑。
在用户配置服务器时，如果配置了多个服务器，可以提供一个自动测速选择的功能，大概的实现思路就是每隔10分钟左右，使用用户配置的各个线路，去请求一个文件（例如 http://www.gstatic.com/generate_204 ），然后测算下载时间，然后帮用户自动选择下载时间耗时最少的服务器，这样既方便用户，也同时实现了单服务器故障时，有能力自动切换到可用服务器的能力（我目前在帮好几个同事家里弄了自动翻墙，偶尔当某个服务器故障后，我超级头痛需要一个个帮他们去修改）

**Comment by madeye** [comment]
No plan for this.

**Comment by aa65535** [comment]
No plan for this.
