### ISSUE TITLE
Error when saving Redir rules under Luci

### ISSUE THREAD

**Issue by jackcctse** [shadowsocks/luci-app-shadowsocks#220]
openwrt master SNAPSHOT r9293-e3311cb138
click "Save" under Luci -> Services -> Shadowsocks-libev -> Redir rules will cause errors. any hints?

`Failed to execute cbi dispatcher target for entry '/admin/services/shadowsocks-libev/rules'.
The called action terminated with an exception:
/usr/lib/lua/luci/cbi.lua:165: Datatype error, bad token "cidr"
stack traceback:
        [C]: in function 'error'
        /usr/lib/lua/luci/cbi.lua:165: in function 'compile_datatype'
        /usr/lib/lua/luci/cbi.lua:177: in function 'compile_datatype'
        /usr/lib/lua/luci/cbi.lua:189: in function 'verify_datatype'
        /usr/lib/lua/luci/cbi.lua:1493: in function 'validate'
        /usr/lib/lua/luci/cbi.lua:1414: in function 'parse'
        /usr/lib/lua/luci/cbi.lua:248: in function 'parse'
        /usr/lib/lua/luci/cbi.lua:1111: in function 'parse'
        /usr/lib/lua/luci/cbi.lua:248: in function 'parse'
        /usr/lib/lua/luci/cbi.lua:387: in function 'parse'
        /usr/lib/lua/luci/dispatcher.lua:881: in function </usr/lib/lua/luci/dispatcher.lua:860>
`

**Comment by aa65535** [comment]
Please report this issue to https://github.com/openwrt/luci/tree/master/applications/luci-app-shadowsocks-libev .
