### ISSUE TITLE
aarch64 在openwrt上运行速度大幅低于armbian

### ISSUE THREAD

**Issue by sijidou** [shadowsocks/luci-app-shadowsocks#225]
aarch64， 在openwrt上运行速度大幅低于armbian
在全志H5的板子上运行时，对比openwrt和armbian，执行脚本
#!/bin/bash

number=128M
method=chacha20-ietf-poly1305

ss-tunnel -k test -m $method -l 8387 -L 127.0.0.1:8388 -s 127.0.0.1 -p 8389 &
ss_tunnel_pid=$!
ss-server -k test -m $method -s 127.0.0.1 -p 8389 &
ss_server_pid=$!

iperf -s -p 8388 &
iperf_pid=$!

sleep 1

iperf -c 127.0.0.1 -p 8387 -n $number

sleep 1

kill $ss_tunnel_pid
kill $ss_server_pid
kill $iperf_pid

sleep 1
echo "Test Finished"

当系统为armbian时，速度大约是180Mbits/sec，而换到openwrt 上再次测试，就只有75 Mbits/sec左右。
我尝试编译openwrt内核时候，添加
CONFIG_CRYPTO_CHACHA20=y
CONFIG_CRYPTO_CHACHA20POLY1305=y
,速度依然没有变化。

我不知道是由于什么原因导致，我能为此做些什么？

**Comment by pexcn** [comment]
恐怕是 CPU 性能不够，测试的时候顺便看看 CPU 还有百分之多少空闲？

**Comment by sijidou** [comment]
> CPU性能不够，测试的时候顺便看看CPU还有百分之多少空闲？

4核，测试的时候2个进程所以2核在跑，闲置2核。

**Comment by pexcn** [comment]
> > CPU性能不够，测试的时候顺便看看CPU还有百分之多少空闲？
> 
> 4核，测试的时候2个进程所以2核在跑，闲置2核。

开 4 个进程试试

**Comment by rampageX** [comment]
应该主要还是与 MbedTLS / Libsodium 这些加密解密库如何编译的有关系。

OpenWRT 上的库都是交叉编译出来的，一些特别针对 CPU 的优化在编译时都没有用到，比如 ASM 相关优化。

下面是我在虚拟机环境交叉编译出来的版本，与路由器上直接编译出来版本的速度区别，都是静态编译，运行环境都是 NETGEAR R6300V2：

## 虚拟机中交叉编译的：

```
[entware][netgear:/opt/etc]$ iperf_ss.sh 128M chacha20-ietf-poly1305
------------------------------------------------------------
Server listening on TCP port 8388
TCP window size: 85.3 KByte (default)
------------------------------------------------------------
 2019-03-20 17:41:46 INFO: initializing ciphers... chacha20-ietf-poly1305
 2019-03-20 17:41:46 INFO: listening at 127.0.0.1:8387
 2019-03-20 17:41:46 INFO: running from root user
 2019-03-20 17:41:46 INFO: initializing ciphers... chacha20-ietf-poly1305
 2019-03-20 17:41:46 INFO: tcp server listening at 127.0.0.1:8389
 2019-03-20 17:41:46 INFO: running from root user
------------------------------------------------------------
Client connecting to 127.0.0.1, TCP port 8387
TCP window size:  193 KByte (default)
------------------------------------------------------------
[  3] local 127.0.0.1 port 15927 connected with 127.0.0.1 port 8387
[  4] local 127.0.0.1 port 8388 connected with 127.0.0.1 port 17888
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-23.2 sec   128 MBytes  46.3 Mbits/sec
[ ID] Interval       Transfer     Bandwidth
[  4]  0.0-23.7 sec   128 MBytes  45.4 Mbits/sec
Test Finished
```

## 路由器上用 Tomatoware 源生编译的：

```
[entware][netgear:/opt/etc]$ iperf_ss.sh 128M chacha20-ietf-poly1305
------------------------------------------------------------
Server listening on TCP port 8388
TCP window size: 85.3 KByte (default)
------------------------------------------------------------
 2019-03-20 17:42:53 INFO: initializing ciphers... chacha20-ietf-poly1305
 2019-03-20 17:42:53 INFO: listening at 127.0.0.1:8387
 2019-03-20 17:42:53 INFO: initializing ciphers... chacha20-ietf-poly1305
 2019-03-20 17:42:53 INFO: running from root user
 2019-03-20 17:42:53 INFO: tcp server listening at 127.0.0.1:8389
 2019-03-20 17:42:53 INFO: running from root user
------------------------------------------------------------
Client connecting to 127.0.0.1, TCP port 8387
TCP window size:  193 KByte (default)
------------------------------------------------------------
[  3] local 127.0.0.1 port 15987 connected with 127.0.0.1 port 8387
[  4] local 127.0.0.1 port 8388 connected with 127.0.0.1 port 17948
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-16.4 sec   128 MBytes  65.7 Mbits/sec
[ ID] Interval       Transfer     Bandwidth
[  4]  0.0-16.7 sec   128 MBytes  64.2 Mbits/sec
Test Finished
```

**Comment by sijidou** [comment]
> 应该主要还是与MbedTLS / Libsodium这些加密解密库如何编译的有关系。
> 
> OpenWRT 上的库都是交叉编译出来的，一些特别针对 CPU 的优化在编译时都没有用到，比如 ASM 相关优化。
> 
> 下面是我在虚拟机环境交叉编译出来的版本，与路由器上直接编译出来版本的速度区别，都是静态编译，运行环境都是 NETGEAR R6300V2：
> 
> ## 虚拟机中交叉编译的：
> ```
> [entware][netgear:/opt/etc]$ iperf_ss.sh 128M chacha20-ietf-poly1305
> ------------------------------------------------------------
> Server listening on TCP port 8388
> TCP window size: 85.3 KByte (default)
> ------------------------------------------------------------
>  2019-03-20 17:41:46 INFO: initializing ciphers... chacha20-ietf-poly1305
>  2019-03-20 17:41:46 INFO: listening at 127.0.0.1:8387
>  2019-03-20 17:41:46 INFO: running from root user
>  2019-03-20 17:41:46 INFO: initializing ciphers... chacha20-ietf-poly1305
>  2019-03-20 17:41:46 INFO: tcp server listening at 127.0.0.1:8389
>  2019-03-20 17:41:46 INFO: running from root user
> ------------------------------------------------------------
> Client connecting to 127.0.0.1, TCP port 8387
> TCP window size:  193 KByte (default)
> ------------------------------------------------------------
> [  3] local 127.0.0.1 port 15927 connected with 127.0.0.1 port 8387
> [  4] local 127.0.0.1 port 8388 connected with 127.0.0.1 port 17888
> [ ID] Interval       Transfer     Bandwidth
> [  3]  0.0-23.2 sec   128 MBytes  46.3 Mbits/sec
> [ ID] Interval       Transfer     Bandwidth
> [  4]  0.0-23.7 sec   128 MBytes  45.4 Mbits/sec
> Test Finished
> ```
> ## 路由器上用 Tomatoware 源生编译的：
> ```
> [entware][netgear:/opt/etc]$ iperf_ss.sh 128M chacha20-ietf-poly1305
> ------------------------------------------------------------
> Server listening on TCP port 8388
> TCP window size: 85.3 KByte (default)
> ------------------------------------------------------------
>  2019-03-20 17:42:53 INFO: initializing ciphers... chacha20-ietf-poly1305
>  2019-03-20 17:42:53 INFO: listening at 127.0.0.1:8387
>  2019-03-20 17:42:53 INFO: initializing ciphers... chacha20-ietf-poly1305
>  2019-03-20 17:42:53 INFO: running from root user
>  2019-03-20 17:42:53 INFO: tcp server listening at 127.0.0.1:8389
>  2019-03-20 17:42:53 INFO: running from root user
> ------------------------------------------------------------
> Client connecting to 127.0.0.1, TCP port 8387
> TCP window size:  193 KByte (default)
> ------------------------------------------------------------
> [  3] local 127.0.0.1 port 15987 connected with 127.0.0.1 port 8387
> [  4] local 127.0.0.1 port 8388 connected with 127.0.0.1 port 17948
> [ ID] Interval       Transfer     Bandwidth
> [  3]  0.0-16.4 sec   128 MBytes  65.7 Mbits/sec
> [ ID] Interval       Transfer     Bandwidth
> [  4]  0.0-16.7 sec   128 MBytes  64.2 Mbits/sec
> Test Finished
> ```
> 解决的办法就是用 H5 的编译工具在板子运行的系统上自己编译所有 ss 相关的库（这里不清楚除了加密库其他库有没特定优化），然后静态编译 ss 给这个板子用（系统无关）。

感谢提醒，您的推测是准确的。
测试了下和H5的加密库没有直接关系，aarch64的静态编译的ss就达到了预想的速度。
