### ISSUE TITLE
请问配合v2ray-plugin插件使用，luci-app-shadowsocks 插件参数如何填写？

### ISSUE THREAD

**Issue by hzqim** [shadowsocks/luci-app-shadowsocks#226]
请有使用经验的朋友指导一下，谢谢。

**Comment by yuanwb1984** [comment]
loglevel=none

**Comment by aa65535** [comment]
参考 https://github.com/shadowsocks/v2ray-plugin 的 README

websocket 模式：
server: `server`
client: `loglevel=none`

websocket + tls 模式：
server: `server;tls;host=mydomain.me`
client: `tls;host=mydomain.me;loglevel=none`

quic 模式：
server: `server;mode=quic;host=mydomain.me`
client: `mode=quic;host=mydomain.me;loglevel=none`

注意在 LuCI 中使用必须要加 `loglevel=none`, 否则会启动失败。
