### ISSUE TITLE
不支持icmp代理导致udp协议逻辑不完整，引起ios的Facebook的App速度非常慢

### ISSUE THREAD

**Issue by q741451** [shadowsocks/luci-app-shadowsocks#228]
前提：
丢包率较高的SS服务器，路由器刷OpenWrt，搭建好SS，iPhone链接路由器上FaceBook的App

步骤：
分别测试两个环境下的FaceBook表现：
1.SS同时代理TCP和UDP
2.SS只代理TCP

结果：
1.同时代理TCP和UDP时，FaceBook非常慢，图片经常卡住刷不出来
2.只代理TCP的时候，速度正常，即使有点慢，但也不会卡住

期望：
同时代理TCP和UDP时，速度和只代理TCP一样正常

原因分析：
1.当udp不通时，facebook将全部采用tcp通讯，不会有速度的异常
2.当udp可以连通时候，facebook将会使用udp进行通讯，然而，由于网络环境不好，导致了数据包丢包，引起了ios的app的认为连接超时或者连接错误。ios连接超时后，就会关闭端口，此时服务器再发信息给iphone，iphone就会返回给服务器Destination unreachabl(Port unreachable)的icmp信令，告诉服务器udp包发送失败。服务器理论上收到这条icmp信令后，将会立即切换为备用udp链接继续通讯。然而，路由器ss不支持icmp转发，以至于服务器收不到发送失败的icmp通知，于是服务器不停的重试发送，Facebook就卡住了。

解决方案：
是不是该找个代理icmp的方案了，目前项目其他地方用着都很完美，唯独这个，强迫症用的难受啊....

抓包截图：
![QQ截图20190413033616](https://user-images.githubusercontent.com/1047371/56061933-72df5b80-5d9d-11e9-864c-1a45e0921188.png)
图上，内网路由器抓包，ios设备不停的回复icmp信令，告诉发送失败
![QQ截图20190413034039](https://user-images.githubusercontent.com/1047371/56062102-f13bfd80-5d9d-11e9-8241-c49139c90170.png)
图上，服务器抓包，服务器没有中转承载udp已断开信息的icmp信令，导致服务器不停重试

**Comment by aa65535** [comment]
可以加上这两条规则试试能不能解决
```sh
iptables -t nat -A SS_SPEC_LAN_DG -p icmp -j SS_SPEC_LAN_AC
iptables -t nat -A SS_SPEC_WAN_FW -p icmp -j REDIRECT --to-ports $port
```

**Comment by q741451** [comment]
> 可以加上这两条规则试试能不能解决
> 
> ```shell
> iptables -t nat -A SS_SPEC_LAN_DG -p icmp -j SS_SPEC_LAN_AC
> iptables -t nat -A SS_SPEC_WAN_FW -p icmp -j REDIRECT --to-ports $port
> ```

$port 是不是就是指透明代理配置的本地端口，我填写了透明代理本地端口，执行了这两条命令做了测试。结果如下：

可以执行成功，没有报错，但是执行完了后，Facebook软件还是会很卡，抓包依然后很多udp不可达的icmp信令。我测试了路由器下电脑ping www.baidu.com 和 www.facebook.com，百度显示3ms，facebook超时。路由器抓包，发现icmp包视乎并没有被劫持到走SS代理，而是被路由器走了正常NAT。

我猜，理论上ss-redir只是提供了tcp和udp端口的服务，icmp是不是协议上没有端口的概念，socks代理是不是理论上不能提供icmp包的代理的。如果这样的话，是不是指望ss提供icmp转发功能是不是没戏了。

**Comment by q741451** [comment]
我感觉用了路由器后，很多App莫名其妙很慢的现象，很可能就是UDP关闭信令传输有问题导致的。我尝试找了一下ICMP科学代理的工具，好像大家都不Care这个协议，毕竟又不是不能用，有UDP和TCP就够了。

**Comment by aa65535** [comment]
@q741451 shadowsocks-libev 应该是不支持 icmp ？
另外对于 UDP 不友好的网络，不建议代理 UDP.

**Comment by pertent** [comment]
我目前的解决方案是，在服务再开一个udp false的进程，然后分流把facebook和instagram分流到这个端口
