### ISSUE TITLE
新版 luci 下 main server 不能多次填写同一个服务器

### ISSUE THREAD

**Issue by zmz125000** [shadowsocks/luci-app-shadowsocks#234]
旧版 luci
LuCI openwrt-18.06 branch (git-19.170.32094-4d6d8bc)
![chrome_2019-08-05_16-01-06.png](https://i.loli.net/2019/08/05/Daw9Rqf2IizMNOh.png)

新版 luci 每个服务器只能选一次
LuCI Master (git-19.204.23774-bd44189)
![chrome_2019-08-05_16-06-35.png](https://i.loli.net/2019/08/05/l9HcQjiVoCgMnkh.png)

**Comment by aa65535** [comment]
这是新的 luci 对 `DynamicList` 的支持出了问题，你可以看看 `/cgi-bin/luci/admin/network/dhcp` 页面里“DNS 转发”部分能不能新增。

**Comment by zmz125000** [comment]
不能

**Comment by nasbdh9** [comment]
手动输名字就可以...

**Comment by nasbdh9** [comment]
在Luci里面你想实现同样操作的话

![批注 2019-09-12 112503.png](https://i.loli.net/2019/09/12/1NFjQELaDfTGXcg.png)
![批注 2019-09-12 112516.png](https://i.loli.net/2019/09/12/JTigXMCwP94bsYQ.png)
