### ISSUE TITLE
能够支持标准的socks5服务器吗? 而不是ss

### ISSUE THREAD

**Issue by f4nff** [shadowsocks/luci-app-shadowsocks#237]
![image](https://user-images.githubusercontent.com/19538878/63934406-d983be00-ca8d-11e9-9f7f-876b7b5cc5f2.png)

添加服务器这里,可以添加标准的socks5服务器吗,并且可以支持 socks5  udp over tcp 

ss是加密协议,路由器性能十分有限,如果跑加密解密,性能太差了,我想连接内网其他socks5服务器,这样我可用其他破旧电脑单独开启一个socks5 服务,路由器只跑socks5 不跑加密解密,这样性能大大提升.

**Comment by Jeconxis** [comment]
https://github.com/xsm1997/KumaSocks

**Comment by chan17** [comment]
我是用 Redsocks2  再把国外ip 转到自己局域网里的树莓派上了
我也想要socks5
