### ISSUE TITLE
host address in server log?

### ISSUE THREAD

**Issue by DreamSeason** [shadowsocks/luci-app-shadowsocks#24]
I could see two addresses in server log. One is the host address whose request is sent with the SS_QT5 client. The other is the network address(i.e. containing only number) which is from the router with SS client. I'd like to know if the cause is luci-app or shadowsocks-libev. Thx.

**Comment by aa65535** [comment]
You may need to shadowsocks-libev or shadowsocks-qt to submit this issue.
