### ISSUE TITLE
程序重启小概率会失败

### ISSUE THREAD

**Issue by 0x112** [shadowsocks/luci-app-shadowsocks#240]
在luci界面修改了配置之后点击“保存并应用”之后，很小概率会显示未运行
在命令行的情况下`/etc/init.d/shadowsocks restart`之后也会小概率没启动，没有`ss-*`的进程

不知道什么原因，再次`/etc/init.d/shadowsocks restart`就正常了

**Comment by lixingcong** [comment]
同样遇到，尚未清楚什么原因。。

**Comment by shNanChen** [comment]
我也遇到过，web页面换服务器连，配置会不生效。
需要先删除`/var/etc/shadowsocks.cfgxxxxxx.json`配置文件，
再执行`/etc/init.d/shadowsocks restart`才好用。
