### ISSUE TITLE
openwrt添加的自定义源无法更新

### ISSUE THREAD

**Issue by ClareChen** [shadowsocks/luci-app-shadowsocks#242]
opkg自定义源：
`src/gz openwrt_dist http://openwrt-dist.sourceforge.net/packages/base/x86-64
src/gz openwrt_dist_luci http://openwrt-dist.sourceforge.net/packages/luci`

然后执行opkg update会报错：
`Collected errors:
opkg_download: Failed to download http://openwrt-dist.sourceforge.net/packages/base/x86-64/Packages.gz, wget returned 8.`

**Comment by BurningC4** [comment]
openwrt-dist.sourceforge.net被墙了

**Comment by ClareChen** [comment]
> openwrt-dist.sourceforge.net被墙了

不是这个原因。可以ping测试下。
另：我路由器自身可以翻墙。

**Comment by zjufrankzhang** [comment]
x86-64这里打错了，应该是x86_64

**Comment by ClareChen** [comment]
> x86-64这里打错了，应该是x86_64

确实。感谢指出来！
