### ISSUE TITLE
static link libraries 错误

### ISSUE THREAD

**Issue by Iy204** [shadowsocks/luci-app-shadowsocks#244]
我不是使用SDK编译的，而是在编译固件的时候一起加入的。
新版本无法开启static link libraries，不开启是可以成功编译的。
Openwrt 18.06分支 内核4.14.152
错误代码
`ss_server-resolv.o: In function `resolv_sock_cb':
/home/username/openwrt/openwrt/build_dir/target-mipsel_24kc_musl/shadowsocks-libev/shadowsocks-libev-3.3.3-e2765847cce57a24d845fcb969fdba6cc1420cf3/src/resolv.c:136:(.text+0x60): Unsupported jump between ISA modes; consider recompiling with interlinking enabled
ss_server-resolv.o: In function `resolv_shutdown':
/home/username/openwrt/openwrt/build_dir/target-mipsel_24kc_musl/shadowsocks-libev/shadowsocks-libev-3.3.3-e2765847cce57a24d845fcb969fdba6cc1420cf3/src/resolv.c:205:(.text+0x1008): Unsupported jump between ISA modes; consider recompiling with interlinking enabled
ss_server-resolv.o: In function `resolv_start':
/home/username/openwrt/openwrt/build_dir/target-mipsel_24kc_musl/shadowsocks-libev/shadowsocks-libev-3.3.3-e2765847cce57a24d845fcb969fdba6cc1420cf3/src/resolv.c:231:(.text+0x10e0): Unsupported jump between ISA modes; consider recompiling with interlinking enabled
collect2: error: ld returned 1 exit status
Makefile:699: recipe for target 'ss-server' failed
make[6]: *** [ss-server] Error 1
make[6]: Leaving directory '/home/username/openwrt/openwrt/build_dir/target-mipsel_24kc_musl/shadowsocks-libev/shadowsocks-libev-3.3.3-e2765847cce57a24d845fcb969fdba6cc1420cf3/src'
Makefile:478: recipe for target 'all-recursive' failed
make[5]: *** [all-recursive] Error 1
make[5]: Leaving directory '/home/username/openwrt/openwrt/build_dir/target-mipsel_24kc_musl/shadowsocks-libev/shadowsocks-libev-3.3.3-e2765847cce57a24d845fcb969fdba6cc1420cf3'
Makefile:387: recipe for target 'all' failed
make[4]: *** [all] Error 2
make[4]: Leaving directory '/home/username/openwrt/openwrt/build_dir/target-mipsel_24kc_musl/shadowsocks-libev/shadowsocks-libev-3.3.3-e2765847cce57a24d845fcb969fdba6cc1420cf3'
Makefile:129: recipe for target '/home/username/openwrt/openwrt/build_dir/target-mipsel_24kc_musl/shadowsocks-libev//shadowsocks-libev-3.3.3-e2765847cce57a24d845fcb969fdba6cc1420cf3/.built' failed
make[3]: *** [/home/username/openwrt/openwrt/build_dir/target-mipsel_24kc_musl/shadowsocks-libev//shadowsocks-libev-3.3.3-e2765847cce57a24d845fcb969fdba6cc1420cf3/.built] Error 2
make[3]: Leaving directory '/home/username/openwrt/openwrt/package/openwrt-shadowsocks-master'
time: package/openwrt-shadowsocks-master/compile#30.39#7.09#36.56
package/Makefile:111: recipe for target 'package/openwrt-shadowsocks-master/compile' failed
make[2]: *** [package/openwrt-shadowsocks-master/compile] Error 2
make[2]: Leaving directory '/home/username/openwrt/openwrt'
package/Makefile:107: recipe for target '/home/username/openwrt/openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile' failed
make[1]: *** [/home/username/openwrt/openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/username/openwrt/openwrt'
/home/username/openwrt/openwrt/include/toplevel.mk:216: recipe for target 'world' failed
make: *** [world] Error 2`

**Comment by aa65535** [comment]
Openwrt 18.x 的 SDK 不支持静态编译。
