### ISSUE TITLE
似乎不兼容openwrt-19.07

### ISSUE THREAD

**Issue by BurningC4** [shadowsocks/luci-app-shadowsocks#248]
openwrt-19.07.0已发布，我今天在编译固件时加入了luci-app-shadowsocks，刷机后不能打开services下的任何选项，换成openwrt官方源的luci-app-shadowsocks-libev则全部恢复正常

**Comment by shensven** [comment]
安装`luci-compat`后，`luci-app-shadowsocks`可以正常使用
