### ISSUE TITLE
各项服务都正常启动，还是无法访问外网，如何判断。谢谢

### ISSUE THREAD

**Issue by ztechie** [shadowsocks/luci-app-shadowsocks#25]
Sat Sep  3 11:43:51 2016 kern.info ss-redir[4706]: onetime authentication enabled
Sat Sep  3 11:43:51 2016 kern.info ss-redir[4706]: initializing ciphers... chacha20
Sat Sep  3 11:43:51 2016 kern.info ss-redir[4706]: tcp port reuse enabled
Sat Sep  3 11:43:51 2016 kern.info ss-redir[4706]: UDP relay enabled
Sat Sep  3 11:43:51 2016 kern.info ss-redir[4706]: udp port reuse enabled
Sat Sep  3 11:43:51 2016 kern.info ss-redir[4706]: listening at 0.0.0.0:1234
Sat Sep  3 11:43:54 2016 kern.info ss-local[4802]: onetime authentication enabled
Sat Sep  3 11:43:54 2016 kern.info ss-local[4802]: initializing ciphers... chacha20
Sat Sep  3 11:43:54 2016 kern.info ss-local[4802]: tcp port reuse enabled
Sat Sep  3 11:43:54 2016 kern.info ss-local[4802]: udprelay enabled
Sat Sep  3 11:43:54 2016 kern.info ss-local[4802]: udp port reuse enabled
Sat Sep  3 11:43:54 2016 kern.info ss-local[4802]: listening at 0.0.0.0:1080
Sat Sep  3 11:43:54 2016 kern.info ss-tunnel[4826]: onetime authentication enabled
Sat Sep  3 11:43:54 2016 kern.info ss-tunnel[4826]: initializing ciphers... chacha20
Sat Sep  3 11:43:54 2016 kern.info ss-tunnel[4826]: tcp port reuse enabled
Sat Sep  3 11:43:54 2016 kern.info ss-tunnel[4826]: UDP relay enabled
Sat Sep  3 11:43:54 2016 kern.info ss-tunnel[4826]: udp port reuse enabled
Sat Sep  3 11:43:54 2016 kern.info ss-tunnel[4826]: listening at 0.0.0.0:5300
Sat Sep  3 11:43:59 2016 kern.err ss-redir[4706]: server recv: Connection reset by peer
Sat Sep  3 11:44:47 2016 daemon.info dnsmasq-dhcp[3305]: DHCPREQUEST(br-lan) 192.168.100.208 ac:7b:a1:4d:0d:e6 
Sat Sep  3 11:44:47 2016 daemon.info dnsmasq-dhcp[3305]: DHCPACK(br-lan) 192.168.100.208 ac:7b:a1:4d:0d:e6 DESKTOP-52IKP8B
Sat Sep  3 11:45:20 2016 authpriv.info dropbear[4142]: Exit (root): Keepalive timeout
Sat Sep  3 11:46:04 2016 kern.info ss-redir[4921]: onetime authentication enabled
Sat Sep  3 11:46:04 2016 kern.info ss-redir[4921]: initializing ciphers... chacha20
Sat Sep  3 11:46:04 2016 kern.info ss-redir[4921]: tcp port reuse enabled
Sat Sep  3 11:46:04 2016 kern.info ss-redir[4921]: UDP relay enabled
Sat Sep  3 11:46:04 2016 kern.info ss-redir[4921]: udp port reuse enabled
Sat Sep  3 11:46:04 2016 kern.info ss-redir[4921]: listening at 0.0.0.0:1234
Sat Sep  3 11:46:07 2016 kern.info ss-local[5017]: onetime authentication enabled
Sat Sep  3 11:46:07 2016 kern.info ss-local[5017]: initializing ciphers... chacha20
Sat Sep  3 11:46:07 2016 kern.info ss-local[5017]: tcp port reuse enabled
Sat Sep  3 11:46:07 2016 kern.info ss-local[5017]: udprelay enabled
Sat Sep  3 11:46:07 2016 kern.info ss-local[5017]: udp port reuse enabled
Sat Sep  3 11:46:07 2016 kern.info ss-local[5017]: listening at 0.0.0.0:1080
Sat Sep  3 11:46:07 2016 kern.info ss-tunnel[5041]: onetime authentication enabled
Sat Sep  3 11:46:07 2016 kern.info ss-tunnel[5041]: initializing ciphers... chacha20
Sat Sep  3 11:46:07 2016 kern.info ss-tunnel[5041]: tcp port reuse enabled
Sat Sep  3 11:46:07 2016 kern.info ss-tunnel[5041]: UDP relay enabled
Sat Sep  3 11:46:07 2016 kern.info ss-tunnel[5041]: udp port reuse enabled
Sat Sep  3 11:46:07 2016 kern.info ss-tunnel[5041]: listening at 0.0.0.0:5300
Sat Sep  3 11:46:38 2016 kern.info ss-redir[5101]: onetime authentication enabled
Sat Sep  3 11:46:38 2016 kern.info ss-redir[5101]: initializing ciphers... rc4-md5
Sat Sep  3 11:46:38 2016 kern.info ss-redir[5101]: tcp port reuse enabled
Sat Sep  3 11:46:38 2016 kern.info ss-redir[5101]: UDP relay enabled
Sat Sep  3 11:46:38 2016 kern.info ss-redir[5101]: udp port reuse enabled
Sat Sep  3 11:46:38 2016 kern.info ss-redir[5101]: listening at 0.0.0.0:1234
Sat Sep  3 11:46:41 2016 kern.info ss-local[5197]: onetime authentication enabled
Sat Sep  3 11:46:41 2016 kern.info ss-local[5197]: initializing ciphers... rc4-md5
Sat Sep  3 11:46:41 2016 kern.info ss-local[5197]: tcp port reuse enabled
Sat Sep  3 11:46:41 2016 kern.info ss-local[5197]: udprelay enabled
Sat Sep  3 11:46:41 2016 kern.info ss-local[5197]: udp port reuse enabled
Sat Sep  3 11:46:41 2016 kern.info ss-local[5197]: listening at 0.0.0.0:1080
Sat Sep  3 11:46:41 2016 kern.info ss-tunnel[5221]: onetime authentication enabled
Sat Sep  3 11:46:41 2016 kern.info ss-tunnel[5221]: initializing ciphers... rc4-md5
Sat Sep  3 11:46:41 2016 kern.info ss-tunnel[5221]: tcp port reuse enabled
Sat Sep  3 11:46:41 2016 kern.info ss-tunnel[5221]: UDP relay enabled
Sat Sep  3 11:46:41 2016 kern.info ss-tunnel[5221]: udp port reuse enabled
Sat Sep  3 11:46:41 2016 kern.info ss-tunnel[5221]: listening at 0.0.0.0:5300
Sat Sep  3 11:46:55 2016 authpriv.info dropbear[4131]: Exit (root): Keepalive timeout
Sat Sep  3 11:47:03 2016 kern.info ss-redir[5311]: onetime authentication enabled
Sat Sep  3 11:47:03 2016 kern.info ss-redir[5311]: initializing ciphers... rc4-md5
Sat Sep  3 11:47:03 2016 kern.info ss-redir[5311]: tcp port reuse enabled
Sat Sep  3 11:47:03 2016 kern.info ss-redir[5311]: UDP relay enabled
Sat Sep  3 11:47:03 2016 kern.info ss-redir[5311]: udp port reuse enabled
Sat Sep  3 11:47:03 2016 kern.info ss-redir[5311]: listening at 0.0.0.0:1234
Sat Sep  3 11:47:06 2016 kern.info ss-local[5407]: onetime authentication enabled
Sat Sep  3 11:47:06 2016 kern.info ss-local[5407]: initializing ciphers... rc4-md5
Sat Sep  3 11:47:06 2016 kern.info ss-local[5407]: tcp port reuse enabled
Sat Sep  3 11:47:06 2016 kern.info ss-local[5407]: udprelay enabled
Sat Sep  3 11:47:06 2016 kern.info ss-local[5407]: udp port reuse enabled
Sat Sep  3 11:47:06 2016 kern.info ss-local[5407]: listening at 0.0.0.0:1080
Sat Sep  3 11:47:06 2016 kern.info ss-tunnel[5431]: onetime authentication enabled
Sat Sep  3 11:47:06 2016 kern.info ss-tunnel[5431]: initializing ciphers... rc4-md5
Sat Sep  3 11:47:06 2016 kern.info ss-tunnel[5431]: tcp port reuse enabled
Sat Sep  3 11:47:06 2016 kern.info ss-tunnel[5431]: UDP relay enabled
Sat Sep  3 11:47:06 2016 kern.info ss-tunnel[5431]: udp port reuse enabled
Sat Sep  3 11:47:06 2016 kern.info ss-tunnel[5431]: listening at 0.0.0.0:5300
Sat Sep  3 11:48:29 2016 authpriv.info dropbear[5535]: Child connection from 192.168.100.208:64247
Sat Sep  3 11:48:31 2016 authpriv.notice dropbear[5535]: Password auth succeeded for 'root' from 192.168.100.208:64247
Sat Sep  3 11:48:51 2016 kern.info ss-redir[5599]: onetime authentication enabled
Sat Sep  3 11:48:51 2016 kern.info ss-redir[5599]: initializing ciphers... rc4-md5
Sat Sep  3 11:48:51 2016 kern.info ss-redir[5599]: tcp port reuse enabled
Sat Sep  3 11:48:51 2016 kern.info ss-redir[5599]: UDP relay enabled
Sat Sep  3 11:48:51 2016 kern.info ss-redir[5599]: udp port reuse enabled
Sat Sep  3 11:48:51 2016 kern.info ss-redir[5599]: listening at 0.0.0.0:1234
Sat Sep  3 11:48:54 2016 kern.info ss-tunnel[5698]: onetime authentication enabled
Sat Sep  3 11:48:54 2016 kern.info ss-tunnel[5698]: initializing ciphers... rc4-md5
Sat Sep  3 11:48:54 2016 kern.info ss-tunnel[5698]: tcp port reuse enabled
Sat Sep  3 11:48:54 2016 kern.info ss-tunnel[5698]: UDP relay enabled
Sat Sep  3 11:48:54 2016 kern.info ss-tunnel[5698]: udp port reuse enabled
Sat Sep  3 11:48:54 2016 kern.info ss-tunnel[5698]: listening at 0.0.0.0:5300
Sat Sep  3 11:49:10 2016 kern.info ss-redir[5768]: onetime authentication enabled
Sat Sep  3 11:49:10 2016 kern.info ss-redir[5768]: initializing ciphers... rc4-md5
Sat Sep  3 11:49:10 2016 kern.info ss-redir[5768]: tcp port reuse enabled
Sat Sep  3 11:49:10 2016 kern.info ss-redir[5768]: UDP relay enabled
Sat Sep  3 11:49:10 2016 kern.info ss-redir[5768]: udp port reuse enabled
Sat Sep  3 11:49:10 2016 kern.info ss-redir[5768]: listening at 0.0.0.0:1234
Sat Sep  3 11:49:13 2016 kern.info ss-tunnel[5867]: onetime authentication enabled
Sat Sep  3 11:49:13 2016 kern.info ss-tunnel[5867]: initializing ciphers... rc4-md5
Sat Sep  3 11:49:13 2016 kern.info ss-tunnel[5867]: tcp port reuse enabled
Sat Sep  3 11:49:13 2016 kern.info ss-tunnel[5867]: UDP relay enabled
Sat Sep  3 11:49:13 2016 kern.info ss-tunnel[5867]: udp port reuse enabled
Sat Sep  3 11:49:13 2016 kern.info ss-tunnel[5867]: listening at 0.0.0.0:5300
Sat Sep  3 11:49:24 2016 kern.info ss-redir[5931]: initializing ciphers... rc4-md5
Sat Sep  3 11:49:24 2016 kern.info ss-redir[5931]: tcp port reuse enabled
Sat Sep  3 11:49:24 2016 kern.info ss-redir[5931]: UDP relay enabled
Sat Sep  3 11:49:24 2016 kern.info ss-redir[5931]: udp port reuse enabled
Sat Sep  3 11:49:24 2016 kern.info ss-redir[5931]: listening at 0.0.0.0:1234
Sat Sep  3 11:49:27 2016 kern.info ss-tunnel[6030]: initializing ciphers... rc4-md5
Sat Sep  3 11:49:27 2016 kern.info ss-tunnel[6030]: tcp port reuse enabled
Sat Sep  3 11:49:27 2016 kern.info ss-tunnel[6030]: UDP relay enabled
Sat Sep  3 11:49:27 2016 kern.info ss-tunnel[6030]: udp port reuse enabled
Sat Sep  3 11:49:27 2016 kern.info ss-tunnel[6030]: listening at 0.0.0.0:5300
Sat Sep  3 11:49:39 2016 kern.info ss-redir[6112]: initializing ciphers... rc4-md5
Sat Sep  3 11:49:39 2016 kern.info ss-redir[6112]: tcp port reuse enabled
Sat Sep  3 11:49:39 2016 kern.info ss-redir[6112]: UDP relay enabled
Sat Sep  3 11:49:39 2016 kern.info ss-redir[6112]: udp port reuse enabled
Sat Sep  3 11:49:39 2016 kern.info ss-redir[6112]: listening at 0.0.0.0:1234
Sat Sep  3 11:49:42 2016 kern.info ss-tunnel[6211]: initializing ciphers... rc4-md5
Sat Sep  3 11:49:42 2016 kern.info ss-tunnel[6211]: tcp port reuse enabled
Sat Sep  3 11:49:42 2016 kern.info ss-tunnel[6211]: UDP relay enabled
Sat Sep  3 11:49:42 2016 kern.info ss-tunnel[6211]: udp port reuse enabled
Sat Sep  3 11:49:42 2016 kern.info ss-tunnel[6211]: listening at 0.0.0.0:5300
Sat Sep  3 11:50:01 2016 authpriv.info dropbear[4339]: Exit (root): Keepalive timeout
Sat Sep  3 11:51:06 2016 daemon.info hostapd: wlan0: STA ac:7b:a1:4d:0d:e6 WPA: group key handshake completed (RSN)
Sat Sep  3 11:51:36 2016 daemon.err miniupnpd[1698]: addmasqueraderule() : chain MINIUPNPD-POSTROUTING not found
Sat Sep  3 11:51:36 2016 daemon.notice miniupnpd[1698]: add_redirect_rule2(): addmasqueraderule returned -1
Sat Sep  3 11:52:44 2016 kern.info ss-redir[6367]: initializing ciphers... rc4-md5
Sat Sep  3 11:52:44 2016 kern.info ss-redir[6367]: tcp port reuse enabled
Sat Sep  3 11:52:44 2016 kern.info ss-redir[6367]: UDP relay enabled
Sat Sep  3 11:52:44 2016 kern.info ss-redir[6367]: udp port reuse enabled
Sat Sep  3 11:52:44 2016 kern.info ss-redir[6367]: listening at 0.0.0.0:1234
Sat Sep  3 11:52:47 2016 kern.info ss-tunnel[6466]: initializing ciphers... rc4-md5
Sat Sep  3 11:52:47 2016 kern.info ss-tunnel[6466]: tcp port reuse enabled
Sat Sep  3 11:52:47 2016 kern.info ss-tunnel[6466]: UDP relay enabled
Sat Sep  3 11:52:47 2016 kern.info ss-tunnel[6466]: udp port reuse enabled
Sat Sep  3 11:52:47 2016 kern.info ss-tunnel[6466]: listening at 0.0.0.0:5300

**Comment by aa65535** [comment]
「外网」是指什么？
UDP服务器试试停用掉。
`iptables-save -t nat` 命令的打印结果。

**Comment by ztechie** [comment]
本地服务器设置了127.0.0.1#5300就好了，谢谢
原来问题在这里
# Generated by iptables-save v1.4.21 on Sat Sep  3 12:35:25 2016
*nat
:PREROUTING ACCEPT [353:21699]
:INPUT ACCEPT [186:6622]
:OUTPUT ACCEPT [28:2103]
:POSTROUTING ACCEPT [0:0]
:MINIUPNPD - [0:0]
:SS_SPEC_LAN_AC - [0:0]
:SS_SPEC_LAN_DG - [0:0]
:SS_SPEC_WAN_AC - [0:0]
:SS_SPEC_WAN_DG - [0:0]
:SS_SPEC_WAN_FW - [0:0]
:delegate_postrouting - [0:0]
:delegate_prerouting - [0:0]
:postrouting_lan_rule - [0:0]
:postrouting_rule - [0:0]
:postrouting_wan_rule - [0:0]
:prerouting_lan_rule - [0:0]
:prerouting_rule - [0:0]
:prerouting_wan_rule - [0:0]
:zone_lan_postrouting - [0:0]
:zone_lan_prerouting - [0:0]
:zone_wan_postrouting - [0:0]
:zone_wan_prerouting - [0:0]
-A PREROUTING -j SS_SPEC_LAN_DG
-A PREROUTING -j delegate_prerouting
-A OUTPUT -p tcp -j SS_SPEC_WAN_DG
-A POSTROUTING -j delegate_postrouting
-A MINIUPNPD -p tcp -m tcp --dport 14784 -j DNAT --to-destination 192.168.100.208:14784
-A MINIUPNPD -p udp -m udp --dport 14784 -j DNAT --to-destination 192.168.100.208:8849
-A MINIUPNPD -p tcp -m tcp --dport 5648 -j DNAT --to-destination 192.168.100.208:5648
-A MINIUPNPD -p udp -m udp --dport 5649 -j DNAT --to-destination 192.168.100.208:5648
-A SS_SPEC_LAN_AC -m set --match-set ss_spec_src_bp src -j RETURN
-A SS_SPEC_LAN_AC -m set --match-set ss_spec_src_fw src -j SS_SPEC_WAN_FW
-A SS_SPEC_LAN_AC -m set --match-set ss_spec_src_ac src -j SS_SPEC_WAN_AC
-A SS_SPEC_LAN_AC -j SS_SPEC_WAN_AC
-A SS_SPEC_LAN_DG -m set --match-set ss_spec_dst_sp dst -j RETURN
-A SS_SPEC_LAN_DG -p tcp -j SS_SPEC_LAN_AC
-A SS_SPEC_WAN_AC -m set --match-set ss_spec_dst_fw dst -j SS_SPEC_WAN_FW
-A SS_SPEC_WAN_AC -m set --match-set ss_spec_dst_bp dst -j RETURN
-A SS_SPEC_WAN_AC -j SS_SPEC_WAN_FW
-A SS_SPEC_WAN_DG -m set --match-set ss_spec_dst_sp dst -j RETURN
-A SS_SPEC_WAN_DG -p tcp -j SS_SPEC_WAN_AC
-A SS_SPEC_WAN_FW -p tcp -j REDIRECT --to-ports 1234
-A delegate_postrouting -m comment --comment "user chain for postrouting" -j postrouting_rule
-A delegate_postrouting -o br-lan -j zone_lan_postrouting
-A delegate_postrouting -o eth1 -j zone_wan_postrouting
-A delegate_prerouting -m comment --comment "user chain for prerouting" -j prerouting_rule
-A delegate_prerouting -i br-lan -j zone_lan_prerouting
-A delegate_prerouting -i eth1 -j zone_wan_prerouting
-A zone_lan_postrouting -m comment --comment "user chain for postrouting" -j postrouting_lan_rule
-A zone_lan_prerouting -m comment --comment "user chain for prerouting" -j prerouting_lan_rule
-A zone_wan_postrouting -m comment --comment "user chain for postrouting" -j postrouting_wan_rule
-A zone_wan_postrouting -j MASQUERADE
-A zone_wan_prerouting -j MINIUPNPD
-A zone_wan_prerouting -m comment --comment "user chain for prerouting" -j prerouting_wan_rule
COMMIT
# Completed on Sat Sep  3 12:35:25 2016

**Comment by ztechie** [comment]
再次非常感谢

**Comment by ztechie** [comment]
DNS污染问题 是否要搭配chinadns app？

**Comment by aa65535** [comment]
建议搭配 [ChinaDNS](https://github.com/aa65535/openwrt-chinadns) 使用。
如果觉得 UDP 不稳定可以再搭配 [DNS Forwarder](https://github.com/aa65535/openwrt-chinadns/wiki/Use-DNS-Forwarder)。

**Comment by wongsyrone** [comment]
另外无责任推荐https://github.com/chengr28/Pcap_DNSProxy

**Comment by ztechie** [comment]
谢谢楼上
