### ISSUE TITLE
luci在OpenWrt 19.07.2下有小bug

### ISSUE THREAD

**Issue by pigpigabc123** [shadowsocks/luci-app-shadowsocks#255]
wrt1900路由，双核cpu，OpenWrt 18.06下luci主服务器可设置2个，OpenWrt 19.07.2下无法设置第二个主服务器。已安装luci-compat。

**Comment by whao** [comment]
同样的问题，可能是适配没有做好吧。现在的workaround是直接在`/etc/config/shadowsocks`里面添加多个`list main_server 'id'`来实现负载均衡

**Comment by aa65535** [comment]
https://github.com/shadowsocks/luci-app-shadowsocks/issues/234
https://github.com/openwrt/luci/issues/3387

**Comment by stokito** [comment]
Please review the PR #7558
