### ISSUE TITLE
luci界面添加节点时直接引用v2ray-plugin插件节点使用异常。

### ISSUE THREAD

**Issue by bishiping** [shadowsocks/luci-app-shadowsocks#256]
①请问luci-app-shadowsocks支持在添加节点时引用v2ray-plugin插件吗？
②我试了obfs-local插件（也是您编译好的ipk）可以，至于v2ray-plugin插件，我是从 github.com/shadowsocks/v2ray-plugin 的releases里下载下来的试用于amd64的包，放到 /usr/bin目录下，重命名了，且赋予了可执行权限。
③然后在节点那里随意添加了带v2ray-plugin插件的节点，然后ss-redir那里使用这个节点无法正常使用，提示“未运行”。

**Comment by aa65535** [comment]
https://github.com/shadowsocks/luci-app-shadowsocks/issues/226

**Comment by bishiping** [comment]
> #226

好的，谢谢。
