### ISSUE TITLE
Transparant proxy UDP only (no TCP)

### ISSUE THREAD

**Issue by beanslel** [shadowsocks/luci-app-shadowsocks#263]
Currently, UDP relay with ss-redir will only be enabled if the main server is also enabled. Without the main server enabled, UDP relay is disabled even if a UDP relay server is selected. 

Is it possible to enable UDP relay only without the main server? I don't want to have any TCP redirection at all. I assume this is possible, just have to omit all the TCP iptable rules and only add the UDP rules. Can anyone point me in the direction where to change this in the code, or help me to make this change? My knowledge of iptables is a bit limited.

(I know I can do this outside of Luci in CLI directly, but would like to integrate this in my ss Luci app).

**Comment by cccRaim** [comment]
我记得ss-redir不是有-U参数吗，那个可以支持这个需求吗
