### ISSUE TITLE
使用GfwList的时候，最新版本里面没有这些规则 SS_SPEC_WAN_AC ，SS_SPEC_WAN_FW

### ISSUE THREAD

**Issue by wnarutou** [shadowsocks/luci-app-shadowsocks#264]
我使用的是OpenWrt 19.07.3，然后用的官方渠道安装luci-app-shadowsocks，开启转发规则之后，iptables中不存在SS_SPEC_WAN_FW这些域，请问要怎样修改以下命令呢？
iptables -t nat -I SS_SPEC_WAN_AC 1 -m set --match-set gfwlist dst -j SS_SPEC_WAN_FW

**Comment by aa65535** [comment]
检查你使用的包的来源。
