### ISSUE TITLE
openwrt下shadowsocks无法实现转发

### ISSUE THREAD

**Issue by pstandard** [shadowsocks/luci-app-shadowsocks#267]
各位，帮忙看一下我这个网络环境要怎么设置才能够实现Wifi路由器端口转发。
socks代理(192.168.1.102:1080) 可以正常工作，说明shadowsocks本身的安装应该没问题。把透明代理和转发都打开后，所有设备都工作正常，流量没有走转发通道。

网络环境:
设备                      IP                       开通的服务功能
电信猫：              192.168.1.1         DHCP, 负责跟外网连接，作为所有设备的网关，关闭wifi功能
网件Wifi路由器    192.168.1.102      与电信猫千兆网线相连，开通无线功能，Openwrt 19.07.4版本，安装Shadowsocks-libev 3.3.5+China DNS；
斐讯N1                  192.168.1.8        与Wifi路由器千兆网线相连，安装CoreELEC Kodi，Shadowsocks主要就是服务这台设备
手机等终端            192.168.1.*       与Wifi路由器通讯

**Comment by shNanChen** [comment]
旁路由模式，需要设置电信猫DHCP，把gateway设置为192.168.1.8，
这样无线有线客户端上网通信会经过Shadowsocks

**Comment by pstandard** [comment]
> 旁路由模式，需要设置电信猫DHCP，把gateway设置为192.168.1.8，
> 这样无线有线客户端上网通信会经过Shadowsocks

可以了，谢谢。需要把 桥接: "br-lan" 的代理类型和代理自身都选择成全局代理。

现在是openwrt上面的DNS没有办法启动，Dnsmasq 已经正确设置，但是后台却没有查询到Dnsmasq 进程，53端口也没打开。使用自身的DNS无法解决DNS污染的问题。

**Comment by shNanChen** [comment]
Dnsmasq 进程没起来就是配置文件有错误，
`dnsmasq --test` 查查配置文件
`logread`  看看有没有dnsmasq 的报错信息
