### ISSUE TITLE
端口转发使用插件后显示"未运行"

### ISSUE THREAD

**Issue by 0x112** [shadowsocks/luci-app-shadowsocks#270]
我在端口转发使用了v2ray-plugin后，界面显示端口转发未运行（不使用插件是正常的），然而进入命令行输入 /etc/init.d/shadowsocks restart 后却是正常的。这是可能luci界面的bug吗？

**Comment by aa65535** [comment]
参考一下 #226

**Comment by 0x112** [comment]
可以解决，但是想问下这是什么原理呢？
/etc/init.d/shadowsocks restart不加`loglevel=none`也是正常的

**Comment by aa65535** [comment]
luci 执行的时候，没有 stdout，所以输出日志的话会出错。
