### ISSUE TITLE
访问控制中找不到ChinaDNS

### ISSUE THREAD

**Issue by libook** [shadowsocks/luci-app-shadowsocks#271]
Model: FriendlyElec NanoPi R4S
Firmware Version: OpenWrt 19.07.5 r11257-5090152ae3 / LuCI friendlywrt-v19.07.5 branch git-20.358.36252-85ff2c9

ChinaDNS: v1.3.3-1
shadowsocks-libev: v3.3.5-1
luci-app-shadowsocks: v2.0.2-1

在ShadowSocks的访问控制中的 Bypassed IP List 中只有一个“NULL - As Global Proxy”，找不到ChinaDNS的相关选项，请问我该如何解决这个问题呢？

**Comment by aa65535** [comment]
新的版本去掉了 `chinadns_chnroute`， 手动填写即可。
