### ISSUE TITLE
请教都需要什么依赖包，好像dns forward没有起作用。

### ISSUE THREAD

**Issue by iyzgit** [shadowsocks/luci-app-shadowsocks#272]
使用的是mips-24kc的openwrt 19.07.7
想通过luci-app-shadowsocks+shadowsocks-libev+dns forward+gfwlist实现透明代理。
1.安装了luci-app-shadowsocks，shadowsocks-libev_3.3.5-1_mips_24kc.ipk，dns-forwarder, luci-app-dns-forwarder，dnsmasq-ful，ipset， iptables-mod-tproxy， libev。

2.在/etc/dnsmasq.d/下面也放入了 dnsmasq_gfwlist_ipset.conf .格式如下
#使用不受污染干扰的DNS解析该域名 可以将此IP改为自己使用的DNS服务器
server=/google.com/127.0.0.1#5353
#将解析出来的IP保存到名为gfwlist的ipset表中
ipset=/google.com/gfwlist

3.在/ect/dnsmasq.conf中添加了conf-dir=/etc/dnsmasq.d
4. 在wan口配置中设置127.0.0.1为dns
5. 在dns/dhcp中设置了转发dns为223.5.5.5
6. 在app-dnsforward中设置了监听端口5353，监听地址127.0.0.1 上游dns8.8.8.8
7. 在shadowsocks中，servermanage中添加了ss服务器信息，常规设置中主服务器也正确选择了，udp服务器停用，端口转发设置也选择了主服务器，本地端口5300，目标地址8.8.4.4:53
8.  访问控制 -> 外网区域设置
「被忽略IP列表」 选择留空(/dev/null)
「额外被忽略IP」 设置为 0.0.0.0/1 和 128.0.0.0/1
代理类型，代理自身都是正常代理
9. 系统状态显示透明代理：运行中，socks5代理未启动，端口转发：运行中
10. 参考issue146中的配置，修改了ss-rule 如下
gfwlist_init() {
    ipt="iptables -t nat"
    setname=$(ipset -n list | grep -w "gfwlist")
    if [ ! "$setname" ]; then
        ipset create gfwlist hash:ip
    fi
    $ipt -I SS_SPEC_WAN_AC 1 -m set --match-set gfwlist dst -j SS_SPEC_WAN_FW
    return 0
}
flush_rules && ipset_init && ipt_nat && ipt_mangle && gfwlist_init && export_ipt_rules
11.在路由器上使用ss-local，在电脑设置socke5代理，可以看到能正常上外网。
12.在电脑端指定路由器192.168.1.1为dns，使用nslookup发现国内baidu等都正常返回，google等都是污染过的ip。
13. 看路由器系统日志
Fri Apr 16 20:50:30 2021 daemon.info dnsmasq[2459]: using nameserver 127.0.0.1#5353 for domain zmw.cn
Fri Apr 16 20:50:30 2021 daemon.info dnsmasq[2459]: using nameserver 127.0.0.1#5353 for domain zkaip.com
Fri Apr 16 20:50:30 2021 daemon.info dnsmasq[2459]: using nameserver 127.0.0.1#5353 for domain zippyshare.com
Fri Apr 16 20:50:30 2021 daemon.info dnsmasq[2459]: using nameserver 127.0.0.1#5353 for domain ziporn.com
Fri Apr 16 20:50:30 2021 daemon.info dnsmasq[2459]: using nameserver 127.0.0.1#5353 for domain zinio.com
Fri Apr 16 20:50:30 2021 daemon.info dnsmasq[2459]: using nameserver 127.0.0.1#5353 for domain zim.vn
Fri Apr 16 20:50:30 2021 daemon.warn dnsmasq[2459]: ignoring nameserver 127.0.0.1 - local interface
Fri Apr 16 20:50:30 2021 daemon.info dnsmasq[2459]: using 5716 more nameservers
Fri Apr 16 20:50:30 2021 daemon.info dnsmasq[2459]: read /etc/hosts - 4 addresses
Fri Apr 16 20:50:30 2021 daemon.info dnsmasq[2459]: read /tmp/hosts/odhcpd - 0 addresses
Fri Apr 16 20:50:30 2021 daemon.info dnsmasq[2459]: read /tmp/hosts/dhcp.cfg01411c - 0 addresses
Fri Apr 16 21:01:09 2021 daemon.err ss-redir[1428]: server recv: Connection reset by peer

试了好几天了，还是没有实现透明代理，能否看看是什么问题？感觉是dns污染没有解决。

**Comment by aa65535** [comment]
强制走代理IP 加上 `dnsforward` 的上游服务器IP试试

**Comment by iyzgit** [comment]
请教具体是什么命令？
