### ISSUE TITLE
首次安装出现 grep: /etc/crontabs/root: No such file or directory 错误

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/luci-app-shadowsocks#274]
可能和系统有关？

https://github.com/shadowsocks/luci-app-shadowsocks/blob/0aa84c8f83195f0c59c66ebd5d78e708c5efe2c7/files/root/etc/uci-defaults/luci-shadowsocks#L25-L28
另外希望这几行可以改成当开启订阅功能时再检查并写入到 crontab.

**Comment by aa65535** [comment]
如果出现报错，可以先执行 `mkdir -p /etc/crontabs` 命令，然后重试。
