### ISSUE TITLE
Compile issue // configure: error: Invalid kernel source directory /lib/modules/4.2.0-27-generic/source

### ISSUE THREAD

**Issue by simonchen** [shadowsocks/luci-app-shadowsocks#28]
I appreciate your help, but unfortunately, I can't compile Luci-app-shadowsocks , below is the errors, any thoughts?

configure: error: Invalid kernel source directory /lib/modules/4.2.0-27-generic/source
make[2]: *** [/home/chen/openwrt/build_dir/target-mips_34kc_musl-1.1.15/linux-ar71xx_generic/ipset-6.24/.configured_yyy] Error 1
make[2]: Leaving directory /home/chen/openwrt/package/network/utils/ipset' make[1]: *** [package/network/utils/ipset/compile] Error 2 make[1]: Leaving directory/home/chen/openwrt'
make: *** [package/luci-app-shadowsocks/compile] Error 2

Note, I'm compiling the luci-app-shadowsocks on 

~Ubuntu 14.04 
~latest Openwrt at https://github.com/openwrt/openwrt.git

**Comment by debiansid** [comment]
Try it in lede

**Comment by aa65535** [comment]
Check your toolchain.
This is ipset's compilation error: **Invalid kernel source directory /lib/modules/4.2.0-27-generic/source**.

**Comment by simonchen** [comment]
Thanks, it works after I simply executed 'make' in 'openwrt' root dir:

 make[1] world
 make[2] toolchain/install
 make[3] -C toolchain/gdb prepare
 make[3] -C toolchain/gdb compile
 make[3] -C toolchain/gdb install
 make[3] -C toolchain/binutils prepare
 make[3] -C toolchain/binutils compile
 make[3] -C toolchain/binutils install
 make[3] -C toolchain/gcc/minimal prepare
 make[3] -C toolchain/gcc/minimal compile
 make[3] -C toolchain/gcc/minimal install
 make[3] -C toolchain/kernel-headers prepare
 make[3] -C toolchain/kernel-headers compile
 make[3] -C toolchain/kernel-headers install
 make[3] -C toolchain/musl/headers prepare
 make[3] -C toolchain/musl/headers compile
 make[3] -C toolchain/musl/headers install
 make[3] -C toolchain/gcc/initial prepare
 make[3] -C toolchain/gcc/initial compile
 make[3] -C toolchain/gcc/initial install
 make[3] -C toolchain/musl prepare
 make[3] -C toolchain/musl compile
 make[3] -C toolchain/musl install
 make[3] -C toolchain/gcc/final prepare
 make[3] -C toolchain/gcc/final compile
 make[3] -C toolchain/gcc/final install
 make[3] -C toolchain/fortify-headers prepare
 make[3] -C toolchain/fortify-headers compile
 make[3] -C toolchain/fortify-headers install
 make[2] target/compile
 make[3] -C target/linux compile
...
