### ISSUE TITLE
RPCError

### ISSUE THREAD

**Issue by johkte** [shadowsocks/luci-app-shadowsocks#289]
Build on OpenWRT master results in this error message when trying to access the shadowsocks-libev luci page:
`RPCError
RPC call to uci/get failed with ubus code 4: Resource not found
  at ClassConstructor.handleCallReply (https://192.168.1.1/luci-static/resources/rpc.js?v=git-22.058.70382-d29400e:15:3)`

**Comment by Lu7fer** [comment]
Same issue.
```
RPCError
RPC call to uci/get failed with ubus code 4: Resource not found
  at ClassConstructor.handleCallReply (http://192.168.1.1/luci-static/resources/rpc.js?v=git-22.052.50801-31a27f3:15:3
```

**Comment by Lu7fer** [comment]
Solved by installing `shadowsocks-libev-config`

> Build on OpenWRT master results in this error message when trying to access the shadowsocks-libev luci page: `RPCError RPC call to uci/get failed with ubus code 4: Resource not found at ClassConstructor.handleCallReply (https://192.168.1.1/luci-static/resources/rpc.js?v=git-22.058.70382-d29400e:15:3)`
