### ISSUE TITLE
luci中将路由器ip设为“直接连接”后，路由发起的流量仍走ss

### ISSUE THREAD

**Issue by YizhouZheng** [shadowsocks/luci-app-shadowsocks#29]
在luci界面中添加了路由（192.168.10.1）直接连接规则之后，路由器发起的目标是国外ip的连接（如aria2，迅雷等）仍然走ss...
是不是因为luci界面从下拉列表中选ip是192.168.10.1而不是127.0.0.1的关系？
这样好像不是很直观..在vps上跑了一阵p2p流量以后才发现，幸亏还没被封...

是不是只能写iptables了..求救...
如果能分进程管理是不是走代理最好...如果不行路由器自己不走代理也不要紧的w

麻烦了...

**Comment by aa65535** [comment]
修改 /etc/init.d/shadowsocks [这里](https://github.com/shadowsocks/luci-app-shadowsocks/blob/v1.3.4/files/root/etc/init.d/shadowsocks#L86) , 将 `-o ` 去掉, 改成 `$(get_arg_udp)`

**Comment by aa65535** [comment]
fix this in 181a96b5a424ff5e3443aab40df04d4c0f856393
