### ISSUE TITLE
2.1.0版更改透明代理主服务器无效

### ISSUE THREAD

**Issue by friezwittenfeld** [shadowsocks/luci-app-shadowsocks#290]
- LEDE Reboot 17.01.4
- luci-app-shadowsocks 2.1.0-1
- shadowsocks-libev 3.3.5-1

更改主服务器无效，永远为启动时的服务器
降级到v2.0.3无此问题

**Comment by aa65535** [comment]
尝试在 `/etc/config/ucitrack` 中添加
```
config shadowsocks
	option init 'shadowsocks'
```

17.01 太老了

**Comment by friezwittenfeld** [comment]
看来要找时间升级了，谢谢
