### ISSUE TITLE
OpenWrt 21.02.3 下菜单汉化不全

### ISSUE THREAD

**Issue by pigpigabc123** [shadowsocks/luci-app-shadowsocks#293]
<img width="363" alt="屏幕截图 2022-07-09 001859" src="https://user-images.githubusercontent.com/23742919/178031344-94026537-3509-482c-b400-955430c51c41.png">

**Comment by onexp** [comment]
缺什么？

**Comment by q741451** [comment]
怀疑是浏览器缓存问题，Ctrl+Shift+N进匿名模式登进去看看
