### ISSUE TITLE
Subscription doesn't work

### ISSUE THREAD

**Issue by kery** [shadowsocks/luci-app-shadowsocks#295]
The subscription doesn't work because of below code. The subscription update will be discarded because the table_equal returns true. Don't quite understand what the purpose of below code. Can you have a look?
```Lua
		local current = get_current_servers()
		if table_equal(servers, current) then
			uci:revert(config)
		else
```

**Comment by oemaix** [comment]
I encountered the very same problem. if i commented out the if claus, it works.

**Comment by oemaix** [comment]
I think the logic is not right here.
It compare only the servers that are used for transparent proxy, socks proxy or port forwarding before and after the update.
IMHO, click the update button means that i want update all the servers, rather then only the ones that currently in use.
btw., the file is files/usr/bin/ss-subscribe
