### ISSUE TITLE
是否不支持ss+v2ray plugin+websocket (HTTP) + TLS +CDN方式？

### ISSUE THREAD

**Issue by hybtw** [shadowsocks/luci-app-shadowsocks#296]
即服务端设置
"plugin_opts":"server;path=/ray"
客户端插件选项tls;host=mydomain.me;path=/ray

在luci界面服务器地址只能输入ip，直接修改config文件填入域名也是运行失败

**Comment by aa65535** [comment]
支持，客户端填入: `tls;mux=0;host=mydomain.me;path=/ray;loglevel=none`
服务器地址填优选的IP就行 ，不需要域名，域名在 host 参数上指定了。
