### ISSUE TITLE
GfwList 支持的一些问题

### ISSUE THREAD

**Issue by kuoruan** [shadowsocks/luci-app-shadowsocks#31]
按照 wiki 之中，使用 gfwlist2dnsmasq 导出规则之后，载入了 dnsmasq 之中，然后将 「额外被忽略IP」 设置为 0.0.0.0/1 和 128.0.0.0/1。开启透明代理，发现所有地址都无法代理
![2016-09-11_174730](https://cloud.githubusercontent.com/assets/8685618/18416447/d56e9e8e-7847-11e6-8ff8-e09455a6ddcc.png)
DHCP/DNS 中保持默认，并没有设置为 ChinaDNS 的端口

**Comment by aa65535** [comment]
`ipset list ss_spec_dst_fw` 看一下是否有 IP，没有的话检查 Dnsmasq 配置。

**Comment by kuoruan** [comment]
![2016-09-11_175805](https://cloud.githubusercontent.com/assets/8685618/18416500/51fa3872-7849-11e6-9b71-5b5cfd0c4fee.png)
这个我当时就看了，也没看出来是有还是没有，dnsmasq 运行正常，解析也正常。
![2016-09-11_180018](https://cloud.githubusercontent.com/assets/8685618/18416519/a13645d4-7849-11e6-9e5d-2b5fdaf677be.png)

**Comment by aa65535** [comment]
Dnsmasq 没有将解析结果保存到 ipset ss_spec_dst_fw 里，确认使用的是 Dnsmasq-full 版本，ipset 名称是 ss_spec_dst_fw 。

**Comment by kuoruan** [comment]
Openwrt为自己编译：
![2016-09-11_181120](https://cloud.githubusercontent.com/assets/8685618/18416589/3e1037ec-784b-11e6-882f-f7275609c14d.png)
导出的规则：
![2016-09-11_181134](https://cloud.githubusercontent.com/assets/8685618/18416590/4cffb49e-784b-11e6-8d4d-e02932bf7766.png)

仅在 /etc/dnsmasq.conf 中追加了 ```conf-dir=/etc/dnsmasq.d```
![2016-09-11_181705](https://cloud.githubusercontent.com/assets/8685618/18416623/01ce8760-784c-11e6-93a4-4e4555d9ac9f.png)

是否还有其他需要检查的地方？

**Comment by aa65535** [comment]
检查一下系统日志 `logread | grep dnsmasq`
还有生成的 Dnsmasq 配置文件 `cat /var/etc/dnsmasq.conf`

**Comment by kuoruan** [comment]
手动写了几条规则之后重启 dnsmasq，查看日志：
```
Sun Sep 11 18:47:06 2016 daemon.info dnsmasq[3923]: reading /tmp/resolv.conf.auto
Sun Sep 11 18:47:06 2016 daemon.info dnsmasq[3923]: using local addresses only for domain lan
Sun Sep 11 18:47:06 2016 daemon.info dnsmasq[3923]: using nameserver 127.0.0.1#5353 for domain youtube.com
Sun Sep 11 18:47:06 2016 daemon.info dnsmasq[3923]: using nameserver 127.0.0.1#5353 for domain google.com.sg
Sun Sep 11 18:47:06 2016 daemon.info dnsmasq[3923]: using nameserver 127.0.0.1#5353 for domain google.com
Sun Sep 11 18:47:06 2016 daemon.info dnsmasq[3923]: using nameserver 59.108.61.61#53
Sun Sep 11 18:47:06 2016 daemon.info dnsmasq[3923]: using nameserver 219.232.48.61#53
Sun Sep 11 18:47:07 2016 daemon.info dnsmasq[3923]: read /etc/hosts - 4 addresses
Sun Sep 11 18:47:07 2016 daemon.info dnsmasq[3923]: read /tmp/hosts/dhcp - 2 addresses
Sun Sep 11 18:47:07 2016 daemon.info dnsmasq-dhcp[3923]: read /etc/ethers - 0 addresses
```
能看到已经载入了配置
```
cat /var/etc/dnsmasq.conf 
# auto-generated config file from /etc/config/dhcp
conf-file=/etc/dnsmasq.conf
dhcp-authoritative
domain-needed
localise-queries
read-ethers
bogus-priv
expand-hosts
local-service
domain=lan
server=/lan/
dhcp-leasefile=/tmp/dhcp.leases
resolv-file=/tmp/resolv.conf.auto
stop-dns-rebind
rebind-localhost-ok
dhcp-broadcast=tag:needs-broadcast
addn-hosts=/tmp/hosts
conf-dir=/tmp/dnsmasq.d
user=dnsmasq
group=dnsmasq




dhcp-range=lan,192.168.1.100,192.168.1.249,255.255.255.0,12h
no-dhcp-interface=eth0.2
```
查看生成的配置文件，发现 ```conf-dir=/tmp/dnsmasq.d```
进入这个目录，并没有任何东西。

**Comment by kuoruan** [comment]
现在已经能看到 list 里边有IP了，好现象。

**Comment by aa65535** [comment]
@kuoruan 
是的，下游设备的 DNS 缓存也需要清理掉，这样才能使用 Dnsmasq 去重新请求解析结果同时添加到 ipset 中，如果重启了 shadowsocks ，需要同时重启 Dnsmasq 和清空下游设备的 DNS 缓存。
