### ISSUE TITLE
请问路由器端日志总是这样提示，不知为何

### ISSUE THREAD

**Issue by ztechie** [shadowsocks/luci-app-shadowsocks#35]
Thu Sep 15 11:19:37 2016 kern.info ss-redir[2209]: Request did not begin with TLS handshake.
Thu Sep 15 11:19:37 2016 kern.info ss-redir[2209]: Request did not begin with TLS handshake.
Thu Sep 15 11:19:37 2016 kern.info ss-redir[2209]: Request did not begin with TLS handshake.
Thu Sep 15 11:19:39 2016 kern.info ss-redir[2209]: Request did not begin with TLS handshake.
Thu Sep 15 11:19:39 2016 kern.info ss-redir[2209]: Request did not begin with TLS handshake.
Thu Sep 15 11:19:40 2016 kern.info ss-redir[2209]: Request did not begin with TLS handshake.
Thu Sep 15 11:19:42 2016 kern.info ss-redir[2209]: Request did not begin with TLS handshake.
Thu Sep 15 11:20:01 2016 kern.info ss-redir[2209]: Request did not begin with TLS handshake.
Thu Sep 15 11:20:01 2016 kern.info ss-redir[2209]: Request did not begin with TLS handshake.
Thu Sep 15 11:20:01 2016 kern.info ss-redir[2209]: Request did not begin with TLS handshake.
Thu Sep 15 11:20:02 2016 kern.info ss-redir[2209]: Request did not begin with TLS handshake.
Thu Sep 15 11:20:02 2016 kern.info ss-redir[2209]: Request did not begin with TLS handshake.
Thu Sep 15 11:20:02 2016 kern.info ss-redir[2209]: Request did not begin with TLS handshake.
Thu Sep 15 11:20:09 2016 kern.info ss-redir[2209]: Request did not begin with TLS handshake.
Thu Sep 15 11:20:09 2016 kern.info ss-redir[2209]: Request did not begin with TLS handshake.
Thu Sep 15 11:20:09 2016 kern.info ss-redir[2209]: Request did not begin with TLS handshake.
Thu Sep 15 11:20:09 2016 kern.info ss-redir[2209]: Request did not begin with TLS handshake.
Thu Sep 15 11:20:09 2016 kern.info ss-redir[2209]: Request did not begin with TLS handshake.
Thu Sep 15 11:20:09 2016 kern.info ss-redir[2209]: Request did not begin with TLS handshake.
Thu Sep 15 11:20:09 2016 kern.info ss-redir[2209]: Request did not begin with TLS handshake.
Thu Sep 15 11:20:44 2016 kern.info ss-redir[2209]: Request did not begin with TLS handshake.
Thu Sep 15 11:20:44 2016 kern.info ss-redir[2209]: Request did not begin with TLS handshake.

**Comment by wongsyrone** [comment]
https://github.com/shadowsocks/shadowsocks-libev/issues/832#issuecomment-247224550
