### ISSUE TITLE
Shadowsocks init startup not work

### ISSUE THREAD

**Issue by whao** [shadowsocks/luci-app-shadowsocks#36]
Model	NETGEAR WNDR4300
Firmware Version	OpenWrt Chaos Calmer 15.05.1 / LuCI 15.05-149-g0d8bbd2 Release (git-15.363.78009-956be55)
Kernel Version	3.18.23

After upgrading to the latest version of luci-app-shadowsocks - 1.3.5-1 and shadowsocks-libev - 2.5.2-1. The initscript seems to be not working. The ss-redir won't automatically run after rebooting even if I ran the "/etc/init.d/shadowsocks enable". I have to manually start it from terminal or web.

Thanks

**Comment by aa65535** [comment]
Unable to reproduce this issue, try to reinstall `luci-app-shadowsocks`.

**Comment by whao** [comment]
Issue persists after reinstalling `luci-app-shadowsocks`. My linksys wrt1900 has the same issue. Only socks5(ss-local) runs at startup but ss-redir doesn't.

Thanks

**Comment by whao** [comment]
Also when ss-redir is running
`root@OpenWrt:/tmp/etc# ps | grep ss`
`2138 root      3212 S    ss-redir -c /var/etc/shadowsocks.json -u -A -l 1234 -f /var/run/ss-redir.pid`
` 2238 root      3184 S    ss-local -c /var/etc/shadowsocks.json -u -A -l 1080 -f /var/run/ss-local.pid`
I cannot find json config file.
`root@OpenWrt:/tmp/etc# cat /var/etc/shadowsocks.json`
`cat: can't open '/var/etc/shadowsocks.json': No such file or directory`

**Comment by aa65535** [comment]
The file `/etc/uci-defaults/luci-shadowsocks` exists？

About `/var/etc/shadowsocks.json` see 357433bc7c93145af8ba693e3ad845b01a308da4 .

**Comment by aa65535** [comment]
Which version of the OpenWrt?

**Comment by whao** [comment]
Firmware Version OpenWrt Chaos Calmer 15.05.1 / LuCI 15.05-149-g0d8bbd2 Release (git-15.363.78009-956be55)
Kernel Version 3.18.23
uname -a: `Linux OpenWrt 3.18.23 #1 Sun Jan 31 18:23:08 CET 2016 mips GNU/Linux`

`root@OpenWrt:~# cat /etc/uci-defaults/luci-shadowsocks` 
`cat: can't open '/etc/uci-defaults/luci-shadowsocks': No such file or directory`

**Comment by aa65535** [comment]
Execute the following command to fix the issus.
```sh
uci delete ucitrack.@shadowsocks[-1]
uci add ucitrack shadowsocks
uci set ucitrack.@shadowsocks[-1].init=shadowsocks
uci commit ucitrack
uci delete firewall.shadowsocks
uci set firewall.shadowsocks=include
uci set firewall.shadowsocks.type=script
uci set firewall.shadowsocks.path=/var/etc/shadowsocks.include
uci set firewall.shadowsocks.reload=1
uci commit firewall
```

**Comment by aa65535** [comment]
BTW, the v1.3.4-1 not have this issue?

**Comment by whao** [comment]
不行，我放弃了。
在rc.local里面加了一个shadowsocks restart命令了。先这样凑合用着等过两天重现装一下系统来试一下还有没有问题再来反馈：）

谢谢

**Comment by aa65535** [comment]
问题应该就是 ucitrack 信息没有写入成功，可以看看 /etc/config/ucitrack 里面有没有 shadowsocks 信息，没有的话，上面的命令是可以解决的。

**Comment by whao** [comment]
```
config shadowsocks
	option init 'shadowsocks'
```
有这个 我自己在看看吧 主要是不太懂luci

**Comment by cokebar** [comment]
从那个版本升级上来的？

**Comment by WeiqiChenCN** [comment]
我也有同样的问题。
```bash
root@Raspberrypi-OpenWRT:~# ls /etc/uci-defaults/
root@Raspberrypi-OpenWRT:~# vim fix.sh
root@Raspberrypi-OpenWRT:~# cat fix.sh
uci delete ucitrack.@shadowsocks[-1]
uci add ucitrack shadowsocks
uci set ucitrack.@shadowsocks[-1].init=shadowsocks
uci commit ucitrack
uci delete firewall.shadowsocks
uci set firewall.shadowsocks=include
uci set firewall.shadowsocks.type=script
uci set firewall.shadowsocks.path=/var/etc/shadowsocks.include
uci set firewall.shadowsocks.reload=1
uci commit firewall
root@Raspberrypi-OpenWRT:~# sh fix.sh
cfg26f0ae
root@Raspberrypi-OpenWRT:~# ls /etc/uci-defaults/
root@Raspberrypi-OpenWRT:~# tail /etc/config/ucitrack

config tinyproxy
        option init 'tinyproxy'

config 6relayd
        option init '6relayd'

config shadowsocks
        option init 'shadowsocks'

root@Raspberrypi-OpenWRT:~#

```

我更新一下相关的git再编译看看该问题是否存在吧。迟一点update。

**Comment by WeiqiChenCN** [comment]
依然不行，luci-app-shadowsocks卸载后重新安装问题照旧。

版本信息
```bash
root@Raspberrypi-OpenWRT:~# cat /etc/openwrt_*
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='15.05'
DISTRIB_REVISION='r46767'
DISTRIB_CODENAME='chaos_calmer'
DISTRIB_TARGET='brcm2708/bcm2709'
DISTRIB_DESCRIPTION='OpenWrt Chaos Calmer 15.05'
DISTRIB_TAINTS=''
15.05
root@Raspberrypi-OpenWRT:~# opkg list-installed | grep shadow
luci-app-shadowsocks - 1.6.3-1
shadowsocks-libev - 3.0.5-1
shadowsocks-libev-server - 3.0.5-1
root@Raspberrypi-OpenWRT:~# 
```

该目录依然为空
```
root@Raspberrypi-OpenWRT:~# ls /etc/uci-defaults/
root@Raspberrypi-OpenWRT:~# ./fix.sh 
cfg26f0ae
root@Raspberrypi-OpenWRT:~# ls /etc/uci-defaults/
root@Raspberrypi-OpenWRT:~# 

```

**Comment by WeiqiChenCN** [comment]
我刚才发现，如果通过openwrt网页startup页面设置的开机启动是失败的；
只有通过/etc/init.d/<name> enable并确保/etc/rc.d/xxx 存在相应的软链接才行。
现在ss可以正常开机启动了。

**Comment by whao** [comment]
@WeiqiChenCN 你可以试试Startup Delay 15s 30s什么的
