### ISSUE TITLE
Package kmod-adm8211 is missing dependencies for the following libraries: eeprom_93cx6.ko

### ISSUE THREAD

**Issue by xayane** [shadowsocks/luci-app-shadowsocks#37]
SDK 下载的是：
https://downloads.lede-project.org/snapshots/targets/ipq806x/generic/lede-sdk-ipq806x_gcc-5.4.0_musl-1.1.15_eabi.Linux-x86_64.tar.bz2

按照documents的要求编译，在最后编译的时候：
“
find /home/lede-sdk-ipq806x_gcc-5.4.0_musl-1.1.15_eabi.Linux-x86_64/build_dir/target-arm_cortex-a15+neon-vfpv4_musl-1.1.15_eabi/linux-ipq806x/compat-wireless-2016-06-20/ipkg-arm_cortex-a15_neon-vfpv4/kmod-adm8211 -name 'CVS' -o -name '.svn' -o -name '.#*' -o -name '*~'| xargs -r rm -rf
Package kmod-adm8211 is missing dependencies for the following libraries:
eeprom_93cx6.ko
Makefile:1753: recipe for target '/home/lede-sdk-ipq806x_gcc-5.4.0_musl-1.1.15_eabi.Linux-x86_64/bin/targets/ipq806x/generic/packages/kmod-adm8211_4.4.21+2016-06-20-1_arm_cortex-a15_neon-vfpv4.ipk' failed
make[2]: *** [/home/lede-sdk-ipq806x_gcc-5.4.0_musl-1.1.15_eabi.Linux-x86_64/bin/targets/ipq806x/generic/packages/kmod-adm8211_4.4.21+2016-06-20-1_arm_cortex-a15_neon-vfpv4.ipk] Error 1
make[2]: Leaving directory '/home/lede-sdk-ipq806x_gcc-5.4.0_musl-1.1.15_eabi.Linux-x86_64/feeds/base/package/kernel/mac80211'
package/Makefile:124: recipe for target 'package/feeds/base/mac80211/compile' failed
make[1]: *** [package/feeds/base/mac80211/compile] Error 2
make[1]: Leaving directory '/home/lede-sdk-ipq806x_gcc-5.4.0_musl-1.1.15_eabi.Linux-x86_64'
/home/lede-sdk-ipq806x_gcc-5.4.0_musl-1.1.15_eabi.Linux-x86_64/include/toplevel.mk:186: recipe for target 'package/luci-app-shadowsocks/compile' failed
make: *** [package/luci-app-shadowsocks/compile] Error 2
”

看错误是Package kmod-adm8211 is missing dependencies for the following libraries: eeprom_93cx6.ko。
eeprom_93cx6.ko我搜索了下，没查到。。

是我有哪些依赖文件没装吗？

**Comment by xayane** [comment]
@aa65535 你这边用这个SDK可以编译通过吗？

**Comment by aa65535** [comment]
是的，luci-app-shadowsocks 与 kmod-adm8211 没有关系，尝试重新下载 sdk 编译。
