### ISSUE TITLE
访问控制 标签反应迟钝

### ISSUE THREAD

**Issue by millionart** [shadowsocks/luci-app-shadowsocks#39]
shadowsocks/access-control/
这个标签点击后要很久很久才会打开，长达几分钟甚至有时打不开，其他页面均无此现象
版本mvebu  1.3.5-1
上个版本也有这个问题

**Comment by pexcn** [comment]
https://github.com/shadowsocks/luci-app-shadowsocks/issues/32

**Comment by aa65535** [comment]
请试一下 797f8b6 是否可以解决这个问题。

**Comment by millionart** [comment]
貌似是没问题了，哦耶
谢谢
