### ISSUE TITLE
安装后服务默认是禁用的

### ISSUE THREAD

**Issue by kkjoy** [shadowsocks/luci-app-shadowsocks#4]
安装后在/etc/rc.d 里的链接文件是禁用的，需要手工修改启动项才可以

**Comment by aa65535** [comment]
应该是 /lib/functions.sh 文件里 default_postinst 函数的问题。
安装之后会自动 enable 和 start 的。

**Comment by kkjoy** [comment]
之前的luci-app-shadowsocks-spec 和247 版本安装后就可以正常自动启动的

**Comment by kkjoy** [comment]
我用的imagewriter打包，首次启动在/etc/rc.d里找不到链接文件，而其他启动项都能正常启动

**Comment by aa65535** [comment]
@kkjoy ImageBuilder? 是什么版本？
提供一个下载的链接，我复现一下。

**Comment by kkjoy** [comment]
https://downloads.openwrt.org/chaos_calmer/15.05.1/ar71xx/generic/OpenWrt-ImageBuilder-15.05.1-ar71xx-generic.Linux-x86_64.tar.bz2
下面是我自用的打包命令
make image PROFILE="UBNTAIRROUTER" PACKAGES="luci luci-theme-bootstrap luci-i18n-base-zh-cn ChinaDNS luci-app-chinadns shadowsocks-libev-polarssl luci-app-shadowsocks wget-nossl ddns-scripts dnscrypt-proxy iptables-mod-tproxy" FILES=~/config/ubntdns/
repositories.conf里添加了你的源
src/gz openwrt_dist http://openwrt-dist.sourceforge.net/releases/ar71xx/packages
src/gz openwrt_dist_luci http://openwrt-dist.sourceforge.net/releases/luci/packages
src/gz exopenwrt http://exopenwrt.roland.black/chaos_calmer/15.05.1/ar71xx/packages/exopenwrt
刷机后其他程序都是可以自己启动的，包括之前的旧版spec程序。新的到了启动项设置就是这样的。。
![1](https://cloud.githubusercontent.com/assets/216436/17690453/52adc212-63c1-11e6-92b3-ec3453f11f01.PNG)

**Comment by aa65535** [comment]
导致这个问题的原因是因为打包的 SDK 被修改过, 没有了下面这个 postinst 文件
```sh
#!/bin/sh
[ "${IPKG_NO_SCRIPT}" = "1" ] && exit 0
. ${IPKG_INSTROOT}/lib/functions.sh
default_postinst $0 $@
```

后期打包会解决这个问题.

可以试一下这个, 应该是没问题的.
[luci-app-shadowsocks_1.1.0-1_all.ipk.zip](https://github.com/shadowsocks/luci-app-shadowsocks/files/419719/luci-app-shadowsocks_1.1.0-1_all.ipk.zip)
