### ISSUE TITLE
Luci启动参数并没有配置文件

### ISSUE THREAD

**Issue by acgotaku** [shadowsocks/luci-app-shadowsocks#41]
root@OpenWrt:~# ps | grep shadow
  932 root      1992 S    ss-redir -c /var/etc/shadowsocks.json -l 1234 -f /var/run/ss-redir.pid
 1365 root      1356 S    grep shadow
root@OpenWrt:~# cd /var/etc/
root@OpenWrt:/tmp/etc# ls
dnsmasq.conf
root@OpenWrt:/tmp/etc# 

开启了透明代理，ssh进路由器查看启动进程 发现配置文件` /var/etc/shadowsocks.json` 并不存在

请问，是不是在业务逻辑上忘记生成配置文件了？ 还是我操作有问题呢？

**Comment by acgotaku** [comment]
脚本主要内容在 `https://github.com/shadowsocks/luci-app-shadowsocks/blob/master/files/root/etc/init.d/shadowsocks`

我很好奇怎么调用里面的函数呢？ 使用 `./shadowsocks --help` 发现只有基本的启动参数 和我期待的不太一样。。。

**Comment by wongsyrone** [comment]
生成配置文件在gen_config_file，一般情况，在OP里面/var就是/tmp

**Comment by wongsyrone** [comment]
要想调试可以set -x看看哪个地方有问题

**Comment by acgotaku** [comment]
@wongsyrone 但是那个位置明显啥也没有 QAQ ss无法正常启动啊

**Comment by wongsyrone** [comment]
https://github.com/shadowsocks/openwrt-shadowsocks 这个不是提供二进制么

**Comment by acgotaku** [comment]
@wongsyrone 我装了啊 我是说启动参数的配置文件 在文件系统里面并没有 导致 ss本质上没有正常启动

**Comment by wongsyrone** [comment]
诶，那我就不太清楚了，我用的是自己编译的

**Comment by acgotaku** [comment]
@wongsyrone 那你肯定是完全命令行模式了。。。

**Comment by wongsyrone** [comment]
我没用UCI和LuCI，直接配的，可以参考https://github.com/wongsyrone/lede-1/tree/master/package/external/shadowsocks-libev

**Comment by acgotaku** [comment]
@wongsyrone 你这水平太高了 QAQ

**Comment by wongsyrone** [comment]
QAQ求菊苣给留点面子

**Comment by aa65535** [comment]
@acgotaku 
ss 没有正常启动应该不是没有 `/var/etc/shadowsocks.json`.
因为临时的配置文件会在启动后会删掉, 因为会有用户去尝试修改这个配置文件.
https://github.com/shadowsocks/luci-app-shadowsocks/blob/master/files/root/etc/init.d/shadowsocks#L159

init script 只能调用 `start stop restart rules` 这几个函数.

**Comment by aa65535** [comment]
>root@OpenWrt:~# ps | grep shadow
>932 root 1992 S ss-redir -c /var/etc/shadowsocks.json -l 1234 -f /var/run/ss-redir.pid

不对啊，ss-redir 进程是存在的，说明启动了。

**Comment by acgotaku** [comment]
@aa65535 原来是这样 那应该是其他地方出错了 出丑了 QAQ
