### ISSUE TITLE
ss-rules报错

### ISSUE THREAD

**Issue by shentg** [shadowsocks/luci-app-shadowsocks#42]
我的路由器是TP-Link TL-WDR4310 v1，OpenWrt Chaos Calmer 15.05 / LuCI (git-15.248.30277-3836b45)
安装的是
luci-app-shadowsocks	1.3.6-1
shadowsocks-libev	2.4.8-3

启动shadowsocks时ss-rule有问题。

> iptables v1.4.21: unknown option "--on-port"
Try `iptables -h' or 'iptables --help' for more information.
ss-rules[25931]: Start failed!

iptables是用opkg安装的，是iptables这个版本不兼容么？

**Comment by aa65535** [comment]
有安装 `iptables-mod-tproxy` 么？ 安装后重启路由器了么？

**Comment by shentg** [comment]
不好意思，应该是重装iptables的时候卸载量iptables-mod-tproxy，重新安装后正常。
