### ISSUE TITLE
好奇怪有dns污染也能打开网站？

### ISSUE THREAD

**Issue by DragonCat1** [shadowsocks/luci-app-shadowsocks#44]
我就安了openwrt-shadowsocks和luci-app-shadowsocks，没弄域名解析转发，但不影响上网，而且这些站解析到的ip都是93.46.8.89，查了wiki这明明是被污染的ip，我有点搞不懂了...贴图
![qq 20160928053655](https://cloud.githubusercontent.com/assets/17510330/18892817/bb4b8168-853d-11e6-9482-c3cabe258a50.png)
![qq 20160928053703](https://cloud.githubusercontent.com/assets/17510330/18892819/bb4ef5e6-853d-11e6-8c59-6b295d48dc7b.png)
![qq 20160928053722](https://cloud.githubusercontent.com/assets/17510330/18892820/bb4f5996-853d-11e6-8678-f26fb0e88b69.png)
![qq 20160928053730](https://cloud.githubusercontent.com/assets/17510330/18892821/bb5245de-853d-11e6-92b8-75a48dea648c.png)
![qq 20160928053747](https://cloud.githubusercontent.com/assets/17510330/18892818/bb4e722e-853d-11e6-940a-3412def37a8e.png)
![qq 20160928053548](https://cloud.githubusercontent.com/assets/17510330/18892771/72aac8ce-853d-11e6-8015-52d78e6f7aba.png)

**Comment by aa65535** [comment]
使用 dig 查看解析结果, `Remote Address` 并不是实际连接的地址.
