### ISSUE TITLE
mbedtls 有开启多线程补丁吗？

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/luci-app-shadowsocks#49]
请问这里的 https://dl.bintray.com/aa65535/opkg/shadowsocks-libev/2.5.3/ libmbedtls 有开启多线程补丁吗？

从这里 https://twitter.com/syronewong/status/722029690685251588 得知，多线程默认关闭的。

mbedtls 补丁：tweak config for shadowsocks-libev: https://github.com/wongsyrone/lede-1/commit/dfa308c9a9b988535ab3bec4a70d13d8547b5758

**Comment by aa65535** [comment]
直接删除 [200-config.patch](https://github.com/openwrt/openwrt/blob/master/package/libs/mbedtls/patches/200-config.patch) 后编译的。

**Comment by pexcn** [comment]
谢谢～
