### ISSUE TITLE
只有客户端的luci界面，希望添加服务端的界面

### ISSUE THREAD

**Issue by lingbaoboy** [shadowsocks/luci-app-shadowsocks#5]

**Comment by lingbaoboy** [comment]
只有客户端的luci界面，希望添加服务端的界面

没有服务端设置界面，要想在路由器上运行SS的服务端必须命令行设置了，不太友好，要是集成服务端设置就完美了。
可以在openwrt上挂服务端，想当个vpn了，从外网可以访问内网了

**Comment by aa65535** [comment]
No plan for this.
