### ISSUE TITLE
anyway to upgrade through "opkg update" ?

### ISSUE THREAD

**Issue by DreamSeason** [shadowsocks/luci-app-shadowsocks#51]
First of all, this is not related to luci-app but the openwrt version of shadow socks. But I don't know how to contact with the author so I have to leave an issue here.
I notice there are package.gz file in the link you've provided for openwrt  shadowsocks. So I think maybe there's a way for easier upgrade. I tested adding the following link to the packages list and used "opkg update" but it showed errors. So I'd like to know if that's possible and if so how to do it. Thx

_Link that I tested ( not working)_
[http://dl.bintray.com/aa65535/opkg/shadowsocks-libev/](url)
[https://dl.bintray.com/aa65535/opkg/shadowsocks-libev/](url)

one link that seems at least did something:
[http://dl.bintray.com/aa65535/opkg/shadowsocks-libev/2.5.5/ar71xx](url)
and it's corresponding error:

> 
* opkg_download: Failed to download http://dl.bintray.com/aa65535/opkg/shadowsocks-libev/2.5.5/ar71xx/Packages.sig, wget returned 1.

**Comment by aa65535** [comment]
The package.gz generated by Bintray.

>
Resolving OPKG packages
To use Bintray repository to install ipk packages you need to add an indexed path (a feed) to your opkg.conf file. You can do that using the following command:
```
echo 'src <FEED_NAME> https://dl.bintray.com/aa65535/opkg/<FILE_TARGET_PATH>' >> /etc/opkg/opkg.conf
```
If you want your client to download the .gz variant of the Packages index file instead, change the src part to src/gz. 
To access Bintray using credentials you can specify them in the opkg.conf file as follows
```
echo 'option http_auth aa65535:<API_KEY>' >> /etc/opkg/opkg.conf
```
Your Opkg client will use the specified Bintray repositories after update resources
```
opkg update
```
Install the package
```
opkg install <PACKAGE>
```

You can try this repo: http://openwrt-dist.sourceforge.net/dist/ .
