### ISSUE TITLE
ipv6环境下不能自启

### ISSUE THREAD

**Issue by lixingcong** [shadowsocks/luci-app-shadowsocks#53]
我有一个路由器，使用luci-app-shadowsocks（1.3.6），ss指向同一个vps，填入inet4地址和inet6地址都是正确的。

现将该路由器置于两个网络环境：PPPoE拨号ipv6（校园网）和PPPoE拨号ipv4（移动宽带）

现象是ipv4可以正常自启luci-app-shadowsocks，ss-redir也正常启动，但是在ipv6环境下不能自启luci-app-shadowsocks，需要进入"服务->shadowsocks"点击页面底部“Save and Apply”才能启动ss-redir，每次都需要手动打开luci web界面才能启动，也是麻烦，不过应该可以往/etc/rc.local写入启动启动脚本强制自启。

我记得在ss-openwrt-spec早期版本(好像是2.4.6)是可以v6环境下实现openwrt开机自动启动的。。不清楚作者是怎么判断v6地址连通性然后触发init.d脚本的呢？

**Comment by aa65535** [comment]
目前并不网络是否已经连接，只要 iptable 里有对应的链即可。
现在是先执行 ss-redir 后执行 ss-rules ，可以看一下 ss-redir 有没有正确启动。
另外，检查系统日志。
