### ISSUE TITLE
`ss-rules` should bypass `$server:$port` instead of `$server`

### ISSUE THREAD

**Issue by vimagick** [shadowsocks/luci-app-shadowsocks#54]
Inside [gen_special_purpose_ip()](https://github.com/shadowsocks/luci-app-shadowsocks/blob/master/files/root/usr/bin/ss-rules#L129-L153) function, `$server` and `$SERVER` are bypassed.
If I access website hosted on `$server`/`$SERVER`, all traffic will not be protected.

This is a quickfix:

``` bash
# I'm running TCP and UDP service on 1.2.3.4:8388
iptables -t nat -I SS_SPEC_WAN_AC -d 1.2.3.4 -p tcp --dport 8388 -j RETURN
iptables -t nat -I SS_SPEC_WAN_AC -d 1.2.3.4 -p udp --dport 8388 -j RETURN
iptables -t mangle -I SS_SPEC_WAN_AC -d 1.2.3.4 -p tcp --dport 8388 -j RETURN
iptables -t mangle -I SS_SPEC_WAN_AC -d 1.2.3.4 -p udp --dport 8388 -j RETURN
ipset del ss_spec_dst_sp 1.2.3.4
```

**Comment by aa65535** [comment]
This is superfluous, do not expect to use shadowsocks to protect your traffic.
