### ISSUE TITLE
udp转发和udp中继服务器是什么意思？

### ISSUE THREAD

**Issue by hdstar2009** [shadowsocks/luci-app-shadowsocks#55]
没有看到相关说明，虽然自己有理解，但是觉得还是官方（作者设计者的解释最权威）。

udp转发是用来dns查询的？可以任意指定本地的某个端口转发到一个服务器的指定端口吗？还是说仅仅dns查询用？

udp中继服务器，是指将udp数据包发到中继服务器处理（ss服务器）？一般情况ss程序只发送tcp数据。是这样理解？

**Comment by hdstar2009** [comment]
似乎以上理解不对。开了udp中继和不开，nat表的内容完全没变化。
开了udp中继，ps也看不到ss-local程序，还是只有ss-redir，同时/var/etc/shadowsocks.json前后也无变化。
难道这个udp中继服务器完全没起作用？

**Comment by aa65535** [comment]
是你理解的那样。
但是，你使用的应该不是我提供的版本，或者不是最新版本，因为目前没有这个两个名词。

**Comment by hdstar2009** [comment]
嗯，我刚刚看到有新版的luci，然后发现新版的luci又有了新名词，理解困难了。
比如那个访问控制下的内网区域，这个指什么？我开始理解是说内网的机器，比如10,192等开头的主机，访问这些主机不用代理，所以选择直接连接，外网或者qq都上不了了。只有选择 正常代理，才能上qq和外网。

所以我的个人意见：设置相关的一些名词具体是指什么能否加个说明？

另，新版的luci是用的udp服务器，我记得之前的版本是叫做udp中继服务器。这些名词和作用，我觉得应该至少有个简单说明是做什么用的。

**Comment by aa65535** [comment]
@hdstar2009 
https://github.com/shadowsocks/luci-app-shadowsocks/wiki/LuCI-Access-Control
https://github.com/shadowsocks/luci-app-shadowsocks/wiki/Use-UCI-system
