### ISSUE TITLE
openwrt版本的SSR 是否支持UDP over TCP？

### ISSUE THREAD

**Issue by feizhenzhuang** [shadowsocks/luci-app-shadowsocks#56]
请问openwrt 版本的SSR是否支持这一功能啊 ？  因为在PC端使用kcptun加速时 如果不勾选UDP over TCP 则过一段时间 ISP就会封锁我的端口  然后过一会才会解封。 经测试 我勾选这一选项后  就不会被封了  。当然这是PC端的  请问 openwrt版本支持这一功能吗？  谢谢作者的回复  :)

**Comment by aa65535** [comment]
这里不提供 SSR.
