### ISSUE TITLE
程序版本问题

### ISSUE THREAD

**Issue by UISAHF** [shadowsocks/luci-app-shadowsocks#6]
sf上最新版本是1.5.0
git上又出来个写着1.0.0的1.1.0..
这之间是什么关系啊 要用新版本的话 还是用sf上的对吧

**Comment by aa65535** [comment]
1.5.0 是 luci-app-shadowsocks-spec 属于 openwrt-dist-luci 项目
1.0.0 是 luci-app-shadowsocks 也就是本项目
这是两个不同的项目，他们的区别和关系参考 aa65535/openwrt-dist-luci#35
