### ISSUE TITLE
【显示bug】访问控制 内网主机，主机IP变红字

### ISSUE THREAD

**Issue by cokebar** [shadowsocks/luci-app-shadowsocks#60]
不知为何，即使输入了正确的IP也会出现红字。但不影响正常使用，设置也会正常生效。
重新点击某条IP，展开列表后，字会变灰色，然后保存应用后会重新变成红字。
截图见：
http://imgur.com/cx2SOOC

luci-app-shadowsocks: v1.3.7
LuCI Master (git-16.298.34250-95358ab)
OpenWrt Designated Driver 49965

**Comment by aa65535** [comment]
这个是 DD 版的 LuCI 的问题。

**Comment by aa65535** [comment]
fix in https://github.com/openwrt/luci/pull/917

**Comment by cokebar** [comment]
LEDE也有同样问题 是否需要也向LEDE提交pr？

**Comment by wongsyrone** [comment]
不用，目前两个项目共用packages和luci
