### ISSUE TITLE
SS 无法和 mwan 2.0.x 共存 

### ISSUE THREAD

**Issue by muronghan** [shadowsocks/luci-app-shadowsocks#65]
不知道是否该发到这里。

目前ss和mwan3项目2.0.x的版本（该mwan3版本目前只用于OpenWrt/LEDE 4.x核以上）有共存问题。具体表现在用speedtest测试，流量一开始很小，从0逐步缓慢攀升到峰值，以后忽高忽低。与此同时，同样的ss版本和mwan3 1.6.x (OpenWrt 核心为3.18.x）算是共存蛮好。经过多次试验，我认为可能问题出在：https://wiki.openwrt.org/doc/howto/mwan3#the_routable_loopback_self

也就是mwan3 2.0.x引入了新的机制，并在/etc/config/network里增加了类似下面这段script:

config interface 'self'
	option ifname 'lo'
	option proto 'static'
	option ipaddr '192.168.xx.1'
	option netmask '255.255.255.255'
	option gateway '192.168.xx.1'

如果上面这段script移走，ss的流量就恢复正常，但是mwan3的分流机制会出现问题，即很多路由器触发的流量会走metric小的那个缺省wan口。

**Comment by muronghan** [comment]
我加了一个metric值，比如是5，如下：

config interface 'self'
	option ifname 'lo'
	option proto 'static'
	option ipaddr '192.168.xx.1'
	option netmask '255.255.255.255'
	option gateway '192.168.xx.1'
	option metric '5'

目前mwan3和ss好像是没有冲突了。但是还有点小毛病，就是双线其中一根线断，另一个failure over不起作用，而在老版本里是没有问题的。

暂时关闭这个问题。

**Comment by muronghan** [comment]
最近多次测试了mwan3 2.0.3和ss在LEDE共存的问题，目前打开ss代理的网页通常要好几秒钟，单独使用这两个应用是没问题的，所以共存的毛病依然存在。

**Comment by aa65535** [comment]
请提供一下它们同时开启时 `iptables-save` 的打印信息。

**Comment by muronghan** [comment]
@aa65535 ，详见：https://pan.baidu.com/s/1cuyBMY，mwan3 1.6.2运行于OpenWrt CC.01，mwan3 2.0.3运行于LEDE。两者的设置相似。

mwan 2.0.3 不同的地方，是要在/etc/config/network里加一段：

config interface 'self'
	option ifname 'lo'
	option proto 'static'
	option ipaddr '192.168.xx.1'
	option netmask '255.255.255.255'
	option gateway '192.168.xx.1'

以防止流量走metric小的那根wan。

**Comment by aa65535** [comment]
@muronghan 我这里没有办法去测试，你可以测试一下关闭 UDP 的透明代理后是否还有问题。

**Comment by muronghan** [comment]
@aa65535 ，试了上述两种办法，either one or both，目前看来还不管用。现象仍是代理的流量忽高忽低，而且第一次打开，会十分缓慢。

**Comment by aa65535** [comment]
@muronghan 尝试在 mwan3 中添加一个规则，将服务器的 ip 都只走其中的一个 wan 口试试？

**Comment by muronghan** [comment]
@aa65535 好的，我试一下，不过可能要稍后一点时间。。。之前，人为在mwan3规则里倒是添加过强迫路由IP走某个口，但是似乎不行，当然，这个在尝试添加iptables -t mangle -I mwan3_hook -m set --match-set ss_spec_dst_sp dst -j MARK --set-xmark 0xff00/0xff00之前。

**Comment by muronghan** [comment]
家里移动到期了，就没再续，短期内没法再测了，先关闭了以后再说。
