### ISSUE TITLE
Cannot automatic start ss-redir during boot sometimes

### ISSUE THREAD

**Issue by AnyOfYou** [shadowsocks/luci-app-shadowsocks#67]
I got this in system log
> Thu Dec  8 04:37:01 2016 kern.info ss-redir[1034]: onetime authentication enabled
Thu Dec  8 04:37:01 2016 kern.info ss-redir[1034]: initializing ciphers... rc4-md5
Thu Dec  8 04:37:02 2016 kern.info ss-redir[1034]: tcp port reuse enabled
Thu Dec  8 04:37:02 2016 kern.info ss-redir[1034]: UDP relay enabled
Thu Dec  8 04:37:02 2016 kern.err ss-redir[1034]: [udp] getaddrinfo: ai_family not supported
Thu Dec  8 04:37:02 2016 kern.err ss-redir[1034]: [udp] bind() error

After network interface is up, I can manually start it with no problem.
Maybe we should add a hotplug script like [this](https://github.com/aa65535/openwrt-shadowvpn/blob/master/files/shadowvpn.hotplug) in the ShadowVPN luci app project to avoid this issue.

**Comment by wongsyrone** [comment]
Or just boot delay mechanism

an example: https://github.com/wongsyrone/openwrt-Pcap_DNSProxy/blob/master/files/pcap-dnsproxy.procd.init#L30

**Comment by lixingcong** [comment]
My network stack is ipv6. Met the same issue.

I have to manually click 'Save and Apply' in 'Services->Shadowsocks' after every boot.

**Comment by suikatomoki** [comment]
@lixingcong  +1 
 I also click it after boot

**Comment by simonsmh** [comment]
With start delay, is there any possibility to support domain server name?

**Comment by pexcn** [comment]
不支持吧 @simonsmh

**Comment by simonsmh** [comment]
为啥 @pexcn 
延迟启动几秒钟应该足够给DNS服务器发查询了

**Comment by suikatomoki** [comment]
@simonsmh https://github.com/shadowsocks/luci-app-shadowsocks/pull/30#issuecomment-246110155

**Comment by simonsmh** [comment]
在之前，shadowsocks不支持延时启动，所以解析域名确实有一定的次序问题，但既然有了延时启动，不妨将此功能带回。
你试试停了ss照样能正常进行dns解析，若如果担心ISP的DNS污染，也可以使用tcp/http解析。

suika <notifications@github.com>于2017年1月5日周四 20:54写道：

**Comment by suikatomoki** [comment]
@simonsmh  还是会被污染，并且路由器拨号认证也不定秒拨，延迟算不准

**Comment by pexcn** [comment]
@simonsmh 同样的问题我昨天问过 @aa65535 ，他表示延时启动只支持 ss-redir, 具体在哪个 issues 问我忘记了。。

**Comment by suikatomoki** [comment]
@pexcn  https://github.com/shadowsocks/openwrt-shadowsocks/issues/124#issuecomment-270384882

**Comment by pexcn** [comment]
对，就是这里

**Comment by aa65535** [comment]
@pexcn 那里说的是域名不是延迟启动，延迟启动是全局的。

另外，与本 issues 无关的讨论可以到对应的 issues 或者另开。
