### ISSUE TITLE
增加 ss-libev obfs（混淆）分支新特性兼容

### ISSUE THREAD

**Issue by simonsmh** [shadowsocks/luci-app-shadowsocks#68]
https://github.com/shadowsocks/shadowsocks-libev/tree/obfs

**Comment by pexcn** [comment]
等 obfs 的更新合并到 master 分支再做也不迟嘛

**Comment by aa65535** [comment]
add in https://github.com/shadowsocks/luci-app-shadowsocks/commit/842977fac20ed12757265ea36def4b7b0159cb81
