### ISSUE TITLE
优先级高于ss_spec_dst_fw的白名单

### ISSUE THREAD

**Issue by Nullizer** [shadowsocks/luci-app-shadowsocks#69]
我使用这篇wiki里的方案采用gfwlist智能翻墙：https://github.com/shadowsocks/luci-app-shadowsocks/wiki/GfwList-Support

但是有一个问题就是gfwlist里的google.com有一个子域名dl.google.com在合理的DNS配置下可以被正确解析到北京的google服务器，不翻墙反而更快，在更新大块头Android SDK时尤其有用。

但是现在解析出北京的IP也会被加入到ss_spec_dst_fw这个ipset，导致访问速度反而慢。

即便加入了忽略Chnroute的功能也没有用，因为Chnroute被加入到ss_spec_dst_bp，它的优先级也没有ss_spec_dst_fw高。

所以就像标题说的，能不能搞一个优先级高于ss_spec_dst_fw的白名单出来？

**Comment by aa65535** [comment]
加到 Dnsmasq 的配置文件中
```
address=/dl.google.com/{北京Google服务器}

    OR

server=/dl.google.com/{dns_server}
ipset=/dl.google.com/ss_spec_dst_bp
```

**Comment by Nullizer** [comment]
ss_spec_dst_bp在iptables规则里的优先级没有ss_spec_dst_fw高吧，你确定这样没问题？

**Comment by aa65535** [comment]
只要不将这个IP添加进 ss_spec_dst_fw 就行了，没必要另外加一个比 ss_spec_dst_fw 优先级高的 ipset.
