### ISSUE TITLE
 commit fbc8530 无法启动或者停止ss-redir

### ISSUE THREAD

**Issue by hzqim** [shadowsocks/luci-app-shadowsocks#7]
系统：OpenWRT trunk r49881
CPU：mt7628AN

 commit 6363d89 能正常开启或者关闭。
新 luci 很赞，谢谢辛苦编写！

**Comment by aa65535** [comment]
我这里无法复现此问题，尝试执行一下下面命令
```
killall -9 ss-redir
killall -9 ss-tunnel
/etc/init.d/shadowsocks start
```

**Comment by hzqim** [comment]
具体是这样的：

在luci界面选择启动ss，保存应用了几次都提示“未运行”
通过netstat -nlp 查看，列表中没有 ss-redir/ss-tunnel
接着，运行 /etc/init.d/shadowsocks start 
界面提示“运行中”，netstat -nlp 也能看到 ss-redir 在运行，
这时候，在luci界面选择 停止shadowsocks ，保存应用之后，
界面依然提示“运行中”，netstat -nlp 依然还能看到 ss-redir在运行。

我现在已经回退到 6363d89，暂时没有发现问题。

**Comment by aa65535** [comment]
是自己编译 ipk 安装的吗？如果是请提供 ipk 文件.
到 「系统 - 启动项」里面看一下 `shadowsocks` 是否是启用状态.

**Comment by hzqim** [comment]
是自己编译的。
第一次反馈，没有经验，ipk文件已经被删除。
非常抱歉！

**Comment by aa65535** [comment]
在 6363d89d27f05b42761a64f8133c65676e0c26d3 之后并没有做太多gaid3, 一个可能的原因就是没有 enable, 或者是 ucitrack 信息没有写入.

先 close 了, 如果还有问题可以继续反馈.

**Comment by lrinQVQ** [comment]
Openwrt版本:Designated Driver 49881
Openwrt luci版本:LuCI Master (git-16.229.34804-46755e2)
发现了同样的问题
killall -9 ss-redir提示killall: ss-redir: no process killed
killall -9 ss-tunnel提示killall: ss-tunnel: no process killed
系统 - 启动项中shadowsocks为启用状态
Shadowsocks-libev 和 luci-app-shadowsocks在编译时已添加

**Comment by aa65535** [comment]
@lrinQVQ 是直接将  luci-app-shadowsocks 编译到固件中了？

看一下下面的两条命令是否有输出
```sh
uci show ucitrack.@shadowsocks[-1]
uci show firewall.shadowsocks
```

**Comment by lrinQVQ** [comment]
@aa65535 全部提示:uci: Entry not found

**Comment by aa65535** [comment]
那就是 ucitrack 没有写入, ipk 中有一个 postinst-pkg 脚本，看来是没执行.
```sh
#!/bin/sh
uci -q batch <<-EOF >/dev/null 2>&1
	delete ucitrack.@shadowsocks[-1]
	add ucitrack shadowsocks
	set ucitrack.@shadowsocks[-1].init=shadowsocks_
	commit ucitrack
	delete firewall.shadowsocks
	set firewall.shadowsocks=include
	set firewall.shadowsocks.type=script
	set firewall.shadowsocks.path=/var/etc/shadowsocks.include_
	set firewall.shadowsocks.reload=1
	commit firewall
EOF
exit 0
```
您提到 6363d89 是正常的，是包括这个提交本身了吗？因为是这个提交修改了 postinst 脚本.

**Comment by lrinQVQ** [comment]
@aa65535 非常抱歉,我还没有退回分支去测试,我直接使用的最新的commit编译的

**Comment by lrinQVQ** [comment]
@aa65535 已回退6363d89 commit重新编译了一次,和之前一样orz,我退回上一个commit试试

**Comment by aa65535** [comment]
@lrinQVQ 您测试一下最新的提交，看看问题是否有解决

**Comment by lrinQVQ** [comment]
@aa65535 好的

**Comment by lrinQVQ** [comment]
@aa65535 一切正常,非常感谢～
