### ISSUE TITLE
内核不兼容如何使用？

### ISSUE THREAD

**Issue by BrushXue** [shadowsocks/luci-app-shadowsocks#70]
路由器是WRT1200AC，刷的是https://downloads.openwrt.org/people/kaloz/ 里面的系统（这个版本WiFi驱动比较新，5G不会掉速），但是安装时报错，和内核不兼容

```
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-shadowsocks:
 * 	kernel (= 3.18.23-1-81be0e40bf30c51dba2c46c84dd50f29) * 	kernel (= 3.18.23-1-81be0e40bf30c51dba2c46c84dd50f29) * 
 * opkg_install_cmd: Cannot install package luci-app-shadowsocks.
```

试着忽略依赖安装，设置好服务器以后，系统里有ss-local的进程，但是完全没有代理。
如果是用官方的稳定版应该没啥问题，但是[mwlwifi-bin](https://github.com/NemoAlex/mwlwifi-bin)好久没更新了，那个驱动还是经常掉速。所以我除了自己编译之外还有别的替代方案吗？

**Comment by aa65535** [comment]
应该是这个系统没有带 ipset, 可以让开发者添加这个软件包，或者使用 [ss-rules-without-ipset](https://github.com/shadowsocks/luci-app-shadowsocks/blob/master/files/root/usr/bin/ss-rules-without-ipset) 替换 ss-rules, 不过性能会差很多。
