### ISSUE TITLE
openwrt源里的包好久都没更新过

### ISSUE THREAD

**Issue by suikatomoki** [shadowsocks/luci-app-shadowsocks#71]
http://openwrt-dist.sourceforge.net/releases/ar71xx/packages
http://openwrt-dist.sourceforge.net/releases/luci/packages

最新版还停留在：
luci-app-shadowsocks_1.1.0-1_all.ipk
shadowsocks-libev_2.4.8-3_ar71xx.ipk

可否通知管理者及时更新一下，谢谢

**Comment by aa65535** [comment]
http://openwrt-dist.sourceforge.net/packages/

**Comment by suikatomoki** [comment]
@aa65535 shit 是我没注意... 明明首页教程就写了地址

**Comment by DreamSeason** [comment]
这几天出的新版还是没有在上面的地址更新。 母鸡这算不算得上是个问题  :D

**Comment by suikatomoki** [comment]
@DreamSeason  有更新的，你和我一样，地址弄错，最新版正好是2.6.1 http://openwrt-dist.sourceforge.net/packages/OpenWrt/base/ar71xx/

**Comment by DreamSeason** [comment]
:D 谢谢你的回复，具体的ipk有更新的，问题主要是不能通过自带的opkg update检测到。有兴趣可以看看我这提过的一个issue，https://github.com/shadowsocks/luci-app-shadowsocks/issues/51

**Comment by suikatomoki** [comment]
@DreamSeason  不应该是 opkg list-upgradable 吗

**Comment by suikatomoki** [comment]
![qq 20170108203323](https://cloud.githubusercontent.com/assets/10336224/21749810/b7548182-d5e1-11e6-9923-68d42fe2cd53.png)

@DreamSeason

**Comment by DreamSeason** [comment]
但是现在我list的为空  =-=  wtf

**Comment by DreamSeason** [comment]
root@OpenWrt:~# opkg update
Downloading http://openwrt-dist.sourceforge.net/dist/luci/Packages.
Updated list of available packages in /var/opkg-lists/luci.
Downloading http://openwrt-dist.sourceforge.net/dist/base/ar71xx/Packages.
Updated list of available packages in /var/opkg-lists/ss.

@suikatomoki OK，估计原因是这个。url又改了=-=

**Comment by suikatomoki** [comment]
@DreamSeason 蠢蠢哒！

**Comment by DreamSeason** [comment]
@suikatomoki 0-0  谁知道突然换源了呢。 BTW，也是很久没更新了。
