### ISSUE TITLE
unrecognized option `--obfs-host'

### ISSUE THREAD

**Issue by suikatomoki** [shadowsocks/luci-app-shadowsocks#72]
![qq 20161228152253](https://cloud.githubusercontent.com/assets/10336224/21516369/7e9265d0-cd12-11e6-8c88-e49b9c804975.png)
![qq 20161228152327](https://cloud.githubusercontent.com/assets/10336224/21516370/8226148a-cd12-11e6-9c75-f6bb750b7f22.png)
![qq 20161228152341](https://cloud.githubusercontent.com/assets/10336224/21516372/8322cafe-cd12-11e6-92d0-90f798592efa.png)
![qq 20161228152826](https://cloud.githubusercontent.com/assets/10336224/21516373/8401ba5c-cd12-11e6-800f-1f509b22bf12.png)

**Comment by aa65535** [comment]
fix in https://github.com/shadowsocks/luci-app-shadowsocks/commit/567eaa901b4dde9e4bbab76e1c2ce7fd833b3856

**Comment by aa65535** [comment]
这个选项只能在 shadowsocks-libev 2.6.0 上使用，低于这个版本是会报错的，另外 ipk 是在哪里下载安装的？

**Comment by suikatomoki** [comment]
@aa65535  启动失败他竟然提示shadowsocks-libev 2.4.8，我觉得不对劲把
https://dl.bintray.com/aa65535/opkg/shadowsocks-libev/2.6.0/OpenWrt/ar71xx/
http://openwrt-dist.sourceforge.net/packages/OpenWrt/base/ar71xx/
这两个都试了，还是报错。

**Comment by aa65535** [comment]
分别执行 `/usr/bin/ss-redir -h` 和 `ss-redir -h` 看一下打印的版本信息是否相同。

**Comment by suikatomoki** [comment]
@aa65535 可以，执行之后并不相同，看来是升级后遗症，解决了，谢谢

**Comment by aa65535** [comment]
可能是你之前安装的版本，位置不是在 `/usr/bin/`, 所以升级后没有被覆盖。
另外需要重新安装一下 luci-app-shadowsocks, 之前的版本有问题。
