### ISSUE TITLE
LEDE TLS不能用

### ISSUE THREAD

**Issue by muronghan** [shadowsocks/luci-app-shadowsocks#73]
自己编译的LEDE，按本页教程编译的openwrt-shadowsocks，ShadowSocks不能用TLS，现象是连不上，而且服务端要重启，否则不能继续工作。HTTP似乎正常。

OpenWrt两者都可用，似乎正常。

**Comment by cokebar** [comment]
mbedtls or openssl

**Comment by aa65535** [comment]
https://github.com/shadowsocks/shadowsocks-libev/issues/1019

**Comment by muronghan** [comment]
@cokebar 应该是openssl版本吧。

**Comment by cokebar** [comment]
@muronghan I've tried and I have the same problem. I also got handshake error when using obfs-tls, and the server side will soon block the IP so you must restart the server side to make it work again.
