### ISSUE TITLE
可以添加“仅代理低位端口”选项

### ISSUE THREAD

**Issue by t123yh** [shadowsocks/luci-app-shadowsocks#74]
例如，仅代理 1 - 1024 端口的访问，避免 ED2K 下载时可能造成的意外。
我不知道提出功能需求是否失礼，如果是，请忽略，并关闭 Issue。

**Comment by aa65535** [comment]
这个选项可能会在以后添加，目前可用使用 ipt_ext 配置解决：
https://github.com/shadowsocks/openwrt-shadowsocks/issues/36#issuecomment-77681549

**Comment by pexcn** [comment]
是否还可以添加 『不代理 %s 端口』的选项？@aa65535

**Comment by aa65535** [comment]
@pexcn 输入框可以选择自定义填写。

**Comment by muronghan** [comment]
@aa65535 我看到新的luci版本已经支持端口的设置，很棒！。。另外，start delay是什么？随便怎么填写都可以，而且服务端不需要设置？
