### ISSUE TITLE
添加域名列表支持

### ISSUE THREAD

**Issue by cokebar** [shadowsocks/luci-app-shadowsocks#78]
1、检测dnsmasq-full  （uci实现）
2、利用域名列表生成ipset规则（走代理的域名，不走代理的域名） （shell script实现）
3、修改dnsmasq.conf （uci实现）
4、重启dnsmasq（uci实现）

之前都是我手动设置的，不过看起来自动设置应该没啥问题。
这样单通过luci就可以设置为gfwlist方案、或者利用dnsmasq-chinalist来彻底避免国内域名走代理，省去手动设置的麻烦。
只是提出建议，不知道实际实现会不会有麻烦。^v^

如果只是shell script我还能解决，不过luci部分我目前无能为力啊；好想帮点忙但是完全帮不上

**Comment by aa65535** [comment]
不打算添加这些功能（控制 Dnsmasq），因为它们不应当由 luci-app-shadowsocks 去做的。
或许可以添加一个 luci-app-dnsmasq 去做这些事情。
