### ISSUE TITLE
配置页面报错

### ISSUE THREAD

**Issue by shao222** [shadowsocks/luci-app-shadowsocks#8]
opkg install luci-app-shadowsocks_1.1.1-1_all.ipk
opkg install shadowsocks-libev_2.4.8-3_mvebu.ipk

OpenWrt Chaos Calmer 15.05.1  Linksys WRT1900ACv2

打开配置页面报错，请问我该如何做？

> /usr/lib/lua/luci/dispatcher.lua:433: Failed to execute cbi dispatcher target for entry '/admin/services/shadowsocks'.
The called action terminated with an exception:
/usr/lib/lua/luci/cbi.lua:52: Model 'shadowsocks' not found!
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:433: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:168: in function </usr/lib/lua/luci/dispatcher.lua:167>

**Comment by aa65535** [comment]
尝试一下 `rm -rf /tmp/luci-*`

**Comment by cokebar** [comment]
遇到过 重启可破

**Comment by aa65535** [comment]
如果是从 `luci-app-shadowsocks-spec` 更新到 `luci-app-shadowsocks` 是会遇到这个问题, 删除 `/tmp/luci-modulecache` 就行了.
