### ISSUE TITLE
when selected  new server profile,then press save&apply ,SS programme can't stop and load new profile. 

### ISSUE THREAD

**Issue by uglee** [shadowsocks/luci-app-shadowsocks#80]
my env is Linux OpenWrt 3.18.23 #2 SMP Wed Jan 11 15:55:29 HKT 2017 i686 GNU/Linux
when selected  new server profile,then press save&apply ,SS programme can't stop and load new profile. 
and i try to fix it .
vi  /etc/init.d/shadowsocks 
gen_config_file() {
	cat <<-EOF >$CONFIG_FILE
		{
		    "server": "$(uci_get_by_name $1 server)",
		    "server_port": $(uci_get_by_name $1 server_port),
		    "local_address": "0.0.0.0",
		    "password": "$(uci_get_by_name $1 password)",
		    "timeout": "$(uci_get_by_name $1 timeout 60)",
		    "method": "$(uci_get_by_name $1 encrypt_method)"
		}
start() {
	pidof ss-redir ss-tunnel ss-rules ss-local | xargs  kill -9
	mkdir -p /var/run /var/etc
	ss_redir && rules
	ss_local
	ss_tunnel
stop() {
	pidof ss-redir ss-tunnel ss-rules ss-local | xargs  kill -9
	#/usr/bin/ss-rules -f
	#kill_all ss-redir ss-local ss-tunnel

**Comment by iYUYUE** [comment]
Same thing here. luci-app-shadowsocks 1.5.0 on OpenWrt BB.
