### ISSUE TITLE
请问一下iptables-mod-tproxy在make menuconfig的哪个目录里面？

### ISSUE THREAD

**Issue by terrytw** [shadowsocks/luci-app-shadowsocks#81]
作者你好

我自己编译了一个OPENWRT的系统，别的都运行良好，就是不能装IPTABLES-MOD-TPROXY来开启UDP转发，因为系统内核版本比较高（我的是3.18.45，需求的是3.18.20）
搜索发现了这个ISSUE: https://github.com/shadowsocks/openwrt-shadowsocks/issues/284

现在想如果用自己的环境编译出来的TPROXY是不是就不会出现这个问题了
但是找来找去在MAKE MENUCONFIG里面怎么也找不到这个TPROXY...

诚心求教一下

**Comment by aa65535** [comment]
```
  x Symbol: DEFAULT_iptables-mod-tproxy [=DEFAULT_iptables-mod-tproxy]                                          x  
  x Type  : unknown                                                                                             x  
  x                                                                                                             x  
  x                                                                                                             x  
  x Symbol: PACKAGE_iptables-mod-tproxy [=y]                                                                    x  
  x Type  : tristate                                                                                            x  
  x Prompt: iptables-mod-tproxy................ Transparent proxy iptables extensions                           x  
  x   Location:                                                                                                 x  
  x     -> Network                                                                                              x  
  x       -> Firewall                                                                                           x  
  x (1)     -> iptables................................. IP firewall administration tool (PACKAGE_iptables [=y] x  
  x   Defined at tmp/.config-package.in:15370                                                                   x  
  x   Depends on: PACKAGE_iptables [=y]                                                                         x  
  x   Selects: PACKAGE_libpthread [=n] && PACKAGE_librt [=n] && PACKAGE_libssp [=n] && PACKAGE_libc [=y] && PAC x  
```

**Comment by terrytw** [comment]
你好，非常不好意思又打扰了

我重新编译了一个自带tproxy的openwrt
但是UDP转发还是不可用，依然显示tproxy或者IP缺失

我看了一下xt_tproxy已经加载了，规则如下：

root@OpenWrt:~# iptables-save -t mangle
# Generated by iptables-save v1.4.21 on Sat Jan 21 10:43:49 2017
*mangle
:PREROUTING ACCEPT [19022:10368413]
:INPUT ACCEPT [11961:5473748]
:FORWARD ACCEPT [7018:4884589]
:OUTPUT ACCEPT [11816:5815107]
:POSTROUTING ACCEPT [18834:10699696]
:fwmark - [0:0]
:mssfix - [0:0]
-A PREROUTING -j fwmark
-A FORWARD -j mssfix
-A mssfix -o pppoe-wan -p tcp -m tcp --tcp-flags SYN,RST SYN -m comment --comment "wan (mtu_fix)" -j TCPMSS --clamp-mss-to-pmtu
-A mssfix -o eth1 -p tcp -m tcp --tcp-flags SYN,RST SYN -m comment --comment "wan (mtu_fix)" -j TCPMSS --clamp-mss-to-pmtu
COMMIT
# Completed on Sat Jan 21 10:43:49 2017

烦请看一下哪里有问题可以吗？

**Comment by aa65535** [comment]
那就是还缺少 ip 或者 ip-full 这个包。

2017年1月21日 10:48，terrytw <notifications@github.com>写道：

你好，非常不好意思又打扰了

我重新编译了一个自带tproxy的openwrt
但是UDP转发还是不可用，依然显示tproxy或者IP缺失

我看了一下xt_tproxy已经加载了，规则如下：

root@OpenWrt:~# iptables-save -t mangle

Generated by iptables-save v1.4.21 on Sat Jan 21 10:43:49 2017

*mangle
:PREROUTING ACCEPT [19022:10368413]
:INPUT ACCEPT [11961:5473748]
:FORWARD ACCEPT [7018:4884589]
:OUTPUT ACCEPT [11816:5815107]
:POSTROUTING ACCEPT [18834:10699696]
:fwmark - [0:0]
:mssfix - [0:0]
-A PREROUTING -j fwmark
-A FORWARD -j mssfix
-A mssfix -o pppoe-wan -p tcp -m tcp --tcp-flags SYN,RST SYN -m comment --comment "wan (mtu_fix)" -j TCPMSS --clamp-mss-to-pmtu
-A mssfix -o eth1 -p tcp -m tcp --tcp-flags SYN,RST SYN -m comment --comment "wan (mtu_fix)" -j TCPMSS --clamp-mss-to-pmtu
COMMIT

Completed on Sat Jan 21 10:43:49 2017

烦请看一下哪里有问题可以吗？
