### ISSUE TITLE
compiling errors

### ISSUE THREAD

**Issue by edmondfr** [shadowsocks/luci-app-shadowsocks#83]
LEDE 17.01 branch r3028

git clone https://github.com/shadowsocks/openwrt-shadowsocks.git package/shadowsocks-libev
git clone https://github.com/shadowsocks/luci-app-shadowsocks.git package/luci-app-shadowsocks

Collected errors:
* check_data_file_clashes: Package shadowsocks-libev wants to install file /home/edmond/source/build_dir/target-arm_cortex-a9+vfpv3_musl-1.1.15_eabi/root-mvebu/usr/bin/ss-rules
        But that file is already provided by package  * luci-app-shadowsocks
* opkg_install_cmd: Cannot install package shadowsocks-libev.
package/Makefile:60: recipe for target 'package/install' failed
make[2]: *** [package/install] Error 255
make[2]: Leaving directory '/home/edmond/source'
package/Makefile:102: recipe for target '/home/edmond/source/staging_dir/target-arm_cortex-a9+vfpv3_musl-1.1.15_eabi/stamp/.package_install' failed
make[1]: *** [/home/edmond/source/staging_dir/target-arm_cortex-a9+vfpv3_musl-1.1.15_eabi/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/edmond/source'
Build failed - please re-run with -j1 to see the real error message
/home/edmond/source/include/toplevel.mk:197: recipe for target 'world' failed
make: *** [world] Error 1

**Comment by aa65535** [comment]
你大概是安装了官方源里的 shadowsocks-libev
