### ISSUE TITLE
请问新版本的luci without ipset是如何工作的？

### ISSUE THREAD

**Issue by terrytw** [shadowsocks/luci-app-shadowsocks#85]
你好，打扰了

我看到新版本的LUCI可以不依赖IPSET来工作了
想请教一下现在是如何实现被忽略列表-chnroute的
因为现在在尝试用一个树莓派(装的是debian改的raspbian)来配置SS
不太明白忽略列表的iptables怎么写

不胜感激，另祝新年快乐

**Comment by aa65535** [comment]
其实就是很多条 `iptables -t nat -A SS_SPEC_WAN_AC -d xx.xx.xx.xx -j RETURN`, 如果可以的话，建议不要使用 without ipset 版本, 性能很差。
