### ISSUE TITLE
无法配合ss-libev 3.0 运行

### ISSUE THREAD

**Issue by simonsmh** [shadowsocks/luci-app-shadowsocks#88]

**Comment by suikatomoki** [comment]
关掉OTA还可以用

**Comment by simonsmh** [comment]
ss-redir: can't load library 'libsodium.so.18'

**Comment by suikatomoki** [comment]
http://openwrt-dist.sourceforge.net/packages/OpenWrt/base/ar71xx/libmbedtls_2.4.0-2_ar71xx.ipk

**Comment by suikatomoki** [comment]
http://openwrt-dist.sourceforge.net/packages/OpenWrt/base/ar71xx/libsodium_1.0.11-2_ar71xx.ipk

**Comment by simonsmh** [comment]
1505的话似乎版本低了
https://github.com/openwrt/packages/blob/for-15.05/libs/libsodium/Makefile

suika <notifications@github.com>于2017年2月3日周五 18:12写道：
