### ISSUE TITLE
OTA unsupported

### ISSUE THREAD

**Issue by coderfox** [shadowsocks/luci-app-shadowsocks#89]
`shadowsocks-libev` 2.6.3 or 3.0.0
processor ramips

When OTA enabled, there always be an error `21:47 ERROR: Unrecognized option: (null)` and all services cannot be started, while if OTA disabled, everything works.

**Comment by cokebar** [comment]
OTA is decrepted in shadowsocks-libev 3.0. Just don't enable it. luci-app-shadowsocks may will be updated later, just wait.
Use aead instead of ota.
