### ISSUE TITLE
ChaCha20-Poly1305应该被支持吗？

### ISSUE THREAD

**Issue by suikatomoki** [shadowsocks/luci-app-shadowsocks#91]
https://shadowsocks.org/en/spec/AEAD.html

文档上面没有这个加密方式

**Comment by cokebar** [comment]
https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/aead.c#L143

**Comment by suikatomoki** [comment]
![qq 20170207182334](https://cloud.githubusercontent.com/assets/10336224/22687386/c3c19df4-ed62-11e6-88ef-1a265918892a.png)
@cokebar   确实是不被支持

**Comment by simonsmh** [comment]
还有rc4 table之类的

**Comment by riobard** [comment]
chacha20-poly1305 is now safe to use if the implementation follows [SIP007](https://github.com/shadowsocks/shadowsocks-org/issues/42).

**Comment by suikatomoki** [comment]
@riobard got it
