### ISSUE TITLE
Full chain name of those chains created by shadowsocks for better understanding the logic.

### ISSUE THREAD

**Issue by DreamSeason** [shadowsocks/luci-app-shadowsocks#93]
Interested in more depth of the iptables stuff related to shadowsocks, and some chain names kept me from going on. So I'd like to ask for the full name for them. They are the following:
SS_SPEC_WAN_AC
SS_SPEC_WAN_DG
SS_SPEC_WAN_FW 
I could know fw is short for firewall. How about the other two, AC and DG?
Thanks.

**Comment by aa65535** [comment]
AC -> access control
DG -> delegate postrouting
FW -> forwarded

![iptables](https://cloud.githubusercontent.com/assets/5417786/23065089/abfa8ec6-f54e-11e6-8973-536a78393580.png)

**Comment by yuanl** [comment]
@aa65535 have you ever consider putting this chart on WiKi? I was confuse with these names too.

**Comment by DreamSeason** [comment]
@aa65535 @yuanl Do you find something strange in the chart? Why double check for the same ss_spec_dst_sp int the top 2 judge block?

**Comment by aa65535** [comment]
@yuanl Like this? https://github.com/shadowsocks/luci-app-shadowsocks/wiki/Instruction-of-ss-rules

@DreamSeason This is my mistake, I have corrected it.
