### ISSUE TITLE
上游的 ss-redir 已经支持 TFO

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/luci-app-shadowsocks#96]
https://github.com/shadowsocks/shadowsocks-libev/commit/8a40e538f87d63c05047ebce9b6c5a05e49050b0

**Comment by cokebar** [comment]
@pexcn 问个问题，如果查看TFO已经生效，帮助文档上说tcpdump出来看，但是具体内容不懂，dump出来什么样子可以断定TFO生效

**Comment by pexcn** [comment]
不太清楚。我也试过 tcpdump ss-local 的，开启了 TFO，但是没看到相应的 flag.

**Comment by myliyifei** [comment]
Wireshark抓包是可以看到fastopen的。但是我也有点不明白的事，是不是整个链路都必须开启fastopen才有效。比如从client os到ss client 到ss server 到ss server的OS参数，到目标网站的web服务器（nginx支持），有一个不开启就无效了？

**Comment by cokebar** [comment]
ss开启只是ss-server到ss client之间有效吧。
ss-redir不清楚，但是ss-local的话，访问http，至少客户端到代理这一段tfo应该是有效的。代理服务器到远程目标服务器之间这段就要看远程服务器支不支持了

**Comment by Typhonling** [comment]
@cokebar https://trello.com/c/0zU8SMno/43-tcp-fast-open
Debian 8下应该是grep '^TcpExt:' /proc/net/netstat | cut -d ' ' -f 91-96 | column -t
通信前后观察TCPFastOpenPassive是否有变化
