### ISSUE TITLE
name the sever section.

### ISSUE THREAD

**Issue by yuanl** [shadowsocks/luci-app-shadowsocks#97]
All server only have a meaningless CFGID even I set the alias for them. This will make it harder to switch the server without Luci.
What is **cfg104a8f** when we edit the config file?
```
config transparent_proxy
	option local_port '1234'
	option udp_relay_server 'same'
	option main_server 'cfg104a8f'
```

We should give it a name like this
```
config servers 'linode'
	option timeout '60'
	option alias 'linode'
config transparent_proxy
	option local_port '1234'
	option udp_relay_server 'same'
	option main_server 'linode'
```

**Comment by aa65535** [comment]
You can use uci or editor to name servers section, but you can not name it on luci.

**Comment by yuanl** [comment]
I think it is possible to name a section during creation. Just like the network config did to it's interface section.
