### ISSUE TITLE
关于"添加多进程支持, 只能在多核心路由使用"的问题

### ISSUE THREAD

**Issue by DreamSeason** [shadowsocks/luci-app-shadowsocks#99]
luci上的这个更新是从luci来控制实际转发的实例运行个数么？另外这个多进程是啥意思？不是太理解，因为想不到多进程的场景，一个进程足以处理多个端口了

**Comment by aa65535** [comment]
https://github.com/shadowsocks/shadowsocks-libev/issues/493

**Comment by DreamSeason** [comment]
我更新了luci和应用程序本身，找了一下似乎没有在luci里面看到有新加的关于多进程的选项，是我遗漏了还是本身就没，需要命令行来操作

**Comment by aa65535** [comment]
只在「多核心路由」可用。

**Comment by DreamSeason** [comment]
哈哈哈，原来是程序做了判断。昨天路由不在我身边，我看到这个之后就去查了下我的3800，这下算是确定不是了。 :D Thx

**Comment by wonpn** [comment]
主机名 | LEDE
-- | --
主机型号 | Newifi-D1
固件版本 | LEDE Reboot 17.01.2 r3435-65eec8bd5f / LuCI lede-17.01 branch (git-17.152.82987-7f6fc16)
内核版本 | 4.4.71

没有多进程选项。
